/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_core/@msrc@slayers.nim.c.o /workspaces/telestorie/nimcache_wasm_core/@msrc@slayers.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw;
typedef struct tySequence__hETDgeXECLenIIi9aRQgjOA tySequence__hETDgeXECLenIIi9aRQgjOA;
typedef struct tySequence__hETDgeXECLenIIi9aRQgjOA_Content tySequence__hETDgeXECLenIIi9aRQgjOA_Content;
typedef struct tySequence__yAQ9af4LrMfsCspWq9a5u6Og tySequence__yAQ9af4LrMfsCspWq9a5u6Og;
typedef struct tySequence__yAQ9af4LrMfsCspWq9a5u6Og_Content tySequence__yAQ9af4LrMfsCspWq9a5u6Og_Content;
typedef struct tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyObject_TerminalInputParser__GHUTtss0GjS80F0ZztO53Q tyObject_TerminalInputParser__GHUTtss0GjS80F0ZztO53Q;
typedef struct tyObject_StringCsiState__yPPwgzKq9cCUo1gaKFHgn6w tyObject_StringCsiState__yPPwgzKq9cCUo1gaKFHgn6w;
typedef struct tyTuple__hSHiEU6uEtL7soi1F4tKCg tyTuple__hSHiEU6uEtL7soi1F4tKCg;
typedef struct tyObject_Table__wdMFxA8VBzcKe9cq9c9a9cPqMw tyObject_Table__wdMFxA8VBzcKe9cq9c9a9cPqMw;
typedef struct tySequence__9as8hCyx8WDhZXqXMf9bhgtA tySequence__9as8hCyx8WDhZXqXMf9bhgtA;
typedef struct tySequence__9as8hCyx8WDhZXqXMf9bhgtA_Content tySequence__9as8hCyx8WDhZXqXMf9bhgtA_Content;
typedef struct tyObject_Cell__cmvwxiDU9cRtyqddD9c1iMTA tyObject_Cell__cmvwxiDU9cRtyqddD9c1iMTA;
typedef struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ tyObject_Style__UURjArTrf2wmcCbN5MncAQ;
typedef struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__9a36bWaF9cbmf9bDveJf6DOxA tyTuple__9a36bWaF9cbmf9bDveJf6DOxA;
typedef struct tyObject_StyleConfig__9bjh0AGgwfTanQXGeML3y9aA tyObject_StyleConfig__9bjh0AGgwfTanQXGeML3y9aA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, void* ClE_0);
void* ClE_0;
} tyProc__bCvtH5ozdDDqkD8FYCmuQg;
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__yt5VDPNtUGx9cBkOVakHwdQ[6];
struct tySequence__hETDgeXECLenIIi9aRQgjOA {
  NI len; tySequence__hETDgeXECLenIIi9aRQgjOA_Content* p;
};
struct tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw {
	NI width;
	NI height;
	tySequence__hETDgeXECLenIIi9aRQgjOA cells;
	NI clipX;
	NI clipY;
	NI clipW;
	NI clipH;
	NI offsetX;
	NI offsetY;
};
struct tySequence__yAQ9af4LrMfsCspWq9a5u6Og {
  NI len; tySequence__yAQ9af4LrMfsCspWq9a5u6Og_Content* p;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len; tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q {
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
	NI counter;
};
typedef NU8 tyEnum_ParserState__6PLEBin7h1EQimLs0bNQ8Q;
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef NI64 tyArray__OVZLCdT9cxlVUwpPH2Dz8OA[16];
struct tyObject_StringCsiState__yPPwgzKq9cCUo1gaKFHgn6w {
	NI leaderlen;
	tyArray__Wfh9bjgBQ4UqJsyISUuDSuA leader;
	NI argi;
	tyArray__OVZLCdT9cxlVUwpPH2Dz8OA args;
};
struct tyObject_TerminalInputParser__GHUTtss0GjS80F0ZztO53Q {
	NIM_BOOL prevEsc;
	NIM_BOOL inEsc;
	NIM_BOOL inEscO;
	NIM_BOOL inUtf8;
	NI utf8Remaining;
	NimStringV2 utf8Buffer;
	tyEnum_ParserState__6PLEBin7h1EQimLs0bNQ8Q state;
	tyObject_StringCsiState__yPPwgzKq9cCUo1gaKFHgn6w csi;
	NI intermedlen;
	tyArray__Wfh9bjgBQ4UqJsyISUuDSuA intermed;
	NI mouseCol;
	NI mouseRow;
	NI width;
	NI height;
	NF escTimer;
	NIM_BOOL endedInEsc;
	NIM_BOOL enableEscapeTimeout;
	NI escapeTimeout;
	NIM_BOOL mouseTrackingDisabled;
	NF mouseTrackingReenableTime;
};
struct tyTuple__hSHiEU6uEtL7soi1F4tKCg {
	NU8 Field0;
	NU8 Field1;
	NU8 Field2;
};
struct tySequence__9as8hCyx8WDhZXqXMf9bhgtA {
  NI len; tySequence__9as8hCyx8WDhZXqXMf9bhgtA_Content* p;
};
struct tyObject_Table__wdMFxA8VBzcKe9cq9c9a9cPqMw {
	tySequence__9as8hCyx8WDhZXqXMf9bhgtA data;
	NI counter;
};
struct tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q {
	NIM_BOOL running;
	NI termWidth;
	NI termHeight;
	tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw currentBuffer;
	tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw previousBuffer;
	NI frameCount;
	NF totalTime;
	NF fps;
	NF lastFpsUpdate;
	NF targetFps;
	NI colorSupport;
	tySequence__yAQ9af4LrMfsCspWq9a5u6Og layers;
	tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q layerIndexCache;
	NIM_BOOL cacheValid;
	tyObject_TerminalInputParser__GHUTtss0GjS80F0ZztO53Q inputParser;
	NI lastMouseX;
	NI lastMouseY;
	void* audioSystemPtr;
	tyTuple__hSHiEU6uEtL7soi1F4tKCg themeBackground;
	tyObject_Table__wdMFxA8VBzcKe9cq9c9a9cPqMw styleSheet;
};
struct tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ {
	NimStringV2 id;
	NI z;
	NIM_BOOL visible;
	tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw buffer;
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef N_CLOSURE_PTR(void, TM__S7JoVEI2sNQ6bM1nRx3HAQ_24) (tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0);
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* x_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* y_p1, void* ClE_0);
void* ClE_0;
} tyProc__ijtkaENAqyRwfv9bZK9cSOuA;
typedef NU8 tyEnum_SortOrder__4o9bu23mZL49azIuH2sugcuQ;
typedef N_CLOSURE_PTR(NI, TM__S7JoVEI2sNQ6bM1nRx3HAQ_25) (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* x_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* y_p1, void* ClE_0);
struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ {
	NU8 r;
	NU8 g;
	NU8 b;
};
struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ {
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ fg;
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ bg;
	NIM_BOOL bold;
	NIM_BOOL underline;
	NIM_BOOL italic;
	NIM_BOOL dim;
};
struct tyObject_Cell__cmvwxiDU9cRtyqddD9c1iMTA {
	NimStringV2 ch;
	tyObject_Style__UURjArTrf2wmcCbN5MncAQ style;
};
struct tySequence__hETDgeXECLenIIi9aRQgjOA_Content { NI cap; tyObject_Cell__cmvwxiDU9cRtyqddD9c1iMTA data[SEQ_DECL_SIZE]; };
struct tySequence__yAQ9af4LrMfsCspWq9a5u6Og_Content { NI cap; tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* data[SEQ_DECL_SIZE]; };
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
	NI Field0;
	NimStringV2 Field1;
	NI Field2;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE]; };
struct tyObject_StyleConfig__9bjh0AGgwfTanQXGeML3y9aA {
	tyTuple__hSHiEU6uEtL7soi1F4tKCg fg;
	tyTuple__hSHiEU6uEtL7soi1F4tKCg bg;
	NIM_BOOL bold;
	NIM_BOOL italic;
	NIM_BOOL underline;
	NIM_BOOL dim;
};
struct tyTuple__9a36bWaF9cbmf9bDveJf6DOxA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_StyleConfig__9bjh0AGgwfTanQXGeML3y9aA Field2;
};
struct tySequence__9as8hCyx8WDhZXqXMf9bhgtA_Content { NI cap; tyTuple__9a36bWaF9cbmf9bDveJf6DOxA data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3414)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2645)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, newTermBuffer__backendsZterminalZtermbuffer_u4)(NI w_p0, NI h_p1, tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* Result);
N_LIB_PRIVATE N_NIMCALL(void, clearTransparent__backendsZterminalZtermbuffer_u170)(tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* tb_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__srcZlayers_u2146)(tySequence__yAQ9af4LrMfsCspWq9a5u6Og* x_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ*, eqdup___srcZlayers_u82)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* src_p0);
N_LIB_PRIVATE N_NIMCALL(void, invalidateLayerCache__srcZlayers_u1963)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___srcZlayers_u73)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZlayers_u76)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___srcZlayers_u79)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** dest_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, rebuildLayerCache__srcZlayers_u98)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0);
N_LIB_PRIVATE N_NIMCALL(void, clear__srcZlayers_u136)(tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___srcZlayers_u489)(tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q* t_p0, NimStringV2 key_p1, NI val_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__srcZlayers_u2005)(tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NI*, X5BX5D___srcZlayers_u2067)(tyObject_Table__wHO9bxCEQsaOZ0Zzubt3C7Q* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, delete__srcZlayers_u2255)(tySequence__yAQ9af4LrMfsCspWq9a5u6Og* x_p0, NI i_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___srcZlayers_u25)(tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* dest_p0, tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* src_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, clear__backendsZterminalZtermbuffer_u155)(tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* tb_p0, tyTuple__hSHiEU6uEtL7soi1F4tKCg bgColor_p1);
N_LIB_PRIVATE N_NIMCALL(void, sort__srcZlayers_u2365)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** a_p0, NI a_p0Len_0, tyProc__ijtkaENAqyRwfv9bZK9cSOuA cmp_p1, tyEnum_SortOrder__4o9bu23mZL49azIuH2sugcuQ order_p2);
N_LIB_PRIVATE N_NIMCALL(NI, colonanonymous___srcZlayers_u2355)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* a_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* b_p1);
N_LIB_PRIVATE N_NIMCALL(NI, cmp__system_u6638)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, compositeBufferOnto__backendsZterminalZtermbuffer_u194)(tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* dest_p0, tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static NIM_CONST tyProc__bCvtH5ozdDDqkD8FYCmuQg TM__S7JoVEI2sNQ6bM1nRx3HAQ_2 = {NIM_NIL,NIM_NIL};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_3 = { 22 | NIM_STRLIT_FLAG, "[Layer] Adding layer \'" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_4 = {22, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_3};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_5 = { 19 | NIM_STRLIT_FLAG, "\' with dimensions: " };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_6 = {19, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_5};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_7 = { 1 | NIM_STRLIT_FLAG, "x" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_8 = {1, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_7};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_9 = { 15 | NIM_STRLIT_FLAG, "[Layer] Layer \'" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_10 = {15, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_9};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_11 = { 29 | NIM_STRLIT_FLAG, "\' buffer created successfully" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_12 = {29, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_11};
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_13 = {15, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_9};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_14 = { 16 | NIM_STRLIT_FLAG, "\' added to state" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_15 = {16, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_14};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_16 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_17 = {90, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_16};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_18 = { 7 | NIM_STRLIT_FLAG, "default" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_19 = {7, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_18};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__S7JoVEI2sNQ6bM1nRx3HAQ_20 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_21 = {90, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_20};
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_23 = {90, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_16};
static const NimStringV2 TM__S7JoVEI2sNQ6bM1nRx3HAQ_26 = {90, (NimStrPayload*)&TM__S7JoVEI2sNQ6bM1nRx3HAQ_16};
N_LIB_PRIVATE tyProc__bCvtH5ozdDDqkD8FYCmuQg gCompositeHook__srcZlayers_u2346;
extern NIM_BOOL nimInErrorMode__system_u4234;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3414(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___srcZlayers_u2620)(tyProc__bCvtH5ozdDDqkD8FYCmuQg* dest_p0, tyProc__bCvtH5ozdDDqkD8FYCmuQg src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, invalidateLayerCache__srcZlayers_u1963)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0) {
	(*state_p0).cacheValid = NIM_FALSE;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ*, addLayer__srcZlayers_u2140)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NimStringV2 id_p1, NI z_p2) {
	tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* layer_1;
	NimStringV2 colontmpD__3;
	NI colontmpD__4;
	tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* colontmpD__5;
	tyArray__yt5VDPNtUGx9cBkOVakHwdQ T2_;
	tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* T3_;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg T4_;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	layer_1 = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4 = (NI)0;
	colontmpD__5 = NIM_NIL;
	T2_[0] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_4;
	T2_[1] = id_p1;
	T2_[2] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_6;
	colontmpD_ = dollar___systemZdollars_u14((*state_p0).termWidth);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[3] = colontmpD_;
	T2_[4] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_8;
	colontmpD__2 = dollar___systemZdollars_u14((*state_p0).termHeight);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[5] = colontmpD__2;
	echoBinSafe(T2_, 6);
	T3_ = NIM_NIL;
	T3_ = (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ*) nimNewObjUninit(sizeof(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ), NIM_ALIGNOF(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ));
	colontmpD__3 = eqdup___system_u2645(id_p1);
	(*T3_).id = colontmpD__3;
	colontmpD__4 = z_p2;
	(*T3_).z = colontmpD__4;
	(*T3_).visible = NIM_TRUE;
	newTermBuffer__backendsZterminalZtermbuffer_u4((*state_p0).termWidth, (*state_p0).termHeight, (&(*T3_).buffer));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	layer_1 = T3_;
	T4_[0] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_10;
	T4_[1] = id_p1;
	T4_[2] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_12;
	echoBinSafe(T4_, 3);
	clearTransparent__backendsZterminalZtermbuffer_u170((&(*layer_1).buffer));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__5 = eqdup___srcZlayers_u82(layer_1);
	add__srcZlayers_u2146((&(*state_p0).layers), colontmpD__5);
	invalidateLayerCache__srcZlayers_u1963(state_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[0] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_13;
	T5_[1] = id_p1;
	T5_[2] = TM__S7JoVEI2sNQ6bM1nRx3HAQ_15;
	echoBinSafe(T5_, 3);
	result = layer_1;
	eqwasMoved___srcZlayers_u73(&layer_1);
	eqdestroy___srcZlayers_u76(layer_1);
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___srcZlayers_u76(layer_1);
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ*, getLayer__srcZlayers_u2203)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NimStringV2 id_p1) {
	tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** layer_1;
		NI i_1;
		NI L_1;
		NI T2_;
		layer_1 = (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ**)0;
		i_1 = ((NI)0);
		T2_ = (*state_p0).layers.len;
		L_1 = T2_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				if (i_1 < 0 || i_1 >= (*state_p0).layers.len){ raiseIndexError2(i_1,(*state_p0).layers.len-1); goto BeforeRet_;
				}
				layer_1 = &(*state_p0).layers.p->data[i_1];
				{
					if (!eqStrings((*(*layer_1)).id, id_p1)) goto LA7_;
					eqcopy___srcZlayers_u79(&result, (*layer_1));
					goto BeforeRet_;
				}
LA7_: ;
				i_1 += ((NI)1);
				{
					NI T11_;
					T11_ = (*state_p0).layers.len;
					if (!!((T11_ == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u234(TM__S7JoVEI2sNQ6bM1nRx3HAQ_17);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA4: ;
		}
	}
	result = ((tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ*) NIM_NIL);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, resolveLayerIndex__srcZlayers_u2133)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NI layerId_p1) {
	NI result;
{	{
		NIM_BOOL T3_;
		NI T5_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= layerId_p1);
		if (!(T3_)) goto LA4_;
		T5_ = (*state_p0).layers.len;
		T3_ = (layerId_p1 < T5_);
LA4_: ;
		if (!T3_) goto LA6_;
		result = layerId_p1;
		goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rebuildLayerCache__srcZlayers_u98)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	clear__srcZlayers_u136((&(*state_p0).layerIndexCache));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* layer_1;
		NI i_1;
		NI i_2;
		NI L_1;
		NI T2_;
		layer_1 = NIM_NIL;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		T2_ = (*state_p0).layers.len;
		L_1 = T2_;
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA4;
				i_1 = i_2;
				if (i_2 < 0 || i_2 >= (*state_p0).layers.len){ raiseIndexError2(i_2,(*state_p0).layers.len-1); goto BeforeRet_;
				}
				eqcopy___srcZlayers_u79(&layer_1, (*state_p0).layers.p->data[i_2]);
				X5BX5Deq___srcZlayers_u489((&(*state_p0).layerIndexCache), (*layer_1).id, i_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_2 += ((NI)1);
				{
					NI T7_;
					T7_ = (*state_p0).layers.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u234(TM__S7JoVEI2sNQ6bM1nRx3HAQ_21);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
		eqdestroy___srcZlayers_u76(layer_1);
	}
	(*state_p0).cacheValid = NIM_TRUE;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, resolveLayerIndex__srcZlayers_u1965)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NimStringV2 layerId_p1) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqStrings(layerId_p1, TM__S7JoVEI2sNQ6bM1nRx3HAQ_19);
		if (T3_) goto LA4_;
		T3_ = (layerId_p1.len == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((NI)0);
		goto BeforeRet_;
	}
LA5_: ;
	{
		if (!!((*state_p0).cacheValid)) goto LA9_;
		rebuildLayerCache__srcZlayers_u98(state_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		NI* T16_;
		T13_ = (NIM_BOOL)0;
		T13_ = hasKey__srcZlayers_u2005((*state_p0).layerIndexCache, layerId_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T13_) goto LA14_;
		T16_ = (NI*)0;
		T16_ = X5BX5D___srcZlayers_u2067((&(*state_p0).layerIndexCache), layerId_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (*T16_);
		goto BeforeRet_;
	}
	goto LA11_;
LA14_: ;
	{
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, removeLayer__srcZlayers_u2248)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NimStringV2 id_p1) {
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*state_p0).layers.len;
			if (!(i_1 < T3_)) goto LA2;
			{
				if (i_1 < 0 || i_1 >= (*state_p0).layers.len){ raiseIndexError2(i_1,(*state_p0).layers.len-1); goto BeforeRet_;
				}
				if (!eqStrings((*(*state_p0).layers.p->data[i_1]).id, id_p1)) goto LA6_;
				if ((i_1) < ((NI)0) || (i_1) > ((NI)2147483647)){ raiseRangeErrorI(i_1, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
				}
				delete__srcZlayers_u2255((&(*state_p0).layers), (i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				invalidateLayerCache__srcZlayers_u1963(state_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			goto LA4_;
LA6_: ;
			{
				NI TM__S7JoVEI2sNQ6bM1nRx3HAQ_22;
				if (nimAddInt(i_1, ((NI)1), &TM__S7JoVEI2sNQ6bM1nRx3HAQ_22)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__S7JoVEI2sNQ6bM1nRx3HAQ_22);
			}
LA4_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, resizeLayers__srcZlayers_u2334)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0, NI newWidth_p1, NI newHeight_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** layer_1;
		NI i_1;
		NI L_1;
		NI T2_;
		layer_1 = (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ**)0;
		i_1 = ((NI)0);
		T2_ = (*state_p0).layers.len;
		L_1 = T2_;
		{
			while (1) {
				tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw T5_;
				if (!(i_1 < L_1)) goto LA4;
				if (i_1 < 0 || i_1 >= (*state_p0).layers.len){ raiseIndexError2(i_1,(*state_p0).layers.len-1); goto BeforeRet_;
				}
				layer_1 = &(*state_p0).layers.p->data[i_1];
				nimZeroMem((void*)(&T5_), sizeof(tyObject_TermBuffer__a0me0i7S30c79coeAcFBkWw));
				newTermBuffer__backendsZterminalZtermbuffer_u4(newWidth_p1, newHeight_p2, (&T5_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				eqsink___srcZlayers_u25((&(*(*layer_1)).buffer), (&T5_));
				clearTransparent__backendsZterminalZtermbuffer_u170((&(*(*layer_1)).buffer));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_1 += ((NI)1);
				{
					NI T8_;
					T8_ = (*state_p0).layers.len;
					if (!!((T8_ == L_1))) goto LA9_;
					failedAssertImpl__stdZassertions_u234(TM__S7JoVEI2sNQ6bM1nRx3HAQ_23);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA9_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, colonanonymous___srcZlayers_u2355)(tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* a_p0, tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ* b_p1) {
	NI result;
	result = cmp__system_u6638((*a_p0).z, (*b_p1).z);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, compositeLayers__srcZlayers_u2347)(tyObject_AppStatecolonObjectType___jrSyZ9aZLwUQnIb5lEtzv8Q* state_p0) {
	tyProc__ijtkaENAqyRwfv9bZK9cSOuA T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((gCompositeHook__srcZlayers_u2346.ClP_0 == 0))) goto LA3_;
		gCompositeHook__srcZlayers_u2346.ClE_0? gCompositeHook__srcZlayers_u2346.ClP_0(state_p0, gCompositeHook__srcZlayers_u2346.ClE_0):((TM__S7JoVEI2sNQ6bM1nRx3HAQ_24)(gCompositeHook__srcZlayers_u2346.ClP_0))(state_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NI T7_;
		T7_ = (*state_p0).layers.len;
		if (!(T7_ == ((NI)0))) goto LA8_;
		goto BeforeRet_;
	}
LA8_: ;
	clear__backendsZterminalZtermbuffer_u155((&(*state_p0).currentBuffer), (*state_p0).themeBackground);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T10_), sizeof(tyProc__ijtkaENAqyRwfv9bZK9cSOuA));
	T10_.ClP_0 = ((TM__S7JoVEI2sNQ6bM1nRx3HAQ_25) (colonanonymous___srcZlayers_u2355)); T10_.ClE_0 = NIM_NIL;
	sort__srcZlayers_u2365((((*state_p0).layers).p) ? ((*state_p0).layers.p->data) : NIM_NIL, (*state_p0).layers.len, T10_, ((tyEnum_SortOrder__4o9bu23mZL49azIuH2sugcuQ)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	invalidateLayerCache__srcZlayers_u1963(state_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ** layer_1;
		NI i_1;
		NI L_1;
		NI T12_;
		layer_1 = (tyObject_LayercolonObjectType___GgVqgNTBauiDGOm9bCEWiYQ**)0;
		i_1 = ((NI)0);
		T12_ = (*state_p0).layers.len;
		L_1 = T12_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA14;
				if (i_1 < 0 || i_1 >= (*state_p0).layers.len){ raiseIndexError2(i_1,(*state_p0).layers.len-1); goto BeforeRet_;
				}
				layer_1 = &(*state_p0).layers.p->data[i_1];
				{
					if (!(*(*layer_1)).visible) goto LA17_;
					compositeBufferOnto__backendsZterminalZtermbuffer_u194((&(*state_p0).currentBuffer), (&(*(*layer_1)).buffer));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA17_: ;
				i_1 += ((NI)1);
				{
					NI T21_;
					T21_ = (*state_p0).layers.len;
					if (!!((T21_ == L_1))) goto LA22_;
					failedAssertImpl__stdZassertions_u234(TM__S7JoVEI2sNQ6bM1nRx3HAQ_26);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA22_: ;
			} LA14: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___srcZlayers_u2609)(tyProc__bCvtH5ozdDDqkD8FYCmuQg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmsrcatslayersdotnim_Init000)(void) {
{
	gCompositeHook__srcZlayers_u2346.ClE_0 = TM__S7JoVEI2sNQ6bM1nRx3HAQ_2.ClE_0;
	gCompositeHook__srcZlayers_u2346.ClP_0 = TM__S7JoVEI2sNQ6bM1nRx3HAQ_2.ClP_0;
	nimTestErrorFlag();
}
}

