/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_sdl3_test/@mbackends@ssdl3@ssdl_fonts.nim.c.o /workspaces/telestorie/nimcache_sdl3_test/@mbackends@ssdl3@ssdl_fonts.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "SDL3_ttf/SDL_ttf.h"
#include "SDL3/SDL_error.h"
#include "SDL3/SDL_render.h"
#include "SDL3/SDL.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw;
typedef struct tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tySequence__9bTnbkRBTC5HY9cBND9azv7Gw tySequence__9bTnbkRBTC5HY9cBND9azv7Gw;
typedef struct tySequence__9bTnbkRBTC5HY9cBND9azv7Gw_Content tySequence__9bTnbkRBTC5HY9cBND9azv7Gw_Content;
typedef struct tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ;
typedef struct tySequence__IM39bYRG4nsV1TeicWPjvjg tySequence__IM39bYRG4nsV1TeicWPjvjg;
typedef struct tySequence__IM39bYRG4nsV1TeicWPjvjg_Content tySequence__IM39bYRG4nsV1TeicWPjvjg_Content;
typedef struct tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ;
typedef struct tyTuple__QtUZD4UVv4QS49cIQ6mfN0A tyTuple__QtUZD4UVv4QS49cIQ6mfN0A;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ;
typedef struct tyTuple__8UPuicltHGA3VJ3rtdHaow tyTuple__8UPuicltHGA3VJ3rtdHaow;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct tySequence__9bTnbkRBTC5HY9cBND9azv7Gw {
  NI len; tySequence__9bTnbkRBTC5HY9cBND9azv7Gw_Content* p;
};
struct tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ {
	tySequence__9bTnbkRBTC5HY9cBND9azv7Gw data;
	NI counter;
};
struct tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw {
	tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ fonts;
	TTF_Font* defaultFont;
	NF defaultSize;
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence__IM39bYRG4nsV1TeicWPjvjg {
  NI len; tySequence__IM39bYRG4nsV1TeicWPjvjg_Content* p;
};
struct tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ {
	tySequence__IM39bYRG4nsV1TeicWPjvjg data;
	NI counter;
};
struct tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ {
	tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ textures;
	NI maxCacheSize;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
struct tyTuple__QtUZD4UVv4QS49cIQ6mfN0A {
	NI Field0;
	tyTuple__XOVT24GHXwqiEj5GCsEGCA Field1;
	TTF_Font* Field2;
};
struct tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ {
	SDL_Texture* texture;
	NI width;
	NI height;
	NI lastUsed;
};
struct tyTuple__8UPuicltHGA3VJ3rtdHaow {
	NI Field0;
	NimStringV2 Field1;
	tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ Field2;
};
struct tySequence__9bTnbkRBTC5HY9cBND9azv7Gw_Content { NI cap; tyTuple__QtUZD4UVv4QS49cIQ6mfN0A data[SEQ_DECL_SIZE]; };
struct tySequence__IM39bYRG4nsV1TeicWPjvjg_Content { NI cap; tyTuple__8UPuicltHGA3VJ3rtdHaow data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u311)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw** dest_p0, tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* src_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4643)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u279)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u166)(tySequence__9bTnbkRBTC5HY9cBND9azv7Gw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw*, initFontCache__backendsZsdl3Zsdl95fonts_u40)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u157)(tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ* dest_p0, tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ, initTable__backendsZsdl3Zsdl95fonts_u54)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u148)(tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ* dest_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u302)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u590)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ** dest_p0, tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u559)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u516)(tySequence__IM39bYRG4nsV1TeicWPjvjg dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ*, initTextureCache__backendsZsdl3Zsdl95fonts_u343)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u507)(tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ* dest_p0, tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ, initTable__backendsZsdl3Zsdl95fonts_u357)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u498)(tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u581)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, init__backendsZsdl3Zsdl95fonts_u603)(void);
N_LIB_PRIVATE N_NIMCALL(NI, len__backendsZsdl3Zsdl95fonts_u652)(tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ t_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, len__backendsZsdl3Zsdl95fonts_u882)(tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ t_p0);
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_2 = { 34 | NIM_STRLIT_FLAG, "[Fonts] Failed to initialize TTF: " };
static const NimStringV2 TM__ke5zx9bh9bosnlsWNavZNJFw_3 = {34, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_2};
static const struct {
  NI cap; NIM_CHAR data[51+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_4 = { 51 | NIM_STRLIT_FLAG, "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" };
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_5 = { 39 | NIM_STRLIT_FLAG, "/usr/share/fonts/TTF/DejaVuSansMono.ttf" };
static const struct {
  NI cap; NIM_CHAR data[63+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_6 = { 63 | NIM_STRLIT_FLAG, "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf" };
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_7 = { 33 | NIM_STRLIT_FLAG, "[FontCache] Loaded default font: " };
static const NimStringV2 TM__ke5zx9bh9bosnlsWNavZNJFw_8 = {33, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_7};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_10 = { 42 | NIM_STRLIT_FLAG, "[FontCache] Warning: No default font found" };
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_12 = { 27 | NIM_STRLIT_FLAG, "[Fonts] SDL_ttf initialized" };
static const struct {
  NI cap; NIM_CHAR data[158+1];
} TM__ke5zx9bh9bosnlsWNavZNJFw_13 = { 158 | NIM_STRLIT_FLAG, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim(835, 13) `len(t) == L` the length of the table changed while iterating over it" };
static const NimStringV2 TM__ke5zx9bh9bosnlsWNavZNJFw_14 = {158, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_13};
static const NimStringV2 TM__ke5zx9bh9bosnlsWNavZNJFw_16 = {158, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_13};
N_LIB_PRIVATE NIM_CONST tyArray__24KAM9afIUgUaqBaEBB6r9bg defaultPaths__backendsZsdl3Zsdl95fonts_u206 = {{51, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_4},
{39, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_5},
{63, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_6}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ke5zx9bh9bosnlsWNavZNJFw_9 = {{42, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_10}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ke5zx9bh9bosnlsWNavZNJFw_11 = {{27, (NimStrPayload*)&TM__ke5zx9bh9bosnlsWNavZNJFw_12}}
;
N_LIB_PRIVATE tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* globalFontCache__backendsZsdl3Zsdl95fonts_u37;
N_LIB_PRIVATE tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* globalTextureCache__backendsZsdl3Zsdl95fonts_u38;
N_LIB_PRIVATE NI frameCounter__backendsZsdl3Zsdl95fonts_u39 = ((NI)0);
extern NIM_THREADVAR TFrame* framePtr__system_u2743;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4425;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2743;
	framePtr__system_u2743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4643();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2743 = (*framePtr__system_u2743).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(364, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");
	nimlf_(219, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u279)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* dest_p0) {
	eqdestroy___backendsZsdl3Zsdl95fonts_u166((*dest_p0).fonts.data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u311)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw** dest_p0, tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___backendsZsdl3Zsdl95fonts_u279((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4425);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw*, initFontCache__backendsZsdl3Zsdl95fonts_u40)(void) {
	tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* result;
	tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* T1_;
	tyObject_Table__pHZlZiWdyKeIxP1cX9aB8RQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("initFontCache", "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(33, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw*) nimNewObj(sizeof(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw), NIM_ALIGNOF(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw));
	result = T1_;
	nimlf_(281, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");	nimlf_(34, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	T2_ = initTable__backendsZsdl3Zsdl95fonts_u54(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___backendsZsdl3Zsdl95fonts_u148(&T2_); goto BeforeRet_;}
	nimlf_(281, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");	eqsink___backendsZsdl3Zsdl95fonts_u157((&(*result).fonts), T2_);
	nimlf_(35, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	(*result).defaultSize = 16.0;
	nimln_(36);	(*result).defaultFont = ((TTF_Font*) NIM_NIL);
	{
		NimStringV2 path_1;
		NI i_1;
		path_1.len = 0; path_1.p = NIM_NIL;
		nimlf_(43, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(59, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");				path_1 = defaultPaths__backendsZsdl3Zsdl95fonts_u206[(i_1)- 0];
				nimln_(60);				(*result).defaultFont = TTF_OpenFont(nimToCStringConv(path_1), ((float) ((*result).defaultSize)));
				nimln_(61);				{
					tyArray__Re75IspeoxXy2oCZHwcRrA T10_;
					if (!!(((*result).defaultFont == 0))) goto LA8_;
					nimln_(62);					T10_[0] = TM__ke5zx9bh9bosnlsWNavZNJFw_8;
					T10_[1] = path_1;
					echoBinSafe(T10_, 2);
					nimln_(63);					goto LA3;
				}
LA8_: ;
				nimlf_(46, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");				{
					if (!(((NI)2) <= i_1)) goto LA13_;
					goto LA4;
				}
LA13_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA4: ;
	} LA3: ;
	nimlf_(65, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	{
		if (!((*result).defaultFont == 0)) goto LA17_;
		nimln_(66);		echoBinSafe(TM__ke5zx9bh9bosnlsWNavZNJFw_9, 1);
	}
LA17_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u302)(tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___backendsZsdl3Zsdl95fonts_u279((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u559)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* dest_p0) {
	eqdestroy___backendsZsdl3Zsdl95fonts_u516((*dest_p0).textures.data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___backendsZsdl3Zsdl95fonts_u590)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ** dest_p0, tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___backendsZsdl3Zsdl95fonts_u559((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ*, initTextureCache__backendsZsdl3Zsdl95fonts_u343)(void) {
	tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* result;
	tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* T1_;
	tyObject_Table__1SsKF9cXCnnX9bpX9cQX5WttQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("initTextureCache", "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");
{nimErr_ = nimErrorFlag();
	nimln_(70);	T1_ = NIM_NIL;
	T1_ = (tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ*) nimNewObj(sizeof(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ), NIM_ALIGNOF(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ));
	result = T1_;
	nimlf_(281, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");	nimlf_(71, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	T2_ = initTable__backendsZsdl3Zsdl95fonts_u357(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___backendsZsdl3Zsdl95fonts_u498(&T2_); goto BeforeRet_;}
	nimlf_(281, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");	eqsink___backendsZsdl3Zsdl95fonts_u507((&(*result).textures), T2_);
	nimlf_(72, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	(*result).maxCacheSize = ((NI)100);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___backendsZsdl3Zsdl95fonts_u581)(tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___backendsZsdl3Zsdl95fonts_u559((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, init__backendsZsdl3Zsdl95fonts_u603)(void) {
	tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw* T11_;
	tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ* T12_;
NIM_BOOL* nimErr_;
	nimfr_("init", "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");
{nimErr_ = nimErrorFlag();
	nimln_(76);	{
		NIM_BOOL T3_;
		NimStringV2 colontmpD_;
		tyArray__Re75IspeoxXy2oCZHwcRrA T7_;
		NCSTRING T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = TTF_Init();
		if (!!(T3_)) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(77);		T7_[0] = TM__ke5zx9bh9bosnlsWNavZNJFw_3;
		T8_ = (NCSTRING)0;
		T8_ = SDL_GetError();
		colontmpD_ = cstrToNimstr(T8_);
		T7_[1] = colontmpD_;
		echoBinSafe(T7_, 2);
		nimln_(78);		nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		goto BeforeRet_;
		{
			LA6_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimlf_(33, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	nimln_(80);	T11_ = NIM_NIL;
	T11_ = initFontCache__backendsZsdl3Zsdl95fonts_u40();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___backendsZsdl3Zsdl95fonts_u302(T11_); goto BeforeRet_;}
	nimln_(33);	eqsink___backendsZsdl3Zsdl95fonts_u311(&globalFontCache__backendsZsdl3Zsdl95fonts_u37, T11_);
	nimln_(70);	nimln_(81);	T12_ = NIM_NIL;
	T12_ = initTextureCache__backendsZsdl3Zsdl95fonts_u343();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___backendsZsdl3Zsdl95fonts_u581(T12_); goto BeforeRet_;}
	nimln_(70);	eqsink___backendsZsdl3Zsdl95fonts_u590(&globalTextureCache__backendsZsdl3Zsdl95fonts_u38, T12_);
	nimln_(82);	echoBinSafe(TM__ke5zx9bh9bosnlsWNavZNJFw_11, 1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(TTF_Font*, getDefaultFont__backendsZsdl3Zsdl95fonts_u2620)(void) {
	TTF_Font* result;
NIM_BOOL* nimErr_;
	nimfr_("getDefaultFont", "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");
{nimErr_ = nimErrorFlag();
	result = (TTF_Font*)0;
	nimln_(120);	{
		if (!(globalFontCache__backendsZsdl3Zsdl95fonts_u37 == 0)) goto LA3_;
		nimln_(121);		init__backendsZsdl3Zsdl95fonts_u603();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(122);	nimln_(118);	nimln_(122);	result = (*globalFontCache__backendsZsdl3Zsdl95fonts_u37).defaultFont;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/hashcommon.nim");
	nimlf_(27, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shutdown__backendsZsdl3Zsdl95fonts_u604)(void) {
NIM_BOOL* nimErr_;
	nimfr_("shutdown", "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(86, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");	{
		if (!!((globalFontCache__backendsZsdl3Zsdl95fonts_u37 == 0))) goto LA3_;
		{
			TTF_Font** font_1;
			NI L_1;
			font_1 = (TTF_Font**)0;
			nimlf_(831, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");			L_1 = len__backendsZsdl3Zsdl95fonts_u652((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h_1;
				NI colontmp_;
				NI T7_;
				NI res_1;
				h_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(81, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				nimlf_(832, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");				T7_ = ((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.len-1);
				colontmp_ = T7_;
				nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				res_1 = ((NI)0);
				{
					nimln_(97);					while (1) {
						NI TM__ke5zx9bh9bosnlsWNavZNJFw_15;
						if (!(res_1 <= colontmp_)) goto LA9;
						nimlf_(832, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");						h_1 = ((NI) (res_1));
						nimln_(833);						{
							NIM_BOOL T12_;
							if (h_1 < 0 || h_1 >= (*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.len){ raiseIndexError2(h_1,(*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.len-1); goto BeforeRet_;
							}
							T12_ = (NIM_BOOL)0;
							T12_ = isFilled__pureZcollectionsZtables_u31((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.p->data[h_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T12_) goto LA13_;
							nimlf_(87, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");							if (h_1 < 0 || h_1 >= (*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.len){ raiseIndexError2(h_1,(*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.len-1); goto BeforeRet_;
							}
							font_1 = &(*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts.data.p->data[h_1].Field2;
							nimln_(88);							TTF_CloseFont((*font_1));
							nimlf_(835, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");							{
								NI T17_;
								T17_ = (NI)0;
								T17_ = len__backendsZsdl3Zsdl95fonts_u652((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).fonts);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T17_ == L_1))) goto LA18_;
								failedAssertImpl__stdZassertions_u234(TM__ke5zx9bh9bosnlsWNavZNJFw_14);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
LA18_: ;
						}
LA13_: ;
						nimlf_(102, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");						if (nimAddInt(res_1, ((NI)1), &TM__ke5zx9bh9bosnlsWNavZNJFw_15)) { raiseOverflow(); goto BeforeRet_;
						};
						res_1 = (NI)(TM__ke5zx9bh9bosnlsWNavZNJFw_15);
					} LA9: ;
				}
			}
		}
		nimlf_(89, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");		{
			if (!!(((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).defaultFont == 0))) goto LA22_;
			nimln_(90);			TTF_CloseFont((*globalFontCache__backendsZsdl3Zsdl95fonts_u37).defaultFont);
		}
LA22_: ;
		nimln_(33);		eqsink___backendsZsdl3Zsdl95fonts_u311(&globalFontCache__backendsZsdl3Zsdl95fonts_u37, ((tyObject_FontCachecolonObjectType___q0MZlFv66QZdlEKPGK9adzw*) NIM_NIL));
	}
LA3_: ;
	nimln_(93);	{
		if (!!((globalTextureCache__backendsZsdl3Zsdl95fonts_u38 == 0))) goto LA26_;
		{
			tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ* cached_1;
			NI L_2;
			cached_1 = (tyObject_CachedTexture__9caVQJ7T6dUY7clLDI9bVRlQ*)0;
			nimlf_(831, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");			L_2 = len__backendsZsdl3Zsdl95fonts_u882((*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h_2;
				NI colontmp__2;
				NI T30_;
				NI res_2;
				h_2 = (NI)0;
				colontmp__2 = (NI)0;
				nimlf_(81, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				nimlf_(832, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");				T30_ = ((*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.len-1);
				colontmp__2 = T30_;
				nimlf_(96, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				res_2 = ((NI)0);
				{
					nimln_(97);					while (1) {
						NI TM__ke5zx9bh9bosnlsWNavZNJFw_17;
						if (!(res_2 <= colontmp__2)) goto LA32;
						nimlf_(832, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");						h_2 = ((NI) (res_2));
						nimln_(833);						{
							NIM_BOOL T35_;
							if (h_2 < 0 || h_2 >= (*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.len){ raiseIndexError2(h_2,(*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.len-1); goto BeforeRet_;
							}
							T35_ = (NIM_BOOL)0;
							T35_ = isFilled__pureZcollectionsZtables_u31((*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.p->data[h_2].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T35_) goto LA36_;
							nimlf_(94, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");							if (h_2 < 0 || h_2 >= (*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.len){ raiseIndexError2(h_2,(*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.len-1); goto BeforeRet_;
							}
							cached_1 = (&(*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures.data.p->data[h_2].Field2);
							nimln_(95);							SDL_DestroyTexture((*cached_1).texture);
							nimlf_(835, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/pure/collections/tables.nim");							{
								NI T40_;
								T40_ = (NI)0;
								T40_ = len__backendsZsdl3Zsdl95fonts_u882((*globalTextureCache__backendsZsdl3Zsdl95fonts_u38).textures);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T40_ == L_2))) goto LA41_;
								failedAssertImpl__stdZassertions_u234(TM__ke5zx9bh9bosnlsWNavZNJFw_16);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
LA41_: ;
						}
LA36_: ;
						nimlf_(102, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");						if (nimAddInt(res_2, ((NI)1), &TM__ke5zx9bh9bosnlsWNavZNJFw_17)) { raiseOverflow(); goto BeforeRet_;
						};
						res_2 = (NI)(TM__ke5zx9bh9bosnlsWNavZNJFw_17);
					} LA32: ;
				}
			}
		}
		nimlf_(70, "/workspaces/telestorie/backends/sdl3/sdl_fonts.nim");		eqsink___backendsZsdl3Zsdl95fonts_u590(&globalTextureCache__backendsZsdl3Zsdl95fonts_u38, ((tyObject_TextureCachecolonObjectType___57CoZdfFCDUhLb09bzHNNTQ*) NIM_NIL));
	}
LA26_: ;
	nimln_(98);	TTF_Quit();
	}BeforeRet_: ;
	popFrame();
}
