/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_sdl3_test/@mlib@sascii_art.nim.c.o /workspaces/telestorie/nimcache_sdl3_test/@mlib@sascii_art.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A;
typedef struct tyObject_Env__YOkjv76lcCADUm0ClKJM5g tyObject_Env__YOkjv76lcCADUm0ClKJM5g;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA tySequence__Gf9avO3sd1YsdKIYcdAbNvA;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content;
typedef struct tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg;
typedef struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A tyObject_Table__Kkv168EwyeC2mcswHBvZ1A;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ tySequence__2nVARL7psn6awrm07aftcQ;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ_Content tySequence__2nVARL7psn6awrm07aftcQ_Content;
typedef struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA;
typedef struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ tyObject_Style__UURjArTrf2wmcCbN5MncAQ;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ tySequence__7s5HyddQ0f9bxMNILHrXwJQ;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content;
typedef struct tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew;
typedef struct RootObj RootObj;
typedef struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g tyTuple__kuMQ1fbjJlHtwKTmBGAe6g;
typedef struct tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A;
typedef struct tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA;
typedef struct tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg;
typedef struct tyTuple__PeaKGF1vEV41H4oI8RZKYw tyTuple__PeaKGF1vEV41H4oI8RZKYw;
typedef struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ;
typedef struct tySequence__DO9b82qH3MtRoSTKL0Z6msQ tySequence__DO9b82qH3MtRoSTKL0Z6msQ;
typedef struct tySequence__DO9b82qH3MtRoSTKL0Z6msQ_Content tySequence__DO9b82qH3MtRoSTKL0Z6msQ_Content;
typedef struct tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_BoxChars__3coEb3ZQGILEougHGNaKLQ tyObject_BoxChars__3coEb3ZQGILEougHGNaKLQ;
typedef struct tyObject_BorderStyles__rctVdtnVOrVseTcnYl6vBQ tyObject_BorderStyles__rctVdtnVOrVseTcnYl6vBQ;
typedef struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA tyTuple__9bJQUgvR2blr9cUNMhbZPKyA;
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA {
  NI len; tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, ClP_0) (tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1, void* ClE_0);
void* ClE_0;
} tyProc__uEHdpYdtD80h7sXcarWpbg;
typedef NU8 tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ;
struct tySequence__2nVARL7psn6awrm07aftcQ {
  NI len; tySequence__2nVARL7psn6awrm07aftcQ_Content* p;
};
struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A {
	tySequence__2nVARL7psn6awrm07aftcQ data;
	NI counter;
};
struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA {
	NU64 a0;
	NU64 a1;
};
struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A {
	tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ kind;
	NI i;
	NF f;
	NIM_BOOL b;
	NimStringV2 s;
	tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg* fnVal;
	tyObject_Table__Kkv168EwyeC2mcswHBvZ1A map;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr;
	void* ptrVal;
	tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA randState;
};
typedef N_CLOSURE_PTR(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, TM__cQO1gSS9cJIIrf1RlWejjtw_4) (tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4, void* ClE_0);
void* ClE_0;
} tyProc__hRaIwOO1Eoq16bvREHa41g;
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ {
  NI len; tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content* p;
};
typedef struct {
N_NIMCALL_PTR(NimStringV2, ClP_0) (NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0);
void* ClE_0;
} tyProc__9cB4P2Bw7Mj9aC3M2N727hRw;
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew {
	RootObj Sup;
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules0;
	NimStringV2 default1;
};
struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
};
struct tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A {
	NI len;
	void* p;
};
struct tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA {
	RootObj Sup;
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules0;
	NimStringV2 default1;
};
struct tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg {
	RootObj Sup;
	NimStringV2 char0;
};
struct tyTuple__PeaKGF1vEV41H4oI8RZKYw {
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw Field0;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw Field1;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw Field2;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw Field3;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ {
	NU8 r;
	NU8 g;
	NU8 b;
};
struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ {
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ fg;
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ bg;
	NIM_BOOL bold;
	NIM_BOOL underline;
	NIM_BOOL italic;
	NIM_BOOL dim;
};
typedef N_CLOSURE_PTR(NimStringV2, TM__cQO1gSS9cJIIrf1RlWejjtw_54) (NI x_p0, NI y_p1, NI w_p2, NI h_p3);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_56) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(NimStringV2, TM__cQO1gSS9cJIIrf1RlWejjtw_60) (NI x_p0, NI y_p1, NI w_p2, NI h_p3);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_64) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(NimStringV2, TM__cQO1gSS9cJIIrf1RlWejjtw_67) (NI x_p0, NI y_p1, NI w_p2, NI h_p3);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_69) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(NimStringV2, TM__cQO1gSS9cJIIrf1RlWejjtw_73) (NI x_p0, NI y_p1, NI w_p2, NI h_p3);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_77) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_79) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_82) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_85) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_90) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
struct tySequence__DO9b82qH3MtRoSTKL0Z6msQ {
  NI len; tySequence__DO9b82qH3MtRoSTKL0Z6msQ_Content* p;
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw {
	NI x;
	NI y;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ chars;
	tySequence__8Np6tlClE5az1CyqZdN19bQ offsets;
};
struct tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA {
	NI a;
	NI b;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
typedef N_CLOSURE_PTR(void, TM__cQO1gSS9cJIIrf1RlWejjtw_99) (NI layer_p0, NI x_p1, NI y_p2, NimStringV2 char_p3, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p4);
struct tyObject_BoxChars__3coEb3ZQGILEougHGNaKLQ {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ solid;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ double_0;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lightBreaks;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ heavyBreaks;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ branches;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ weathered;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ corners;
};
struct tyObject_BorderStyles__rctVdtnVOrVseTcnYl6vBQ {
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ classic;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ double_0;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ rounded;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ heavy;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ weathered;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content { NI cap; tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* data[SEQ_DECL_SIZE]; };
struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* Field2;
};
struct tySequence__2nVARL7psn6awrm07aftcQ_Content { NI cap; tyTuple__9bJQUgvR2blr9cUNMhbZPKyA data[SEQ_DECL_SIZE]; };
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content { NI cap; tyTuple__kuMQ1fbjJlHtwKTmBGAe6g data[SEQ_DECL_SIZE]; };
struct tySequence__DO9b82qH3MtRoSTKL0Z6msQ_Content { NI cap; tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw data[SEQ_DECL_SIZE]; };
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, queuePluginRegistration__niminiZauto95pointer_u25)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ callback_p0);
N_LIB_PRIVATE N_NIMCALL(void, register_setSeedIfNeeded__libZascii95art_u79)(void);
N_LIB_PRIVATE N_NIMCALL(void, registerNative__niminiZruntime_u6373)(NimStringV2 name_p0, tyProc__uEHdpYdtD80h7sXcarWpbg fn_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ imports_p2, tySequence__sM4lkSb7zS6F7OVMvW9cffQ storieLibs_p3, tySequence__sM4lkSb7zS6F7OVMvW9cffQ dependencies_p4, NimStringV2 description_p5);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, niminiAuto_setSeedIfNeeded__libZascii95art_u74)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1);
static N_INLINE(NI, niminiConvertToInt__niminiZauto95bindings_u6)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4643)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, setSeedIfNeeded__libZascii95art_u72)(NI seed_p0);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u297)(NI64 seed_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valNil__niminiZruntime_u1028)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3785)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3482)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1679)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1616)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u139)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___libZascii95art_u142)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ* dest_p0, tySequence__7s5HyddQ0f9bxMNILHrXwJQ src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__libZascii95art_u160)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2710)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u88)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1641)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1644)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1758)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1695)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* dest_p0);
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u320)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1720)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1723)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1828)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1767)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* dest_p0);
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u347)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1790)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1793)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___libZascii95art_u298)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* dest_p0, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw src_p1);
N_LIB_PRIVATE N_NIMCALL(void, moduloPattern__libZascii95art_u84)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules_p0, NimStringV2 default_p1, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result);
N_LIB_PRIVATE N_NIMCALL(void, moduloPatternV__libZascii95art_u316)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules_p0, NimStringV2 default_p1, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result);
N_LIB_PRIVATE N_NIMCALL(void, solidPattern__libZascii95art_u344)(NimStringV2 char_p0, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result);
N_LIB_PRIVATE N_NIMCALL(NI, rand__libZascii95art_u725)(tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA x_p0);
static N_INLINE(tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2713)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__niminiZtype95converters_u3162)(tySequence__8Np6tlClE5az1CyqZdN19bQ* x_p0, tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__libZascii95art_u803)(tySequence__DO9b82qH3MtRoSTKL0Z6msQ* x_p0, tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niminiZtype95converters_u3045)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_2 = { 15 | NIM_STRLIT_FLAG, "setSeedIfNeeded" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_3 = {15, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_5 = { 5 | NIM_STRLIT_FLAG, "ascii" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_6 = {5, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_5};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_7 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_8 = {0, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_7};
N_LIB_PRIVATE TNimTypeV2 NTIv2__4g35yA1gggABk9bw5oTTJew_;
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_11 = { 149 | NIM_STRLIT_FLAG, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_12 = {149, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_11};
N_LIB_PRIVATE TNimTypeV2 NTIv2__1r1UCScaPi3hzezdOoZhiA_;
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_15 = {149, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_11};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Pz2DFndxoONZTnzEwGB6fg_;
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_18 = { 3 | NIM_STRLIT_FLAG, "\342\225\214" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_20 = { 3 | NIM_STRLIT_FLAG, "\342\224\254" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_22 = { 3 | NIM_STRLIT_FLAG, "\342\225\245" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_24 = { 3 | NIM_STRLIT_FLAG, "\342\224\264" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_25 = { 3 | NIM_STRLIT_FLAG, "\342\224\200" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_26 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_25};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_30 = { 3 | NIM_STRLIT_FLAG, "\342\225\250" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_32 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_25};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_34 = { 3 | NIM_STRLIT_FLAG, "\342\225\216" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_36 = { 3 | NIM_STRLIT_FLAG, "\342\224\234" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_38 = { 3 | NIM_STRLIT_FLAG, "\342\225\236" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_40 = { 3 | NIM_STRLIT_FLAG, "\342\224\244" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_41 = { 3 | NIM_STRLIT_FLAG, "\342\224\202" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_42 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_41};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_46 = { 3 | NIM_STRLIT_FLAG, "\342\225\241" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_48 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_41};
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_49 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_25};
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_50 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_25};
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_51 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_41};
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_52 = {3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_41};
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_100 = { 149 | NIM_STRLIT_FLAG, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__cQO1gSS9cJIIrf1RlWejjtw_101 = {149, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_100};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_102 = { 3 | NIM_STRLIT_FLAG, "\342\224\214" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_103 = { 3 | NIM_STRLIT_FLAG, "\342\224\220" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_104 = { 3 | NIM_STRLIT_FLAG, "\342\224\224" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_105 = { 3 | NIM_STRLIT_FLAG, "\342\224\230" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_106 = { 3 | NIM_STRLIT_FLAG, "\342\224\274" };
static const struct {
  NI cap; NimStringV2 data[11];
} TM__cQO1gSS9cJIIrf1RlWejjtw_107 = {11 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_25},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_41},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_102},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_103},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_104},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_105},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_36},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_40},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_20},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_24},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_106}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_108 = { 3 | NIM_STRLIT_FLAG, "\342\225\220" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_109 = { 3 | NIM_STRLIT_FLAG, "\342\225\221" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_110 = { 3 | NIM_STRLIT_FLAG, "\342\225\224" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_111 = { 3 | NIM_STRLIT_FLAG, "\342\225\227" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_112 = { 3 | NIM_STRLIT_FLAG, "\342\225\232" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_113 = { 3 | NIM_STRLIT_FLAG, "\342\225\235" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_114 = { 3 | NIM_STRLIT_FLAG, "\342\225\240" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_115 = { 3 | NIM_STRLIT_FLAG, "\342\225\243" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_116 = { 3 | NIM_STRLIT_FLAG, "\342\225\246" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_117 = { 3 | NIM_STRLIT_FLAG, "\342\225\251" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_118 = { 3 | NIM_STRLIT_FLAG, "\342\225\254" };
static const struct {
  NI cap; NimStringV2 data[11];
} TM__cQO1gSS9cJIIrf1RlWejjtw_119 = {11 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_108},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_109},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_110},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_111},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_112},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_113},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_114},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_115},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_116},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_117},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_118}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_120 = { 3 | NIM_STRLIT_FLAG, "\342\225\215" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_121 = { 3 | NIM_STRLIT_FLAG, "\342\224\204" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_122 = { 3 | NIM_STRLIT_FLAG, "\342\224\205" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_123 = { 3 | NIM_STRLIT_FLAG, "\342\224\206" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_124 = { 3 | NIM_STRLIT_FLAG, "\342\224\207" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_125 = { 3 | NIM_STRLIT_FLAG, "\342\224\210" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_126 = { 3 | NIM_STRLIT_FLAG, "\342\224\211" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_127 = { 3 | NIM_STRLIT_FLAG, "\342\224\212" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_128 = { 3 | NIM_STRLIT_FLAG, "\342\224\213" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_129 = { 3 | NIM_STRLIT_FLAG, "\342\225\217" };
static const struct {
  NI cap; NimStringV2 data[12];
} TM__cQO1gSS9cJIIrf1RlWejjtw_130 = {12 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_18},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_120},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_121},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_122},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_123},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_124},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_125},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_126},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_127},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_128},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_34},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_129}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_131 = { 3 | NIM_STRLIT_FLAG, "\342\225\270" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_132 = { 3 | NIM_STRLIT_FLAG, "\342\225\271" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_133 = { 3 | NIM_STRLIT_FLAG, "\342\225\272" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_134 = { 3 | NIM_STRLIT_FLAG, "\342\225\273" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_135 = { 3 | NIM_STRLIT_FLAG, "\342\225\274" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_136 = { 3 | NIM_STRLIT_FLAG, "\342\225\275" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_137 = { 3 | NIM_STRLIT_FLAG, "\342\225\276" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_138 = { 3 | NIM_STRLIT_FLAG, "\342\225\277" };
static const struct {
  NI cap; NimStringV2 data[8];
} TM__cQO1gSS9cJIIrf1RlWejjtw_139 = {8 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_131},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_132},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_133},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_134},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_135},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_136},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_137},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_138}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_140 = { 3 | NIM_STRLIT_FLAG, "\342\225\201" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_141 = { 3 | NIM_STRLIT_FLAG, "\342\225\202" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_142 = { 3 | NIM_STRLIT_FLAG, "\342\225\203" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_143 = { 3 | NIM_STRLIT_FLAG, "\342\225\204" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_144 = { 3 | NIM_STRLIT_FLAG, "\342\225\205" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_145 = { 3 | NIM_STRLIT_FLAG, "\342\225\206" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_146 = { 3 | NIM_STRLIT_FLAG, "\342\225\207" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_147 = { 3 | NIM_STRLIT_FLAG, "\342\225\210" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_148 = { 3 | NIM_STRLIT_FLAG, "\342\225\211" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_149 = { 3 | NIM_STRLIT_FLAG, "\342\225\212" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_150 = { 3 | NIM_STRLIT_FLAG, "\342\225\213" };
static const struct {
  NI cap; NimStringV2 data[16];
} TM__cQO1gSS9cJIIrf1RlWejjtw_151 = {16 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_20},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_24},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_36},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_40},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_106},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_140},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_141},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_142},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_143},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_144},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_145},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_146},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_147},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_148},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_149},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_150}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_152 = { 3 | NIM_STRLIT_FLAG, "\342\225\252" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_153 = { 3 | NIM_STRLIT_FLAG, "\342\225\253" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_154 = { 3 | NIM_STRLIT_FLAG, "\342\224\257" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_155 = { 3 | NIM_STRLIT_FLAG, "\342\224\267" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_156 = { 3 | NIM_STRLIT_FLAG, "\342\224\277" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_157 = { 3 | NIM_STRLIT_FLAG, "\342\225\200" };
static const struct {
  NI cap; NimStringV2 data[11];
} TM__cQO1gSS9cJIIrf1RlWejjtw_158 = {11 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_22},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_30},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_38},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_46},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_152},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_153},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_118},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_154},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_155},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_156},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_157}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_159 = { 3 | NIM_STRLIT_FLAG, "\342\225\255" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_160 = { 3 | NIM_STRLIT_FLAG, "\342\225\256" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_161 = { 3 | NIM_STRLIT_FLAG, "\342\225\260" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_162 = { 3 | NIM_STRLIT_FLAG, "\342\225\257" };
static const struct {
  NI cap; NimStringV2 data[12];
} TM__cQO1gSS9cJIIrf1RlWejjtw_163 = {12 | NIM_STRLIT_FLAG, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_102},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_103},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_104},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_105},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_110},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_111},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_112},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_113},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_159},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_160},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_161},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_162}}};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_164 = { 3 | NIM_STRLIT_FLAG, "\342\224\217" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_165 = { 3 | NIM_STRLIT_FLAG, "\342\224\223" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_166 = { 3 | NIM_STRLIT_FLAG, "\342\224\227" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__cQO1gSS9cJIIrf1RlWejjtw_167 = { 3 | NIM_STRLIT_FLAG, "\342\224\233" };
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_17 = {((NI)7),
((NI)3),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_18}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_19 = {((NI)11),
((NI)5),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_20}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_21 = {((NI)13),
((NI)2),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_22}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_23 = {((NI)17),
((NI)8),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_24}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_27 = {((NI)8),
((NI)2),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_18}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_28 = {((NI)12),
((NI)7),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_24}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_29 = {((NI)15),
((NI)4),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_30}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_31 = {((NI)19),
((NI)11),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_20}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_33 = {((NI)6),
((NI)2),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_34}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_35 = {((NI)9),
((NI)4),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_36}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_37 = {((NI)13),
((NI)7),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_38}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_39 = {((NI)16),
((NI)10),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_40}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_43 = {((NI)7),
((NI)3),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_34}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_44 = {((NI)10),
((NI)5),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_40}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_45 = {((NI)14),
((NI)8),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_46}}
;
static NIM_CONST tyTuple__kuMQ1fbjJlHtwKTmBGAe6g TM__cQO1gSS9cJIIrf1RlWejjtw_47 = {((NI)17),
((NI)11),
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_36}}
;
N_LIB_PRIVATE NIM_CONST tyObject_BoxChars__3coEb3ZQGILEougHGNaKLQ BoxDrawing__libZascii95art_u64 = {{11, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_107}, {11, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_119}, {12, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_130}, {8, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_139}, {16, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_151}, {11, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_158}, {12, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__cQO1gSS9cJIIrf1RlWejjtw_163}}
;
N_LIB_PRIVATE NIM_CONST tyObject_BorderStyles__rctVdtnVOrVseTcnYl6vBQ BorderCorners__libZascii95art_u71 = {{{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_102},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_103},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_104},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_105}}
, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_110},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_111},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_112},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_113}}
, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_159},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_160},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_161},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_162}}
, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_164},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_165},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_166},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_167}}
, {{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_110},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_111},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_112},
{3, (NimStrPayload*)&TM__cQO1gSS9cJIIrf1RlWejjtw_113}}
}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2743;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4425;
static NIM_CONST NU32 TM__cQO1gSS9cJIIrf1RlWejjtw_9[2] = {3701606400, 234473472};
N_LIB_PRIVATE TNimTypeV2 NTIv2__4g35yA1gggABk9bw5oTTJew_ = {.destructor = (void*)rttiDestroy__libZascii95art_u1679, .size = sizeof(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew), .align = (NI16) NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew), .depth = 1, .display = TM__cQO1gSS9cJIIrf1RlWejjtw_9, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__cQO1gSS9cJIIrf1RlWejjtw_13[2] = {3701606400, 3176401152};
N_LIB_PRIVATE TNimTypeV2 NTIv2__1r1UCScaPi3hzezdOoZhiA_ = {.destructor = (void*)rttiDestroy__libZascii95art_u1758, .size = sizeof(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA), .align = (NI16) NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA), .depth = 1, .display = TM__cQO1gSS9cJIIrf1RlWejjtw_13, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__cQO1gSS9cJIIrf1RlWejjtw_16[2] = {3701606400, 1032001024};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Pz2DFndxoONZTnzEwGB6fg_ = {.destructor = (void*)rttiDestroy__libZascii95art_u1828, .size = sizeof(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg), .align = (NI16) NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg), .depth = 1, .display = TM__cQO1gSS9cJIIrf1RlWejjtw_16, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2743;
	framePtr__system_u2743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4643();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2743 = (*framePtr__system_u2743).prev;
}
static N_INLINE(NI, niminiConvertToInt__niminiZauto95bindings_u6)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	nimfr_("niminiConvertToInt", "/workspaces/telestorie/nimini/auto_bindings.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	nimlf_(32, "/workspaces/telestorie/nimini/auto_bindings.nim");	switch ((*v_p0).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		nimln_(33);		colontmpD_ = (*v_p0).i;
		result = colontmpD_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)2):
	{
		nimln_(34);		if ((((NI) ((*v_p0).f))) < ((NI)(IL64(-9223372036854775807) - IL64(1))) || (((NI) ((*v_p0).f))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) ((*v_p0).f)), ((NI)(IL64(-9223372036854775807) - IL64(1))), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		colontmpD__2 = (((NI) ((*v_p0).f)));
		result = colontmpD__2;
	}
	break;
	default:
	{
		nimln_(35);		colontmpD__3 = ((NI)0);
		result = colontmpD__3;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4425);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setSeedIfNeeded__libZascii95art_u72)(NI seed_p0) {
NIM_BOOL* nimErr_;
	nimfr_("setSeedIfNeeded", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(103, "/workspaces/telestorie/lib/ascii_art.nim");	{
		if (!!((seed_p0 == ((NI)0)))) goto LA3_;
		nimln_(104);		randomize__pureZrandom_u297(((NI64) (seed_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, niminiAuto_setSeedIfNeeded__libZascii95art_u74)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	NI seed_1;
NIM_BOOL* nimErr_;
	nimfr_("niminiAuto_setSeedIfNeeded", "/workspaces/telestorie/nimini/auto_bindings.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(214, "/workspaces/telestorie/nimini/auto_bindings.nim");	if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
	}
	seed_1 = niminiConvertToInt__niminiZauto95bindings_u6(args_p1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(101, "/workspaces/telestorie/lib/ascii_art.nim");	nimlf_(109, "/workspaces/telestorie/nimini/auto_bindings.nim");	setSeedIfNeeded__libZascii95art_u72(seed_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(101, "/workspaces/telestorie/lib/ascii_art.nim");	nimlf_(109, "/workspaces/telestorie/nimini/auto_bindings.nim");	result = valNil__niminiZruntime_u1028();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, register_setSeedIfNeeded__libZascii95art_u79)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD_;
	tyProc__uEHdpYdtD80h7sXcarWpbg T1_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T2_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T3_;
NIM_BOOL* nimErr_;
	nimfr_("register_setSeedIfNeeded", "/workspaces/telestorie/nimini/auto_bindings.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(263);	nimZeroMem((void*)(&T1_), sizeof(tyProc__uEHdpYdtD80h7sXcarWpbg));
	T1_.ClP_0 = ((TM__cQO1gSS9cJIIrf1RlWejjtw_4) (niminiAuto_setSeedIfNeeded__libZascii95art_u74)); T1_.ClE_0 = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 0; T2_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(264);	colontmpD_.len = 1; colontmpD_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	colontmpD_.p->data[0] = TM__cQO1gSS9cJIIrf1RlWejjtw_6;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_.len = 0; T3_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(263);	registerNative__niminiZruntime_u6373(TM__cQO1gSS9cJIIrf1RlWejjtw_3, T1_, T2_, colontmpD_, T3_, TM__cQO1gSS9cJIIrf1RlWejjtw_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(2128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqdestroy___system_u3785(colontmpD_);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimlf_(364, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arithmetics.nim");
	nimln_(353);	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	nimlf_(47, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");	nimlf_(60, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T1_));
	nimlf_(48, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimlf_(521, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3482(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___libZascii95art_u595)(tyProc__hRaIwOO1Eoq16bvREHa41g* dest_p0, tyProc__hRaIwOO1Eoq16bvREHa41g src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u139)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field2.p && !(dest_p0.p->data[colontmp_].Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field2.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1616)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* dest_p0) {
	if ((*dest_p0).default1.p && !((*dest_p0).default1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).default1.p);
}
	eqdestroy___libZascii95art_u139((*dest_p0).rules0);
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1679)(void* dest_p0) {
	eqdestroy___libZascii95art_u1616(((tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew*) (dest_p0)));
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A*) (x_p0))).p == (*((tyObject_NimRawSeq__Wg4PEnfhmbJwWjx4Y6H21A*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u204)(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g* dest_p0) {
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u201)(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1 = 0;
	(*dest_p0).Field2.len = 0; (*dest_p0).Field2.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___libZascii95art_u142)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ* dest_p0, tySequence__7s5HyddQ0f9bxMNILHrXwJQ src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__libZascii95art_u160((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			(*dest_p0).p->data[colontmp_].Field1 = src_p1.p->data[colontmp_].Field1;
			eqcopy___system_u2710((&(*dest_p0).p->data[colontmp_].Field2), src_p1.p->data[colontmp_].Field2);
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u88)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0) {
	NimStringV2 result;
	tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* colonenvP__1;
NIM_BOOL* nimErr_;
	nimfr_(":anonymous", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colonenvP__1 = (tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew*) ClE_0;
	{
		tyTuple__kuMQ1fbjJlHtwKTmBGAe6g* rule_1;
		NI i_1;
		NI L_1;
		NI T2_;
		rule_1 = (tyTuple__kuMQ1fbjJlHtwKTmBGAe6g*)0;
		nimlf_(249, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = (*colonenvP__1).rules0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(110, "/workspaces/telestorie/lib/ascii_art.nim");				if (i_1 < 0 || i_1 >= (*colonenvP__1).rules0.len){ raiseIndexError2(i_1,(*colonenvP__1).rules0.len-1); goto BeforeRet_;
				}
				rule_1 = (&(*colonenvP__1).rules0.p->data[i_1]);
				nimln_(111);				{
					NI TM__cQO1gSS9cJIIrf1RlWejjtw_10;
					if ((*rule_1).Field0 == 0){ raiseDivByZero(); goto BeforeRet_;
					}
					if (nimModInt(x_p0, (*rule_1).Field0, &TM__cQO1gSS9cJIIrf1RlWejjtw_10)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_10) == (*rule_1).Field1)) goto LA7_;
					nimln_(112);					nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					eqcopy___system_u2710((&result), (*rule_1).Field2);
					goto BeforeRet_;
				}
LA7_: ;
				nimlf_(13, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T11_;
					T11_ = (*colonenvP__1).rules0.len;
					if (!!((T11_ == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u234(TM__cQO1gSS9cJIIrf1RlWejjtw_12);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA4: ;
		}
	}
	nimlf_(113, "/workspaces/telestorie/lib/ascii_art.nim");	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&result), (*colonenvP__1).default1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
	nimfr_("nimMarkCyclic", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1641)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicStatic", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");
	nimlf_(544, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(545);	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(546);		nimlf_(60, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		nimlf_(547, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(548);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(551);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(553);		rememberCycle__system_u3482(result, cell_1, desc_p1);
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1644)(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__4g35yA1gggABk9bw5oTTJew_))));
		if (!T3_) goto LA4_;
		eqdestroy___libZascii95art_u1616((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, moduloPattern__libZascii95art_u84)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules_p0, NimStringV2 default_p1, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result) {
	tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* colonenv__1;
	tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* T2_;
	tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew* blitTmp_1;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T3_;
NIM_BOOL* nimErr_;
	nimfr_("moduloPattern", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	colonenv__1 = NIM_NIL;
	nimlf_(109, "/workspaces/telestorie/lib/ascii_art.nim");	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew*) nimNewObj(sizeof(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew), NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_moduloPattern___4g35yA1gggABk9bw5oTTJew));
	(*T2_).Sup.m_type = (&NTIv2__4g35yA1gggABk9bw5oTTJew_);
	colonenv__1 = T2_;
	nimln_(110);	eqcopy___libZascii95art_u142((&(*colonenv__1).rules0), rules_p0);
	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&(*colonenv__1).default1), default_p1);
	nimlf_(109, "/workspaces/telestorie/lib/ascii_art.nim");	nimln_(106);	nimln_(109);	blitTmp_1 = colonenv__1;
	nimMarkCyclic(colonenv__1);
	nimln_(106);	eqwasMoved___libZascii95art_u1641(&colonenv__1);
	nimZeroMem((void*)(&T3_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	T3_.ClP_0 = colonanonymous___libZascii95art_u88; T3_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T3_.ClE_0;
	(*Result).ClP_0 = T3_.ClP_0;
	eqdestroy___libZascii95art_u1644(colonenv__1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___libZascii95art_u1644(colonenv__1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___libZascii95art_u298)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* dest_p0, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw src_p1) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u284)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* dest_p0) {
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___libZascii95art_u294)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw src_p0, NIM_BOOL cyclic_p1, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	colontmp_ = (*Result).ClE_0;
	(*Result).ClE_0 = src_p0.ClE_0;
	(*Result).ClP_0 = src_p0.ClP_0;
	{
		if (!src_p0.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p0.ClE_0, cyclic_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u287)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1695)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* dest_p0) {
	if ((*dest_p0).default1.p && !((*dest_p0).default1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).default1.p);
}
	eqdestroy___libZascii95art_u139((*dest_p0).rules0);
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1758)(void* dest_p0) {
	eqdestroy___libZascii95art_u1695(((tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA*) (dest_p0)));
}
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u320)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0) {
	NimStringV2 result;
	tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* colonenvP__1;
NIM_BOOL* nimErr_;
	nimfr_(":anonymous", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colonenvP__1 = (tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA*) ClE_0;
	{
		tyTuple__kuMQ1fbjJlHtwKTmBGAe6g* rule_1;
		NI i_1;
		NI L_1;
		NI T2_;
		rule_1 = (tyTuple__kuMQ1fbjJlHtwKTmBGAe6g*)0;
		nimlf_(249, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = (*colonenvP__1).rules0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(118, "/workspaces/telestorie/lib/ascii_art.nim");				if (i_1 < 0 || i_1 >= (*colonenvP__1).rules0.len){ raiseIndexError2(i_1,(*colonenvP__1).rules0.len-1); goto BeforeRet_;
				}
				rule_1 = (&(*colonenvP__1).rules0.p->data[i_1]);
				nimln_(119);				{
					NI TM__cQO1gSS9cJIIrf1RlWejjtw_14;
					if ((*rule_1).Field0 == 0){ raiseDivByZero(); goto BeforeRet_;
					}
					if (nimModInt(y_p1, (*rule_1).Field0, &TM__cQO1gSS9cJIIrf1RlWejjtw_14)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_14) == (*rule_1).Field1)) goto LA7_;
					nimln_(120);					nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					eqcopy___system_u2710((&result), (*rule_1).Field2);
					goto BeforeRet_;
				}
LA7_: ;
				nimlf_(13, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T11_;
					T11_ = (*colonenvP__1).rules0.len;
					if (!!((T11_ == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u234(TM__cQO1gSS9cJIIrf1RlWejjtw_15);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA4: ;
		}
	}
	nimlf_(121, "/workspaces/telestorie/lib/ascii_art.nim");	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&result), (*colonenvP__1).default1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1720)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1723)(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__1r1UCScaPi3hzezdOoZhiA_))));
		if (!T3_) goto LA4_;
		eqdestroy___libZascii95art_u1695((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, moduloPatternV__libZascii95art_u316)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ rules_p0, NimStringV2 default_p1, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result) {
	tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* colonenv__1;
	tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* T2_;
	tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA* blitTmp_1;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T3_;
NIM_BOOL* nimErr_;
	nimfr_("moduloPatternV", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	colonenv__1 = NIM_NIL;
	nimlf_(117, "/workspaces/telestorie/lib/ascii_art.nim");	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA*) nimNewObj(sizeof(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA), NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_moduloPatternV___1r1UCScaPi3hzezdOoZhiA));
	(*T2_).Sup.m_type = (&NTIv2__1r1UCScaPi3hzezdOoZhiA_);
	colonenv__1 = T2_;
	nimln_(110);	eqcopy___libZascii95art_u142((&(*colonenv__1).rules0), rules_p0);
	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&(*colonenv__1).default1), default_p1);
	nimlf_(117, "/workspaces/telestorie/lib/ascii_art.nim");	nimln_(115);	nimln_(117);	blitTmp_1 = colonenv__1;
	nimMarkCyclic(colonenv__1);
	nimln_(115);	eqwasMoved___libZascii95art_u1720(&colonenv__1);
	nimZeroMem((void*)(&T3_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	T3_.ClP_0 = colonanonymous___libZascii95art_u320; T3_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T3_.ClE_0;
	(*Result).ClP_0 = T3_.ClP_0;
	eqdestroy___libZascii95art_u1723(colonenv__1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___libZascii95art_u1723(colonenv__1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1767)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* dest_p0) {
	if ((*dest_p0).char0.p && !((*dest_p0).char0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).char0.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__libZascii95art_u1828)(void* dest_p0) {
	eqdestroy___libZascii95art_u1767(((tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg*) (dest_p0)));
}
N_LIB_PRIVATE N_CLOSURE(NimStringV2, colonanonymous___libZascii95art_u347)(NI x_p0, NI y_p1, NI w_p2, NI h_p3, void* ClE_0) {
	NimStringV2 result;
	tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* colonenvP__1;
	nimfr_(":anonymous", "/workspaces/telestorie/lib/ascii_art.nim");
{	result.len = 0; result.p = NIM_NIL;
	colonenvP__1 = (tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg*) ClE_0;
	nimln_(133);	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&result), (*colonenvP__1).char0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___libZascii95art_u1790)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1793)(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__Pz2DFndxoONZTnzEwGB6fg_))));
		if (!T3_) goto LA4_;
		eqdestroy___libZascii95art_u1767((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, solidPattern__libZascii95art_u344)(NimStringV2 char_p0, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* Result) {
	tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* colonenv__1;
	tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* T2_;
	tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg* blitTmp_1;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T3_;
NIM_BOOL* nimErr_;
	nimfr_("solidPattern", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	colonenv__1 = NIM_NIL;
	nimlf_(132, "/workspaces/telestorie/lib/ascii_art.nim");	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg*) nimNewObj(sizeof(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg), NIM_ALIGNOF(tyObject_Env_ascii_artdotnim_solidPattern___Pz2DFndxoONZTnzEwGB6fg));
	(*T2_).Sup.m_type = (&NTIv2__Pz2DFndxoONZTnzEwGB6fg_);
	colonenv__1 = T2_;
	nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	eqcopy___system_u2710((&(*colonenv__1).char0), char_p0);
	nimlf_(132, "/workspaces/telestorie/lib/ascii_art.nim");	nimln_(130);	nimln_(132);	blitTmp_1 = colonenv__1;
	nimMarkCyclic(colonenv__1);
	nimln_(130);	eqwasMoved___libZascii95art_u1790(&colonenv__1);
	nimZeroMem((void*)(&T3_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	T3_.ClP_0 = colonanonymous___libZascii95art_u347; T3_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T3_.ClE_0;
	(*Result).ClP_0 = T3_.ClP_0;
	eqdestroy___libZascii95art_u1793(colonenv__1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___libZascii95art_u1793(colonenv__1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, crackedBorderPattern__libZascii95art_u1015)(NI seed_p0, tyTuple__PeaKGF1vEV41H4oI8RZKYw* Result) {
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ colontmpD_;
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ colontmpD__2;
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ colontmpD__3;
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ colontmpD__4;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T1_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T2_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T3_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T4_;
NIM_BOOL* nimErr_;
	nimfr_("crackedBorderPattern", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyTuple__PeaKGF1vEV41H4oI8RZKYw));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	nimln_(281);	setSeedIfNeeded__libZascii95art_u72(seed_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	nimln_(283);	colontmpD_.len = 4; colontmpD_.p = (tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content*) newSeqPayload(4, sizeof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g), NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g));
	colontmpD_.p->data[0] = TM__cQO1gSS9cJIIrf1RlWejjtw_17;
	colontmpD_.p->data[1] = TM__cQO1gSS9cJIIrf1RlWejjtw_19;
	colontmpD_.p->data[2] = TM__cQO1gSS9cJIIrf1RlWejjtw_21;
	colontmpD_.p->data[3] = TM__cQO1gSS9cJIIrf1RlWejjtw_23;
	nimZeroMem((void*)(&T1_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	moduloPattern__libZascii95art_u84(colontmpD_, TM__cQO1gSS9cJIIrf1RlWejjtw_26, (&T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field0), T1_);
	nimln_(290);	colontmpD__2.len = 4; colontmpD__2.p = (tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content*) newSeqPayload(4, sizeof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g), NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g));
	colontmpD__2.p->data[0] = TM__cQO1gSS9cJIIrf1RlWejjtw_27;
	colontmpD__2.p->data[1] = TM__cQO1gSS9cJIIrf1RlWejjtw_28;
	colontmpD__2.p->data[2] = TM__cQO1gSS9cJIIrf1RlWejjtw_29;
	colontmpD__2.p->data[3] = TM__cQO1gSS9cJIIrf1RlWejjtw_31;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	moduloPattern__libZascii95art_u84(colontmpD__2, TM__cQO1gSS9cJIIrf1RlWejjtw_32, (&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field1), T2_);
	nimln_(297);	colontmpD__3.len = 4; colontmpD__3.p = (tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content*) newSeqPayload(4, sizeof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g), NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g));
	colontmpD__3.p->data[0] = TM__cQO1gSS9cJIIrf1RlWejjtw_33;
	colontmpD__3.p->data[1] = TM__cQO1gSS9cJIIrf1RlWejjtw_35;
	colontmpD__3.p->data[2] = TM__cQO1gSS9cJIIrf1RlWejjtw_37;
	colontmpD__3.p->data[3] = TM__cQO1gSS9cJIIrf1RlWejjtw_39;
	nimZeroMem((void*)(&T3_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	moduloPatternV__libZascii95art_u316(colontmpD__3, TM__cQO1gSS9cJIIrf1RlWejjtw_42, (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field2), T3_);
	nimln_(304);	colontmpD__4.len = 4; colontmpD__4.p = (tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content*) newSeqPayload(4, sizeof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g), NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g));
	colontmpD__4.p->data[0] = TM__cQO1gSS9cJIIrf1RlWejjtw_43;
	colontmpD__4.p->data[1] = TM__cQO1gSS9cJIIrf1RlWejjtw_44;
	colontmpD__4.p->data[2] = TM__cQO1gSS9cJIIrf1RlWejjtw_45;
	colontmpD__4.p->data[3] = TM__cQO1gSS9cJIIrf1RlWejjtw_47;
	nimZeroMem((void*)(&T4_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	moduloPatternV__libZascii95art_u316(colontmpD__4, TM__cQO1gSS9cJIIrf1RlWejjtw_48, (&T4_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field3), T4_);
	nimln_(110);	eqdestroy___libZascii95art_u139(colontmpD__4);
	eqdestroy___libZascii95art_u139(colontmpD__3);
	eqdestroy___libZascii95art_u139(colontmpD__2);
	eqdestroy___libZascii95art_u139(colontmpD_);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u1340)(tyTuple__PeaKGF1vEV41H4oI8RZKYw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Field0.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Field0.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Field1.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Field1.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Field2.ClE_0);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Field2.ClE_0);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Field3.ClE_0);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Field3.ClE_0);
	}
LA19_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, simpleBorderPattern__libZascii95art_u1077)(tyTuple__PeaKGF1vEV41H4oI8RZKYw* Result) {
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T1_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T2_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T3_;
	tyProc__9cB4P2Bw7Mj9aC3M2N727hRw T4_;
NIM_BOOL* nimErr_;
	nimfr_("simpleBorderPattern", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyTuple__PeaKGF1vEV41H4oI8RZKYw));
	nimln_(109);	nimln_(313);	nimZeroMem((void*)(&T1_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	solidPattern__libZascii95art_u344(TM__cQO1gSS9cJIIrf1RlWejjtw_49, (&T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field0), T1_);
	nimln_(314);	nimZeroMem((void*)(&T2_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	solidPattern__libZascii95art_u344(TM__cQO1gSS9cJIIrf1RlWejjtw_50, (&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field1), T2_);
	nimln_(315);	nimZeroMem((void*)(&T3_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	solidPattern__libZascii95art_u344(TM__cQO1gSS9cJIIrf1RlWejjtw_51, (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field2), T3_);
	nimln_(316);	nimZeroMem((void*)(&T4_), sizeof(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw));
	solidPattern__libZascii95art_u344(TM__cQO1gSS9cJIIrf1RlWejjtw_52, (&T4_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(109);	eqsink___libZascii95art_u298((&(*Result).Field3), T4_);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___libZascii95art_u290)(tyProc__9cB4P2Bw7Mj9aC3M2N727hRw* dest_p0, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, drawBorder__libZascii95art_u621)(NI layer_p0, NI x_p1, NI y_p2, NI width_p3, NI height_p4, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw topPattern_p5, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw bottomPattern_p6, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw leftPattern_p7, tyProc__9cB4P2Bw7Mj9aC3M2N727hRw rightPattern_p8, tyArray__sMpvt1sOxOJ3LFGulnbeMQ corners_p9, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p10, tyProc__hRaIwOO1Eoq16bvREHa41g drawProc_p11) {
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_80;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_81;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_83;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_84;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_86;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_87;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_88;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_89;
NIM_BOOL* nimErr_;
	nimfr_("drawBorder", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	{
		NI px_1;
		NI colontmp_;
		NI TM__cQO1gSS9cJIIrf1RlWejjtw_53;
		NI i_1;
		px_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		nimlf_(196, "/workspaces/telestorie/lib/ascii_art.nim");		if (nimSubInt(width_p3, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_53)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_53);
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_1 = ((NI)1);
		{
			nimln_(129);			while (1) {
				NimStringV2 char_1;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_55;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_57;
				if (!(i_1 < colontmp_)) goto LA3;
				char_1.len = 0; char_1.p = NIM_NIL;
				nimlf_(196, "/workspaces/telestorie/lib/ascii_art.nim");				px_1 = i_1;
				nimln_(197);				char_1 = topPattern_p5.ClE_0? topPattern_p5.ClP_0(px_1, ((NI)0), width_p3, height_p4, topPattern_p5.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_54)(topPattern_p5.ClP_0))(px_1, ((NI)0), width_p3, height_p4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimln_(198);				if (nimAddInt(x_p1, px_1, &TM__cQO1gSS9cJIIrf1RlWejjtw_55)) { raiseOverflow(); goto LA4_;
				};
				drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_55), y_p2, char_1, style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_56)(drawProc_p11.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_55), y_p2, char_1, style_p10);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				if (nimAddInt(i_1, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_57)) { raiseOverflow(); goto LA4_;
				};
				i_1 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_57);
				{
					LA4_:;
				}
				{
					nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					if (char_1.p && !(char_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(char_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA3: ;
		}
	}
	{
		NI px_2;
		NI colontmp__2;
		NI TM__cQO1gSS9cJIIrf1RlWejjtw_58;
		NI i_2;
		px_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimlf_(126, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		nimlf_(201, "/workspaces/telestorie/lib/ascii_art.nim");		if (nimSubInt(width_p3, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_58)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp__2 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_58);
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_2 = ((NI)1);
		{
			nimln_(129);			while (1) {
				NimStringV2 char_2;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_59;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_61;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_62;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_63;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_65;
				if (!(i_2 < colontmp__2)) goto LA9;
				char_2.len = 0; char_2.p = NIM_NIL;
				nimlf_(201, "/workspaces/telestorie/lib/ascii_art.nim");				px_2 = i_2;
				nimln_(202);				if (nimSubInt(height_p4, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_59)) { raiseOverflow(); goto LA10_;
				};
				char_2 = bottomPattern_p6.ClE_0? bottomPattern_p6.ClP_0(px_2, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_59), width_p3, height_p4, bottomPattern_p6.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_60)(bottomPattern_p6.ClP_0))(px_2, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_59), width_p3, height_p4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
				nimln_(203);				if (nimAddInt(x_p1, px_2, &TM__cQO1gSS9cJIIrf1RlWejjtw_61)) { raiseOverflow(); goto LA10_;
				};
				if (nimAddInt(y_p2, height_p4, &TM__cQO1gSS9cJIIrf1RlWejjtw_62)) { raiseOverflow(); goto LA10_;
				};
				if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_62), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_63)) { raiseOverflow(); goto LA10_;
				};
				drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_61), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_63), char_2, style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_64)(drawProc_p11.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_61), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_63), char_2, style_p10);
				if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
				nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_65)) { raiseOverflow(); goto LA10_;
				};
				i_2 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_65);
				{
					LA10_:;
				}
				{
					nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					if (char_2.p && !(char_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(char_2.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA9: ;
		}
	}
	{
		NI py_1;
		NI colontmp__3;
		NI TM__cQO1gSS9cJIIrf1RlWejjtw_66;
		NI i_3;
		py_1 = (NI)0;
		colontmp__3 = (NI)0;
		nimlf_(126, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		nimlf_(206, "/workspaces/telestorie/lib/ascii_art.nim");		if (nimSubInt(height_p4, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_66)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp__3 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_66);
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_3 = ((NI)1);
		{
			nimln_(129);			while (1) {
				NimStringV2 char_3;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_68;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_70;
				if (!(i_3 < colontmp__3)) goto LA15;
				char_3.len = 0; char_3.p = NIM_NIL;
				nimlf_(206, "/workspaces/telestorie/lib/ascii_art.nim");				py_1 = i_3;
				nimln_(207);				char_3 = leftPattern_p7.ClE_0? leftPattern_p7.ClP_0(((NI)0), py_1, width_p3, height_p4, leftPattern_p7.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_67)(leftPattern_p7.ClP_0))(((NI)0), py_1, width_p3, height_p4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				nimln_(208);				if (nimAddInt(y_p2, py_1, &TM__cQO1gSS9cJIIrf1RlWejjtw_68)) { raiseOverflow(); goto LA16_;
				};
				drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, x_p1, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_68), char_3, style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_69)(drawProc_p11.ClP_0))(layer_p0, x_p1, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_68), char_3, style_p10);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				if (nimAddInt(i_3, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_70)) { raiseOverflow(); goto LA16_;
				};
				i_3 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_70);
				{
					LA16_:;
				}
				{
					nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					if (char_3.p && !(char_3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(char_3.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA15: ;
		}
	}
	{
		NI py_2;
		NI colontmp__4;
		NI TM__cQO1gSS9cJIIrf1RlWejjtw_71;
		NI i_4;
		py_2 = (NI)0;
		colontmp__4 = (NI)0;
		nimlf_(126, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		nimlf_(211, "/workspaces/telestorie/lib/ascii_art.nim");		if (nimSubInt(height_p4, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_71)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp__4 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_71);
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_4 = ((NI)1);
		{
			nimln_(129);			while (1) {
				NimStringV2 char_4;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_72;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_74;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_75;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_76;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_78;
				if (!(i_4 < colontmp__4)) goto LA21;
				char_4.len = 0; char_4.p = NIM_NIL;
				nimlf_(211, "/workspaces/telestorie/lib/ascii_art.nim");				py_2 = i_4;
				nimln_(212);				if (nimSubInt(width_p3, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_72)) { raiseOverflow(); goto LA22_;
				};
				char_4 = rightPattern_p8.ClE_0? rightPattern_p8.ClP_0((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_72), py_2, width_p3, height_p4, rightPattern_p8.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_73)(rightPattern_p8.ClP_0))((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_72), py_2, width_p3, height_p4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				nimln_(213);				if (nimAddInt(x_p1, width_p3, &TM__cQO1gSS9cJIIrf1RlWejjtw_74)) { raiseOverflow(); goto LA22_;
				};
				if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_74), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_75)) { raiseOverflow(); goto LA22_;
				};
				if (nimAddInt(y_p2, py_2, &TM__cQO1gSS9cJIIrf1RlWejjtw_76)) { raiseOverflow(); goto LA22_;
				};
				drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_75), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_76), char_4, style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_77)(drawProc_p11.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_75), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_76), char_4, style_p10);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				if (nimAddInt(i_4, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_78)) { raiseOverflow(); goto LA22_;
				};
				i_4 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_78);
				{
					LA22_:;
				}
				{
					nimlf_(394, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");					if (char_4.p && !(char_4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(char_4.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA21: ;
		}
	}
	nimlf_(216, "/workspaces/telestorie/lib/ascii_art.nim");	drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, x_p1, y_p2, corners_p9[(((NI)0))- 0], style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_79)(drawProc_p11.ClP_0))(layer_p0, x_p1, y_p2, corners_p9[(((NI)0))- 0], style_p10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(217);	if (nimAddInt(x_p1, width_p3, &TM__cQO1gSS9cJIIrf1RlWejjtw_80)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_80), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_81)) { raiseOverflow(); goto BeforeRet_;
	};
	drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_81), y_p2, corners_p9[(((NI)1))- 0], style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_82)(drawProc_p11.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_81), y_p2, corners_p9[(((NI)1))- 0], style_p10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(218);	if (nimAddInt(y_p2, height_p4, &TM__cQO1gSS9cJIIrf1RlWejjtw_83)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_83), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_84)) { raiseOverflow(); goto BeforeRet_;
	};
	drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, x_p1, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_84), corners_p9[(((NI)2))- 0], style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_85)(drawProc_p11.ClP_0))(layer_p0, x_p1, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_84), corners_p9[(((NI)2))- 0], style_p10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(219);	if (nimAddInt(x_p1, width_p3, &TM__cQO1gSS9cJIIrf1RlWejjtw_86)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_86), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_87)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt(y_p2, height_p4, &TM__cQO1gSS9cJIIrf1RlWejjtw_88)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_88), ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_89)) { raiseOverflow(); goto BeforeRet_;
	};
	drawProc_p11.ClE_0? drawProc_p11.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_87), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_89), corners_p9[(((NI)3))- 0], style_p10, drawProc_p11.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_90)(drawProc_p11.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_87), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_89), corners_p9[(((NI)3))- 0], style_p10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA result;
	nimfr_("..", "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");
	nimlf_(436, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__DO9b82qH3MtRoSTKL0Z6msQ, generateCrackDetails__libZascii95art_u695)(NI seed_p0, NI width_p1, NI height_p2, NF density_p3, tySequence__sM4lkSb7zS6F7OVMvW9cffQ crackChars_p4) {
	tySequence__DO9b82qH3MtRoSTKL0Z6msQ result;
	NI numCracks_1;
	NI TM__cQO1gSS9cJIIrf1RlWejjtw_91;
NIM_BOOL* nimErr_;
	nimfr_("generateCrackDetails", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(250, "/workspaces/telestorie/lib/ascii_art.nim");	setSeedIfNeeded__libZascii95art_u72(seed_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(251);	result.len = 0; result.p = (tySequence__DO9b82qH3MtRoSTKL0Z6msQ_Content*) newSeqPayload(0, sizeof(tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw), NIM_ALIGNOF(tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw));
	nimln_(253);	if (nimAddInt(width_p1, height_p2, &TM__cQO1gSS9cJIIrf1RlWejjtw_91)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((((NI) (((NF)(((NF) ((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_91)))) * (NF)(density_p3))))) < ((NI)(IL64(-9223372036854775807) - IL64(1))) || (((NI) (((NF)(((NF) ((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_91)))) * (NF)(density_p3))))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (((NF)(((NF) ((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_91)))) * (NF)(density_p3)))), ((NI)(IL64(-9223372036854775807) - IL64(1))), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	numCracks_1 = (((NI) (((NF)(((NF) ((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_91)))) * (NF)(density_p3)))));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				tySequence__sM4lkSb7zS6F7OVMvW9cffQ chars_1;
				tySequence__8Np6tlClE5az1CyqZdN19bQ offsets_1;
				NI x_1;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_92;
				tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T4_;
				NI y_1;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_93;
				tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T5_;
				NI numChars_1;
				tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T6_;
				tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw T13_;
				tySequence__sM4lkSb7zS6F7OVMvW9cffQ blitTmp_1;
				tySequence__8Np6tlClE5az1CyqZdN19bQ blitTmp_2;
				NI TM__cQO1gSS9cJIIrf1RlWejjtw_96;
				if (!(i_2 < numCracks_1)) goto LA3;
				chars_1.len = 0; chars_1.p = NIM_NIL;
				offsets_1.len = 0; offsets_1.p = NIM_NIL;
				nimlf_(254, "/workspaces/telestorie/lib/ascii_art.nim");				i_1 = i_2;
				nimln_(255);				if (nimSubInt(width_p1, ((NI)3), &TM__cQO1gSS9cJIIrf1RlWejjtw_92)) { raiseOverflow(); goto BeforeRet_;
				};
				T4_ = dotdot___stdZstrbasics_u48(((NI)2), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_92));
				x_1 = rand__libZascii95art_u725(T4_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(256);				if (nimSubInt(height_p2, ((NI)2), &TM__cQO1gSS9cJIIrf1RlWejjtw_93)) { raiseOverflow(); goto BeforeRet_;
				};
				T5_ = dotdot___stdZstrbasics_u48(((NI)1), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_93));
				y_1 = rand__libZascii95art_u725(T5_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(259);				T6_ = dotdot___stdZstrbasics_u48(((NI)1), ((NI)2));
				numChars_1 = rand__libZascii95art_u725(T6_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(260);				chars_1.len = 0; chars_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
				nimln_(261);				offsets_1.len = 0; offsets_1.p = (tySequence__8Np6tlClE5az1CyqZdN19bQ_Content*) newSeqPayload(0, sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ), NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
				{
					NI j_1;
					NI i_3;
					j_1 = (NI)0;
					nimlf_(128, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");					i_3 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NimStringV2 colontmpD_;
							NI colontmpD__2;
							NI T10_;
							NI TM__cQO1gSS9cJIIrf1RlWejjtw_94;
							NI T11_;
							tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ T12_;
							NI TM__cQO1gSS9cJIIrf1RlWejjtw_95;
							if (!(i_3 < numChars_1)) goto LA9;
							colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
							colontmpD__2 = (NI)0;
							nimlf_(263, "/workspaces/telestorie/lib/ascii_art.nim");							j_1 = i_3;
							nimln_(264);							nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");							nimlf_(264, "/workspaces/telestorie/lib/ascii_art.nim");							T10_ = crackChars_p4.len;
							if (nimSubInt(T10_, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_94)) { raiseOverflow(); goto BeforeRet_;
							};
							T11_ = (NI)0;
							T11_ = rand__pureZrandom_u143((NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_94));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (T11_ < 0 || T11_ >= crackChars_p4.len){ raiseIndexError2(T11_,crackChars_p4.len-1); goto BeforeRet_;
							}
							nimlf_(1699, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system.nim");							colontmpD_ = eqdup___system_u2713(crackChars_p4.p->data[T11_]);
							nimlf_(264, "/workspaces/telestorie/lib/ascii_art.nim");							add__stdZenumutils_u70((&chars_1), colontmpD_);
							nimln_(265);							T12_.Field0 = ((NI)0);
							colontmpD__2 = j_1;
							T12_.Field1 = colontmpD__2;
							add__niminiZtype95converters_u3162((&offsets_1), T12_);
							nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");							if (nimAddInt(i_3, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_95)) { raiseOverflow(); goto BeforeRet_;
							};
							i_3 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_95);
						} LA9: ;
					}
				}
				nimlf_(267, "/workspaces/telestorie/lib/ascii_art.nim");				T13_.x = x_1;
				T13_.y = y_1;
				nimln_(270);				blitTmp_1 = chars_1;
				T13_.chars = blitTmp_1;
				nimln_(271);				blitTmp_2 = offsets_1;
				T13_.offsets = blitTmp_2;
				nimln_(267);				add__libZascii95art_u803((&result), (&T13_));
				nimlf_(131, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__cQO1gSS9cJIIrf1RlWejjtw_96)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_96);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u896)(tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw* dest_p0) {
	eqdestroy___niminiZtype95converters_u3045((*dest_p0).offsets);
	eqdestroy___system_u3785((*dest_p0).chars);
}
N_LIB_PRIVATE N_NIMCALL(void, addDetail__libZascii95art_u671)(NI layer_p0, tyObject_DetailPoint__9btyZ0VP4rI0QCqh0O8z9bDw* detail_p1, tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_p2, tyProc__hRaIwOO1Eoq16bvREHa41g drawProc_p3) {
NIM_BOOL* nimErr_;
	nimfr_("addDetail", "/workspaces/telestorie/lib/ascii_art.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2 char_1;
		NI i_1;
		NI i_2;
		NI L_1;
		NI T2_;
		char_1.len = 0; char_1.p = NIM_NIL;
		i_1 = (NI)0;
		nimlf_(182, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");		i_2 = ((NI)0);
		nimln_(183);		T2_ = (*detail_p1).chars.len;
		L_1 = T2_;
		{
			nimln_(184);			while (1) {
				if (!(i_2 < L_1)) goto LA4;
				nimlf_(238, "/workspaces/telestorie/lib/ascii_art.nim");				i_1 = i_2;
				if (i_2 < 0 || i_2 >= (*detail_p1).chars.len){ raiseIndexError2(i_2,(*detail_p1).chars.len-1); goto BeforeRet_;
				}
				char_1 = (*detail_p1).chars.p->data[i_2];
				nimln_(239);				{
					NI T7_;
					tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tmpTuple_1;
					NI dx_1;
					NI dy_1;
					NI TM__cQO1gSS9cJIIrf1RlWejjtw_97;
					NI TM__cQO1gSS9cJIIrf1RlWejjtw_98;
					T7_ = (*detail_p1).offsets.len;
					if (!(i_1 < T7_)) goto LA8_;
					nimln_(240);					if (i_1 < 0 || i_1 >= (*detail_p1).offsets.len){ raiseIndexError2(i_1,(*detail_p1).offsets.len-1); goto BeforeRet_;
					}
					tmpTuple_1 = (*detail_p1).offsets.p->data[i_1];
					dx_1 = tmpTuple_1.Field0;
					dy_1 = tmpTuple_1.Field1;
					nimln_(241);					if (nimAddInt((*detail_p1).x, dx_1, &TM__cQO1gSS9cJIIrf1RlWejjtw_97)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((*detail_p1).y, dy_1, &TM__cQO1gSS9cJIIrf1RlWejjtw_98)) { raiseOverflow(); goto BeforeRet_;
					};
					drawProc_p3.ClE_0? drawProc_p3.ClP_0(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_97), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_98), char_1, style_p2, drawProc_p3.ClE_0):((TM__cQO1gSS9cJIIrf1RlWejjtw_99)(drawProc_p3.ClP_0))(layer_p0, (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_97), (NI)(TM__cQO1gSS9cJIIrf1RlWejjtw_98), char_1, style_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
				nimlf_(13, "/home/codespace/.choosenim/toolchains/nim-2.2.6/lib/system/iterators.nim");				i_2 += ((NI)1);
				nimln_(187);				{
					NI T12_;
					T12_ = (*detail_p1).chars.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__cQO1gSS9cJIIrf1RlWejjtw_101);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___libZascii95art_u592)(tyProc__hRaIwOO1Eoq16bvREHa41g* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmlibatsascii_artdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("ascii_art", "/workspaces/telestorie/lib/ascii_art.nim");
nimErr_ = nimErrorFlag();
	nimlf_(101, "/workspaces/telestorie/lib/ascii_art.nim");	queuePluginRegistration__niminiZauto95pointer_u25(register_setSeedIfNeeded__libZascii95art_u79);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

