/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_sdl3_test/@msrc@splatform@splatform_posix.nim.c.o /workspaces/telestorie/nimcache_sdl3_test/@msrc@splatform@splatform_posix.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <termios.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TerminalState__vlA7VUkqQ66QUQY9cDlM2ag tyObject_TerminalState__vlA7VUkqQ66QUQY9cDlM2ag;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef unsigned char tyArray__aOOZmqWRu0gsduEr7veiQA[32];
struct tyObject_TerminalState__vlA7VUkqQ66QUQY9cDlM2ag {
	struct termios oldTermios;
	NIM_BOOL isRawMode;
};
typedef N_NOCONV_PTR(void, tyProc__gx1DG571q2UZkCl7Jq3AOg) (int sig_p0);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u277)(FILE* f_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4643)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__ecGSLfyLpi64mCeisV5jvg_2 = { 16 | NIM_STRLIT_FLAG, "\033[\?1006h\033[\?1003h" };
static const NimStringV2 TM__ecGSLfyLpi64mCeisV5jvg_3 = {16, (NimStrPayload*)&TM__ecGSLfyLpi64mCeisV5jvg_2};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__ecGSLfyLpi64mCeisV5jvg_4 = { 16 | NIM_STRLIT_FLAG, "\033[\?1006l\033[\?1003l" };
static const NimStringV2 TM__ecGSLfyLpi64mCeisV5jvg_5 = {16, (NimStrPayload*)&TM__ecGSLfyLpi64mCeisV5jvg_4};
N_LIB_PRIVATE tyObject_TerminalState__vlA7VUkqQ66QUQY9cDlM2ag globalTerminalState__srcZplatformZplatform95posix_u6;
N_LIB_PRIVATE NIM_BOOL cleanupRegistered__srcZplatformZplatform95posix_u7 = NIM_FALSE;
N_LIB_PRIVATE tyProc__gx1DG571q2UZkCl7Jq3AOg globalUserHandler__srcZplatformZplatform95posix_u10;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4425;
extern NIM_THREADVAR TFrame* framePtr__system_u2743;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4425);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2743;
	framePtr__system_u2743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4643();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2743 = (*framePtr__system_u2743).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, enableMouseReporting__srcZplatformZplatform95posix_u66)(void) {
NIM_BOOL* nimErr_;
	nimfr_("enableMouseReporting", "/workspaces/telestorie/src/platform/platform_posix.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(91, "/workspaces/telestorie/src/platform/platform_posix.nim");	write__stdZsyncio_u254(stdout, TM__ecGSLfyLpi64mCeisV5jvg_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(92);	flushFile__stdZsyncio_u277(stdout);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, disableMouseReporting__srcZplatformZplatform95posix_u67)(void) {
NIM_BOOL* nimErr_;
	nimfr_("disableMouseReporting", "/workspaces/telestorie/src/platform/platform_posix.nim");
{nimErr_ = nimErrorFlag();
	nimln_(96);	write__stdZsyncio_u254(stdout, TM__ecGSLfyLpi64mCeisV5jvg_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(97);	flushFile__stdZsyncio_u277(stdout);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
