/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_sdl3_test/@nzippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9@szippy.nim.c.o /workspaces/telestorie/nimcache_sdl3_test/@nzippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9@szippy.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q;
typedef struct tyObject_CatchableError__RGaUZ0FR8scVeQ8Z1MyBxw tyObject_CatchableError__RGaUZ0FR8scVeQ8Z1MyBxw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__xhQiLwJj5RFCOa9c4fVuodA tySequence__xhQiLwJj5RFCOa9c4fVuodA;
typedef struct tySequence__xhQiLwJj5RFCOa9c4fVuodA_Content tySequence__xhQiLwJj5RFCOa9c4fVuodA_Content;
typedef struct tyObject_StackTraceEntry__1PUuHpJIPD3aeC4eiQfrTg tyObject_StackTraceEntry__1PUuHpJIPD3aeC4eiQfrTg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__xhQiLwJj5RFCOa9c4fVuodA {
  NI len; tySequence__xhQiLwJj5RFCOa9c4fVuodA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xhQiLwJj5RFCOa9c4fVuodA trace;
	Exception* up;
};
struct tyObject_CatchableError__RGaUZ0FR8scVeQ8Z1MyBxw {
	Exception Sup;
};
struct tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q {
	tyObject_CatchableError__RGaUZ0FR8scVeQ8Z1MyBxw Sup;
};
struct tyObject_StackTraceEntry__1PUuHpJIPD3aeC4eiQfrTg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xhQiLwJj5RFCOa9c4fVuodA_Content { NI cap; tyObject_StackTraceEntry__1PUuHpJIPD3aeC4eiQfrTg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, uncompress__pkgZzippy_u150)(void* src_p0, NI len_p1, tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w dataFormat_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, uncompressGzip__pkgZzippyZgzip_u5)(NimStringV2* dst_p0, NU8* src_p1, NI len_p2, NIM_BOOL trustSize_p3);
N_LIB_PRIVATE N_NIMCALL(void, inflate__pkgZzippyZinflate_u590)(NimStringV2* dst_p0, NU8* src_p1, NI len_p2, NI pos_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NU32, adler32__pkgZzippyZadler32_u188)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, adler32__pkgZzippyZadler32_u3)(void* src_p0, NI len_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4643)(void);
static N_INLINE(void, popFrame)(void);
extern TNimTypeV2 NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_;
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__UqbkX1qqvV1mfEv19avhonw_2 = { 39 | NIM_STRLIT_FLAG, "Unable to detect compressed data format" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_3 = {39, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_2};
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__UqbkX1qqvV1mfEv19avhonw_4 = { 36 | NIM_STRLIT_FLAG, "Invalid buffer, unable to uncompress" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_5 = {36, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_4};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__UqbkX1qqvV1mfEv19avhonw_6 = { 30 | NIM_STRLIT_FLAG, "Unsupported compression method" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_7 = {30, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_6};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__UqbkX1qqvV1mfEv19avhonw_8 = { 24 | NIM_STRLIT_FLAG, "Invalid compression info" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_9 = {24, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_8};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UqbkX1qqvV1mfEv19avhonw_10 = { 14 | NIM_STRLIT_FLAG, "Invalid header" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_11 = {14, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_10};
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__UqbkX1qqvV1mfEv19avhonw_12 = { 38 | NIM_STRLIT_FLAG, "Preset dictionary is not yet supported" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_13 = {38, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_12};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__UqbkX1qqvV1mfEv19avhonw_18 = { 28 | NIM_STRLIT_FLAG, "Checksum verification failed" };
static const NimStringV2 TM__UqbkX1qqvV1mfEv19avhonw_19 = {28, (NimStrPayload*)&TM__UqbkX1qqvV1mfEv19avhonw_18};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4425;
extern NIM_THREADVAR TFrame* framePtr__system_u2743;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4425);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2743 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2743).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2743;
	framePtr__system_u2743 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4643();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2743 = (*framePtr__system_u2743).prev;
}
static N_INLINE(NU32, adler32__pkgZzippyZadler32_u188)(NimStringV2 src_p0) {
	NU32 result;
NIM_BOOL* nimErr_;
	nimfr_("adler32", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy/adler32.nim");
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	nimlf_(66, "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy/adler32.nim");	result = adler32__pkgZzippyZadler32_u3(((void*) (nimToCStringConv(src_p0))), src_p0.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, uncompress__pkgZzippy_u150)(void* src_p0, NI len_p1, tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w dataFormat_p2) {
	NimStringV2 result;
	NU8* src_2;
NIM_BOOL* nimErr_;
	nimfr_("uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(106, "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim");	src_2 = ((NU8*) (src_p0));
	nimln_(108);	switch (dataFormat_p2) {
	case ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)0):
	{
		tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T24_;
		nimln_(110);		{
			NIM_BOOL T4_;
			NIM_BOOL T5_;
			NIM_BOOL T6_;
			NIM_BOOL T7_;
			nimln_(112);			T4_ = (NIM_BOOL)0;
			T5_ = (NIM_BOOL)0;
			T6_ = (NIM_BOOL)0;
			nimln_(111);			T7_ = (NIM_BOOL)0;
			T7_ = (((NI)18) < len_p1);
			if (!(T7_)) goto LA8_;
			nimln_(112);			T7_ = (src_2[((NI)0)] == ((NU8)31));
LA8_: ;
			T6_ = T7_;
			if (!(T6_)) goto LA9_;
			T6_ = (src_2[((NI)1)] == ((NU8)139));
LA9_: ;
			T5_ = T6_;
			if (!(T5_)) goto LA10_;
			T5_ = (src_2[((NI)2)] == ((NU8)8));
LA10_: ;
			T4_ = T5_;
			if (!(T4_)) goto LA11_;
			nimln_(113);			T4_ = ((NU8)(src_2[((NI)3)] & ((NU8)224)) == ((NU8)0));
LA11_: ;
			if (!T4_) goto LA12_;
			nimln_(115);			nimln_(100);			nimln_(115);			result = uncompress__pkgZzippy_u150(((void*) (src_2)), len_p1, ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		}
LA12_: ;
		nimln_(117);		{
			NIM_BOOL T16_;
			NIM_BOOL T17_;
			NIM_BOOL T18_;
			nimln_(120);			T16_ = (NIM_BOOL)0;
			nimln_(119);			T17_ = (NIM_BOOL)0;
			nimln_(118);			T18_ = (NIM_BOOL)0;
			T18_ = (((NI)6) < len_p1);
			if (!(T18_)) goto LA19_;
			nimln_(119);			T18_ = ((NU8)(src_2[((NI)0)] & ((NU8)15)) == ((NU8)8));
LA19_: ;
			T17_ = T18_;
			if (!(T17_)) goto LA20_;
			nimln_(120);			T17_ = ((NU8)((NU8)((NU8)(src_2[((NI)0)]) >> (NU64)(((NI)4)))) <= (NU8)(((NU8)7)));
LA20_: ;
			T16_ = T17_;
			if (!(T16_)) goto LA21_;
			nimln_(121);			T16_ = ((NU16)((NU16)((NU16)((NU16)((NU16)((NU16)(((NU16) (src_2[((NI)0)]))) * (NU16)(((NU16)256)))) + (NU16)(((NU16) (src_2[((NI)1)]))))) % (NU16)(((NU16)31))) == ((NU16)0));
LA21_: ;
			if (!T16_) goto LA22_;
			nimln_(123);			nimln_(100);			nimln_(123);			result = uncompress__pkgZzippy_u150(((void*) (src_2)), len_p1, ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		}
LA22_: ;
		T24_ = NIM_NIL;
		T24_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
		(*T24_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
		(*T24_).Sup.Sup.name = "ZippyError";
		(*T24_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_3;
		(*T24_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(125);		raiseExceptionEx((Exception*)T24_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 125);
goto BeforeRet_;
	}
	break;
	case ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)2):
	{
		nimln_(128);		uncompressGzip__pkgZzippyZgzip_u5((&result), src_2, len_p1, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)1):
	{
		NU8 cmf_1;
		NU8 flg_1;
		NU8 cm_1;
		NU8 cinfo_1;
		NU32 checksum_1;
		NI TM__UqbkX1qqvV1mfEv19avhonw_14;
		NI TM__UqbkX1qqvV1mfEv19avhonw_15;
		NI TM__UqbkX1qqvV1mfEv19avhonw_16;
		NI TM__UqbkX1qqvV1mfEv19avhonw_17;
		nimln_(131);		{
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T31_;
			if (!(len_p1 < ((NI)6))) goto LA29_;
			T31_ = NIM_NIL;
			T31_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T31_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T31_).Sup.Sup.name = "ZippyError";
			(*T31_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_5;
			(*T31_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(132);			raiseExceptionEx((Exception*)T31_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 132);
goto BeforeRet_;
		}
LA29_: ;
		nimln_(135);		cmf_1 = src_2[((NI)0)];
		nimln_(136);		flg_1 = src_2[((NI)1)];
		nimln_(137);		cm_1 = (NU8)(cmf_1 & ((NU8)15));
		nimln_(138);		cinfo_1 = (NU8)((NU8)(cmf_1) >> (NU64)(((NI)4)));
		nimln_(140);		{
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T36_;
			if (!!((cm_1 == ((NU8)8)))) goto LA34_;
			T36_ = NIM_NIL;
			T36_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T36_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T36_).Sup.Sup.name = "ZippyError";
			(*T36_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_7;
			(*T36_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(141);			raiseExceptionEx((Exception*)T36_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 141);
goto BeforeRet_;
		}
LA34_: ;
		nimln_(143);		{
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T41_;
			if (!((NU8)(((NU8)7)) < (NU8)(cinfo_1))) goto LA39_;
			T41_ = NIM_NIL;
			T41_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T41_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T41_).Sup.Sup.name = "ZippyError";
			(*T41_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_9;
			(*T41_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(144);			raiseExceptionEx((Exception*)T41_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 144);
goto BeforeRet_;
		}
LA39_: ;
		nimln_(146);		{
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T46_;
			if (!!(((NU16)((NU16)((NU16)((NU16)((NU16)((NU16)(((NU16) (cmf_1))) * (NU16)(((NU16)256)))) + (NU16)(((NU16) (flg_1))))) % (NU16)(((NU16)31))) == ((NU16)0)))) goto LA44_;
			T46_ = NIM_NIL;
			T46_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T46_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T46_).Sup.Sup.name = "ZippyError";
			(*T46_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_11;
			(*T46_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(147);			raiseExceptionEx((Exception*)T46_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 147);
goto BeforeRet_;
		}
LA44_: ;
		nimln_(149);		{
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T51_;
			if (!!(((NU8)(flg_1 & ((NU8)32)) == ((NU8)0)))) goto LA49_;
			T51_ = NIM_NIL;
			T51_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T51_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T51_).Sup.Sup.name = "ZippyError";
			(*T51_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_13;
			(*T51_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(150);			raiseExceptionEx((Exception*)T51_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 150);
goto BeforeRet_;
		}
LA49_: ;
		nimln_(152);		inflate__pkgZzippyZinflate_u590((&result), src_2, len_p1, ((NI)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(154);		nimln_(157);		nimln_(156);		nimln_(155);		if (nimSubInt(len_p1, ((NI)4), &TM__UqbkX1qqvV1mfEv19avhonw_14)) { raiseOverflow(); goto BeforeRet_;
		};
		nimln_(156);		if (nimSubInt(len_p1, ((NI)3), &TM__UqbkX1qqvV1mfEv19avhonw_15)) { raiseOverflow(); goto BeforeRet_;
		};
		nimln_(157);		if (nimSubInt(len_p1, ((NI)2), &TM__UqbkX1qqvV1mfEv19avhonw_16)) { raiseOverflow(); goto BeforeRet_;
		};
		nimln_(158);		if (nimSubInt(len_p1, ((NI)1), &TM__UqbkX1qqvV1mfEv19avhonw_17)) { raiseOverflow(); goto BeforeRet_;
		};
		checksum_1 = (NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (src_2[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_14)]))) << (NU64)(((NI)24))) | (NU32)((NU64)(((NU32) (src_2[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_15)]))) << (NU64)(((NI)16)))) | (NU32)((NU64)(((NU32) (src_2[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_16)]))) << (NU64)(((NI)8)))) | ((NU32) (src_2[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_17)])));
		nimln_(161);		{
			NU32 T54_;
			tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q* T57_;
			T54_ = (NU32)0;
			T54_ = adler32__pkgZzippyZadler32_u188(result);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!((checksum_1 == T54_))) goto LA55_;
			T57_ = NIM_NIL;
			T57_ = (tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q*) nimNewObj(sizeof(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q), NIM_ALIGNOF(tyObject_ZippyError__9bC0xXOvbp0oMd69bjdtXY5Q));
			(*T57_).Sup.Sup.Sup.m_type = (&NTIv2__9bC0xXOvbp0oMd69bjdtXY5Q_);
			(*T57_).Sup.Sup.name = "ZippyError";
			(*T57_).Sup.Sup.message = TM__UqbkX1qqvV1mfEv19avhonw_19;
			(*T57_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(162);			raiseExceptionEx((Exception*)T57_, "ZippyError", "uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim", 162);
goto BeforeRet_;
		}
LA55_: ;
	}
	break;
	case ((tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w)3):
	{
		nimln_(165);		inflate__pkgZzippyZinflate_u590((&result), src_2, len_p1, ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, uncompress__pkgZzippy_u188)(NimStringV2 src_p0, tyEnum_CompressedDataFormat__2Ixl9bhsdLtE9a2H8R8Ito7w dataFormat_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("uncompress", "/home/codespace/.nimble/pkgs2/zippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9/zippy.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(171);	result = uncompress__pkgZzippy_u150(((void*) (nimToCStringConv(src_p0))), src_p0.len, dataFormat_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
