/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -I/workspaces/storie-vendor/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_sdl3/@nzippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9@szippy@sadler32.nim.c.o /workspaces/telestorie/nimcache_wasm_sdl3/@nzippy-0.10.18-634e8ce02fb5a9bbb3cf4f9853b7150ea21e35a9@szippy@sadler32.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NU32, adler32__pkgZzippyZadler32_u3)(void* src_p0, NI len_p1) {
	NU32 result;
	NU8* src_2;
	NU32 s1_1;
	NU32 s2_1;
	NI l_1;
	NI pos_1;
{	result = (NU32)0;
	src_2 = ((NU8*) (src_p0));
	s1_1 = ((NU32)1);
	s2_1 = ((NU32)0);
	l_1 = len_p1;
	pos_1 = (NI)0;
	{
		while (1) {
			NI TM__39bX9b3IJyQsU8InDO8fInmw_2;
			if (!(((NI)5552) <= l_1)) goto LA2;
			if (nimSubInt(l_1, ((NI)5552), &TM__39bX9b3IJyQsU8InDO8fInmw_2)) { raiseOverflow(); goto BeforeRet_;
			};
			l_1 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_2);
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				i_2 = ((NI)0);
				{
					while (1) {
						NI TM__39bX9b3IJyQsU8InDO8fInmw_3;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_4;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_5;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_6;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_7;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_8;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_9;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_10;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_11;
						NI TM__39bX9b3IJyQsU8InDO8fInmw_12;
						if (!(i_2 < ((NI)694))) goto LA5;
						i_1 = i_2;
						if (nimAddInt(pos_1, ((NI)0), &TM__39bX9b3IJyQsU8InDO8fInmw_3)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_3)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)1), &TM__39bX9b3IJyQsU8InDO8fInmw_4)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_4)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)2), &TM__39bX9b3IJyQsU8InDO8fInmw_5)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_5)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)3), &TM__39bX9b3IJyQsU8InDO8fInmw_6)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_6)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)4), &TM__39bX9b3IJyQsU8InDO8fInmw_7)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_7)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)5), &TM__39bX9b3IJyQsU8InDO8fInmw_8)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_8)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)6), &TM__39bX9b3IJyQsU8InDO8fInmw_9)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_9)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)7), &TM__39bX9b3IJyQsU8InDO8fInmw_10)) { raiseOverflow(); goto BeforeRet_;
						};
						s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_10)]));
						s2_1 += s1_1;
						if (nimAddInt(pos_1, ((NI)8), &TM__39bX9b3IJyQsU8InDO8fInmw_11)) { raiseOverflow(); goto BeforeRet_;
						};
						pos_1 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_11);
						if (nimAddInt(i_2, ((NI)1), &TM__39bX9b3IJyQsU8InDO8fInmw_12)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_12);
					} LA5: ;
				}
			}
			s1_1 = (NU32)((NU32)(s1_1) % (NU32)(((NU32)65521)));
			s2_1 = (NU32)((NU32)(s2_1) % (NU32)(((NU32)65521)));
		} LA2: ;
	}
	{
		while (1) {
			NI TM__39bX9b3IJyQsU8InDO8fInmw_13;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_14;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_15;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_16;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_17;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_18;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_19;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_20;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_21;
			NI TM__39bX9b3IJyQsU8InDO8fInmw_22;
			if (!(((NI)8) <= l_1)) goto LA7;
			if (nimSubInt(l_1, ((NI)8), &TM__39bX9b3IJyQsU8InDO8fInmw_13)) { raiseOverflow(); goto BeforeRet_;
			};
			l_1 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_13);
			if (nimAddInt(pos_1, ((NI)0), &TM__39bX9b3IJyQsU8InDO8fInmw_14)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_14)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)1), &TM__39bX9b3IJyQsU8InDO8fInmw_15)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_15)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)2), &TM__39bX9b3IJyQsU8InDO8fInmw_16)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_16)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)3), &TM__39bX9b3IJyQsU8InDO8fInmw_17)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_17)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)4), &TM__39bX9b3IJyQsU8InDO8fInmw_18)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_18)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)5), &TM__39bX9b3IJyQsU8InDO8fInmw_19)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_19)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)6), &TM__39bX9b3IJyQsU8InDO8fInmw_20)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_20)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)7), &TM__39bX9b3IJyQsU8InDO8fInmw_21)) { raiseOverflow(); goto BeforeRet_;
			};
			s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_21)]));
			s2_1 += s1_1;
			if (nimAddInt(pos_1, ((NI)8), &TM__39bX9b3IJyQsU8InDO8fInmw_22)) { raiseOverflow(); goto BeforeRet_;
			};
			pos_1 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_22);
		} LA7: ;
	}
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		i_4 = ((NI)0);
		{
			while (1) {
				NI TM__39bX9b3IJyQsU8InDO8fInmw_23;
				NI TM__39bX9b3IJyQsU8InDO8fInmw_24;
				if (!(i_4 < l_1)) goto LA10;
				i_3 = i_4;
				if (nimAddInt(pos_1, i_3, &TM__39bX9b3IJyQsU8InDO8fInmw_23)) { raiseOverflow(); goto BeforeRet_;
				};
				s1_1 += ((NU32) (src_2[(NI)(TM__39bX9b3IJyQsU8InDO8fInmw_23)]));
				s2_1 += s1_1;
				if (nimAddInt(i_4, ((NI)1), &TM__39bX9b3IJyQsU8InDO8fInmw_24)) { raiseOverflow(); goto BeforeRet_;
				};
				i_4 = (NI)(TM__39bX9b3IJyQsU8InDO8fInmw_24);
			} LA10: ;
		}
	}
	s1_1 = (NU32)((NU32)(s1_1) % (NU32)(((NU32)65521)));
	s2_1 = (NU32)((NU32)(s2_1) % (NU32)(((NU32)65521)));
	result = (NU32)((NU32)((NU32)(s2_1) << (NU32)(((NI)16))) | s1_1);
	}BeforeRet_: ;
	return result;
}
