/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -I/workspaces/storie-vendor/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@stype_converters.nim.c.o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@stype_converters.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA tySequence__Gf9avO3sd1YsdKIYcdAbNvA;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg;
typedef struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A tyObject_Table__Kkv168EwyeC2mcswHBvZ1A;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ tySequence__2nVARL7psn6awrm07aftcQ;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ_Content tySequence__2nVARL7psn6awrm07aftcQ_Content;
typedef struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA;
typedef struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ tyObject_Style__UURjArTrf2wmcCbN5MncAQ;
typedef struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ;
typedef struct tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA tyTuple__9bJQUgvR2blr9cUNMhbZPKyA;
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA {
  NI len; tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ;
struct tySequence__2nVARL7psn6awrm07aftcQ {
  NI len; tySequence__2nVARL7psn6awrm07aftcQ_Content* p;
};
struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A {
	tySequence__2nVARL7psn6awrm07aftcQ data;
	NI counter;
};
struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA {
	NU64 a0;
	NU64 a1;
};
struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A {
	tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ kind;
	NI i;
	NF f;
	NIM_BOOL b;
	NimStringV2 s;
	tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg* fnVal;
	tyObject_Table__Kkv168EwyeC2mcswHBvZ1A map;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr;
	void* ptrVal;
	tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA randState;
};
struct tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ {
	NU8 r;
	NU8 g;
	NU8 b;
};
struct tyObject_Style__UURjArTrf2wmcCbN5MncAQ {
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ fg;
	tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ bg;
	NIM_BOOL bold;
	NIM_BOOL underline;
	NIM_BOOL italic;
	NIM_BOOL dim;
};
struct tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA {
	NI a;
	NI b;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content { NI cap; tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* data[SEQ_DECL_SIZE]; };
struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* Field2;
};
struct tySequence__2nVARL7psn6awrm07aftcQ_Content { NI cap; tyTuple__9bJQUgvR2blr9cUNMhbZPKyA data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__niminiZruntime_u3494)(tySequence__Gf9avO3sd1YsdKIYcdAbNvA* x_p0, tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valString__niminiZruntime_u1095)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niminiZruntime_u92)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valArray__niminiZruntime_u1255)(tySequence__Gf9avO3sd1YsdKIYcdAbNvA elements_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niminiZruntime_u477)(tySequence__Gf9avO3sd1YsdKIYcdAbNvA dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A, initTable__niminiZruntime_u1225)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___niminiZruntime_u1726)(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A* t_p0, NimStringV2 key_p1, tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* val_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valInt__niminiZruntime_u1086)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valMap__niminiZruntime_u1210)(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A initialMap_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niminiZruntime_u1010)(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__niminiZruntime_u1333)(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___niminiZruntime_u95)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** dest_p0, tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**, X5BX5D___niminiZruntime_u1596)(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2642)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseHexInt)(NimStringV2 s_p0);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1292)(NimStringV2 s_p0, tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA x_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2391)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, valueToInt__niminiZtype95converters_u5)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, valueToBool__niminiZtype95converters_u18)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, tupleXYToValue__niminiZtype95converters_u2679)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ t_p0);
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_2 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_3 = {90, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_4 = { 5 | NIM_STRLIT_FLAG, "width" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_5 = {5, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_6 = { 6 | NIM_STRLIT_FLAG, "height" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_7 = {6, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_8 = { 2 | NIM_STRLIT_FLAG, "fg" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_9 = {2, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_8};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_10 = {2, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_15 = { 1 | NIM_STRLIT_FLAG, "r" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_16 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_15};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_17 = { 1 | NIM_STRLIT_FLAG, "g" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_18 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_17};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_19 = { 1 | NIM_STRLIT_FLAG, "b" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_20 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_19};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_21 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_15};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_22 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_17};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_23 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_19};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_24 = { 2 | NIM_STRLIT_FLAG, "bg" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_25 = {2, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_24};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_26 = {2, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_24};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_27 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_15};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_28 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_17};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_29 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_19};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_30 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_15};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_31 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_17};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_32 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_19};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_33 = { 4 | NIM_STRLIT_FLAG, "bold" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_34 = {4, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_33};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_35 = {4, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_33};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_36 = { 6 | NIM_STRLIT_FLAG, "italic" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_37 = {6, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_36};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_38 = {6, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_36};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_39 = { 9 | NIM_STRLIT_FLAG, "underline" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_40 = {9, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_39};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_41 = {9, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_39};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_42 = { 3 | NIM_STRLIT_FLAG, "dim" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_43 = {3, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_42};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_44 = {3, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_42};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_45 = {90, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_46 = { 1 | NIM_STRLIT_FLAG, "x" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_47 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_46};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__IFF4kERC3UXmKH9aTAraJ8Q_48 = { 1 | NIM_STRLIT_FLAG, "y" };
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_49 = {1, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_48};
static const NimStringV2 TM__IFF4kERC3UXmKH9aTAraJ8Q_50 = {90, (NimStrPayload*)&TM__IFF4kERC3UXmKH9aTAraJ8Q_2};
extern NIM_BOOL nimInErrorMode__system_u4234;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___niminiZtype95converters_u3045)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
}
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, seqStringToValue__niminiZtype95converters_u2452)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ s_p0) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	arr_1.len = 0; arr_1.p = NIM_NIL;
	arr_1.len = 0; arr_1.p = (tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content*) newSeqPayload(0, sizeof(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*), NIM_ALIGNOF(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*));
	{
		NimStringV2* item_1;
		NI i_1;
		NI L_1;
		NI T3_;
		item_1 = (NimStringV2*)0;
		i_1 = ((NI)0);
		T3_ = s_p0.len;
		L_1 = T3_;
		{
			while (1) {
				tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T6_;
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto LA1_;
				}
				item_1 = (&s_p0.p->data[i_1]);
				T6_ = NIM_NIL;
				T6_ = valString__niminiZruntime_u1095((*item_1));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T6_); goto LA1_;}
				add__niminiZruntime_u3494((&arr_1), T6_);
				i_1 += ((NI)1);
				{
					NI T9_;
					T9_ = s_p0.len;
					if (!!((T9_ == L_1))) goto LA10_;
					failedAssertImpl__stdZassertions_u234(TM__IFF4kERC3UXmKH9aTAraJ8Q_3);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA10_: ;
			} LA5: ;
		}
	}
	result = valArray__niminiZruntime_u1255(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___niminiZruntime_u477(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___niminiZruntime_u477(arr_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, tupleWidthHeightToValue__niminiZtype95converters_u3201)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ t_p0) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	tyObject_Table__Kkv168EwyeC2mcswHBvZ1A m_1;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T2_;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&m_1), sizeof(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A));
	m_1 = initTable__niminiZruntime_u1225(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = NIM_NIL;
	T2_ = valInt__niminiZruntime_u1086(t_p0.Field0);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T2_); goto LA1_;}
	X5BX5Deq___niminiZruntime_u1726((&m_1), TM__IFF4kERC3UXmKH9aTAraJ8Q_5, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = NIM_NIL;
	T3_ = valInt__niminiZruntime_u1086(t_p0.Field1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T3_); goto LA1_;}
	X5BX5Deq___niminiZruntime_u1726((&m_1), TM__IFF4kERC3UXmKH9aTAraJ8Q_7, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = valMap__niminiZruntime_u1210(m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___niminiZruntime_u1010((&m_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___niminiZruntime_u1010((&m_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2391(s_p0);
	}
LA5_: ;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1292)(NimStringV2 s_p0, tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	NI TM__IFF4kERC3UXmKH9aTAraJ8Q_11;
	NI TM__IFF4kERC3UXmKH9aTAraJ8Q_12;
{	result.len = 0; result.p = NIM_NIL;
	a_1 = x_p1.a;
	if (nimSubInt(x_p1.b, a_1, &TM__IFF4kERC3UXmKH9aTAraJ8Q_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_11), ((NI)1), &TM__IFF4kERC3UXmKH9aTAraJ8Q_12)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_12);
	if ((L_1) < ((NI)0) || (L_1) > ((NI)2147483647)){ raiseRangeErrorI(L_1, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
	}
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__IFF4kERC3UXmKH9aTAraJ8Q_13;
				NI TM__IFF4kERC3UXmKH9aTAraJ8Q_14;
				if (!(i_2 < L_1)) goto LA3;
				i_1 = i_2;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (nimAddInt(i_1, a_1, &TM__IFF4kERC3UXmKH9aTAraJ8Q_13)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_13) < 0 || (NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_13) >= s_p0.len){ raiseIndexError2((NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_13),s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[(NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_13)];
				if (nimAddInt(i_2, ((NI)1), &TM__IFF4kERC3UXmKH9aTAraJ8Q_14)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__IFF4kERC3UXmKH9aTAraJ8Q_14);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, valueToInt__niminiZtype95converters_u5)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0) {
	NI result;
{	result = (NI)0;
	switch ((*v_p0).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		result = (*v_p0).i;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)2):
	{
		if ((((NI) (((NI64) ((*v_p0).f))))) < ((NI)(-2147483647 -1)) || (((NI) (((NI64) ((*v_p0).f))))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (((NI64) ((*v_p0).f)))), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto BeforeRet_;
		}
		result = (((NI) (((NI64) ((*v_p0).f)))));
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = ((NI)0);
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, valueToBool__niminiZtype95converters_u18)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0) {
	NIM_BOOL result;
{	switch ((*v_p0).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)3):
	{
		result = (*v_p0).b;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		result = !(((*v_p0).i == ((NI)0)));
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Style__UURjArTrf2wmcCbN5MncAQ, valueToStyle__niminiZtype95converters_u21)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0) {
	tyObject_Style__UURjArTrf2wmcCbN5MncAQ result;
NIM_BOOL oldNimErrFin10_;
NIM_BOOL oldNimErrFin57_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Style__UURjArTrf2wmcCbN5MncAQ));
	{
		tyObject_Style__UURjArTrf2wmcCbN5MncAQ style_1;
		if (!((*v_p0).kind == ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)6))) goto LA3_;
		nimZeroMem((void*)(&style_1), sizeof(tyObject_Style__UURjArTrf2wmcCbN5MncAQ));
		{
			NIM_BOOL T7_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* fgVal_1;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T11_;
			T7_ = (NIM_BOOL)0;
			T7_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_9);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T7_) goto LA8_;
			fgVal_1 = NIM_NIL;
			T11_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T11_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_10);
			if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			eqcopy___niminiZruntime_u95(&fgVal_1, (*T11_), NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			{
				NimStringV2 hexStr_1;
				if (!((*fgVal_1).kind == ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)4))) goto LA14_;
				hexStr_1.len = 0; hexStr_1.p = NIM_NIL;
				eqcopy___system_u2642((&hexStr_1), (*fgVal_1).s);
				{
					NIM_BOOL T19_;
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 colontmpD__3;
					NU8 colontmpD__4;
					NU8 colontmpD__5;
					NU8 colontmpD__6;
					NI r_1;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T24_;
					NI g_1;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T25_;
					NI b_1;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T26_;
					tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ T27_;
					T19_ = (NIM_BOOL)0;
					T19_ = (((NI)7) <= hexStr_1.len);
					if (!(T19_)) goto LA20_;
					if (((NI)0) < 0 || ((NI)0) >= hexStr_1.len){ raiseIndexError2(((NI)0),hexStr_1.len-1); goto LA16_;
					}
					T19_ = ((NU8)(hexStr_1.p->data[((NI)0)]) == (NU8)(35));
LA20_: ;
					if (!T19_) goto LA21_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					colontmpD__4 = (NU8)0;
					colontmpD__5 = (NU8)0;
					colontmpD__6 = (NU8)0;
					T24_ = dotdot___stdZstrbasics_u48(((NI)1), ((NI)2));
					colontmpD_ = X5BX5D___pureZstrutils_u1292(hexStr_1, T24_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					r_1 = nsuParseHexInt(colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					T25_ = dotdot___stdZstrbasics_u48(((NI)3), ((NI)4));
					colontmpD__2 = X5BX5D___pureZstrutils_u1292(hexStr_1, T25_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					g_1 = nsuParseHexInt(colontmpD__2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					T26_ = dotdot___stdZstrbasics_u48(((NI)5), ((NI)6));
					colontmpD__3 = X5BX5D___pureZstrutils_u1292(hexStr_1, T26_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					b_1 = nsuParseHexInt(colontmpD__3);
					if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
					colontmpD__4 = ((NU8) (r_1));
					T27_.r = colontmpD__4;
					colontmpD__5 = ((NU8) (g_1));
					T27_.g = colontmpD__5;
					colontmpD__6 = ((NU8) (b_1));
					T27_.b = colontmpD__6;
					style_1.fg = T27_;
					{
						LA23_:;
					}
					{
						if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
						if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				}
LA21_: ;
				{
					LA16_:;
				}
				{
					if (hexStr_1.p && !(hexStr_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(hexStr_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			}
			goto LA12_;
LA14_: ;
			{
				if (!((*fgVal_1).kind == ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)6))) goto LA33_;
				{
					NIM_BOOL T37_;
					NIM_BOOL T38_;
					NU8 colontmpD__7;
					NU8 colontmpD__8;
					NU8 colontmpD__9;
					tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ T43_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T44_;
					NI T45_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T46_;
					NI T47_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T48_;
					NI T49_;
					T37_ = (NIM_BOOL)0;
					T38_ = (NIM_BOOL)0;
					T38_ = hasKey__niminiZruntime_u1333((*fgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_16);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					if (!(T38_)) goto LA39_;
					T38_ = hasKey__niminiZruntime_u1333((*fgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_18);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
LA39_: ;
					T37_ = T38_;
					if (!(T37_)) goto LA40_;
					T37_ = hasKey__niminiZruntime_u1333((*fgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_20);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
LA40_: ;
					if (!T37_) goto LA41_;
					colontmpD__7 = (NU8)0;
					colontmpD__8 = (NU8)0;
					colontmpD__9 = (NU8)0;
					T44_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T44_ = X5BX5D___niminiZruntime_u1596((&(*fgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_21);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					T45_ = (NI)0;
					T45_ = valueToInt__niminiZtype95converters_u5((*T44_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					colontmpD__7 = ((NU8) (T45_));
					T43_.r = colontmpD__7;
					T46_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T46_ = X5BX5D___niminiZruntime_u1596((&(*fgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_22);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					T47_ = (NI)0;
					T47_ = valueToInt__niminiZtype95converters_u5((*T46_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					colontmpD__8 = ((NU8) (T47_));
					T43_.g = colontmpD__8;
					T48_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T48_ = X5BX5D___niminiZruntime_u1596((&(*fgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_23);
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					T49_ = (NI)0;
					T49_ = valueToInt__niminiZtype95converters_u5((*T48_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
					colontmpD__9 = ((NU8) (T49_));
					T43_.b = colontmpD__9;
					style_1.fg = T43_;
				}
LA41_: ;
			}
			goto LA12_;
LA33_: ;
LA12_: ;
			{
				LA10_:;
			}
			{
				oldNimErrFin10_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___niminiZruntime_u92(fgVal_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin10_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA8_: ;
		{
			NIM_BOOL T54_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* bgVal_1;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T58_;
			T54_ = (NIM_BOOL)0;
			T54_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_25);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T54_) goto LA55_;
			bgVal_1 = NIM_NIL;
			T58_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T58_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_26);
			if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
			eqcopy___niminiZruntime_u95(&bgVal_1, (*T58_), NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
			{
				NimStringV2 hexStr_2;
				if (!((*bgVal_1).kind == ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)4))) goto LA61_;
				hexStr_2.len = 0; hexStr_2.p = NIM_NIL;
				eqcopy___system_u2642((&hexStr_2), (*bgVal_1).s);
				{
					NIM_BOOL T66_;
					NimStringV2 colontmpD__10;
					NimStringV2 colontmpD__11;
					NimStringV2 colontmpD__12;
					NU8 colontmpD__13;
					NU8 colontmpD__14;
					NU8 colontmpD__15;
					NI r_2;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T71_;
					NI g_2;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T72_;
					NI b_2;
					tyObject_HSlice__lHgNVhT9csv0Ntz6xvKK2dA T73_;
					tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ T74_;
					T66_ = (NIM_BOOL)0;
					T66_ = (((NI)7) <= hexStr_2.len);
					if (!(T66_)) goto LA67_;
					if (((NI)0) < 0 || ((NI)0) >= hexStr_2.len){ raiseIndexError2(((NI)0),hexStr_2.len-1); goto LA63_;
					}
					T66_ = ((NU8)(hexStr_2.p->data[((NI)0)]) == (NU8)(35));
LA67_: ;
					if (!T66_) goto LA68_;
					colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
					colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
					colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
					colontmpD__13 = (NU8)0;
					colontmpD__14 = (NU8)0;
					colontmpD__15 = (NU8)0;
					T71_ = dotdot___stdZstrbasics_u48(((NI)1), ((NI)2));
					colontmpD__10 = X5BX5D___pureZstrutils_u1292(hexStr_2, T71_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					r_2 = nsuParseHexInt(colontmpD__10);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					T72_ = dotdot___stdZstrbasics_u48(((NI)3), ((NI)4));
					colontmpD__11 = X5BX5D___pureZstrutils_u1292(hexStr_2, T72_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					g_2 = nsuParseHexInt(colontmpD__11);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					T73_ = dotdot___stdZstrbasics_u48(((NI)5), ((NI)6));
					colontmpD__12 = X5BX5D___pureZstrutils_u1292(hexStr_2, T73_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					b_2 = nsuParseHexInt(colontmpD__12);
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					colontmpD__13 = ((NU8) (r_2));
					T74_.r = colontmpD__13;
					colontmpD__14 = ((NU8) (g_2));
					T74_.g = colontmpD__14;
					colontmpD__15 = ((NU8) (b_2));
					T74_.b = colontmpD__15;
					style_1.bg = T74_;
					{
						LA70_:;
					}
					{
						if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__12.p);
}
						if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__11.p);
}
						if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__10.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
				}
LA68_: ;
				{
					LA63_:;
				}
				{
					if (hexStr_2.p && !(hexStr_2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(hexStr_2.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
			}
			goto LA59_;
LA61_: ;
			{
				if (!((*bgVal_1).kind == ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)6))) goto LA80_;
				{
					NIM_BOOL T84_;
					NIM_BOOL T85_;
					NU8 colontmpD__16;
					NU8 colontmpD__17;
					NU8 colontmpD__18;
					tyObject_Color__TZLGUfQjHRBnaB3m3yIxqQ T90_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T91_;
					NI T92_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T93_;
					NI T94_;
					tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T95_;
					NI T96_;
					T84_ = (NIM_BOOL)0;
					T85_ = (NIM_BOOL)0;
					T85_ = hasKey__niminiZruntime_u1333((*bgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_27);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					if (!(T85_)) goto LA86_;
					T85_ = hasKey__niminiZruntime_u1333((*bgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_28);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
LA86_: ;
					T84_ = T85_;
					if (!(T84_)) goto LA87_;
					T84_ = hasKey__niminiZruntime_u1333((*bgVal_1).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_29);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
LA87_: ;
					if (!T84_) goto LA88_;
					colontmpD__16 = (NU8)0;
					colontmpD__17 = (NU8)0;
					colontmpD__18 = (NU8)0;
					T91_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T91_ = X5BX5D___niminiZruntime_u1596((&(*bgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_30);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					T92_ = (NI)0;
					T92_ = valueToInt__niminiZtype95converters_u5((*T91_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					colontmpD__16 = ((NU8) (T92_));
					T90_.r = colontmpD__16;
					T93_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T93_ = X5BX5D___niminiZruntime_u1596((&(*bgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_31);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					T94_ = (NI)0;
					T94_ = valueToInt__niminiZtype95converters_u5((*T93_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					colontmpD__17 = ((NU8) (T94_));
					T90_.g = colontmpD__17;
					T95_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
					T95_ = X5BX5D___niminiZruntime_u1596((&(*bgVal_1).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_32);
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					T96_ = (NI)0;
					T96_ = valueToInt__niminiZtype95converters_u5((*T95_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA57_;
					colontmpD__18 = ((NU8) (T96_));
					T90_.b = colontmpD__18;
					style_1.bg = T90_;
				}
LA88_: ;
			}
			goto LA59_;
LA80_: ;
LA59_: ;
			{
				LA57_:;
			}
			{
				oldNimErrFin57_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___niminiZruntime_u92(bgVal_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin57_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA55_: ;
		{
			NIM_BOOL T101_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T104_;
			NIM_BOOL T105_;
			T101_ = (NIM_BOOL)0;
			T101_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_34);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T101_) goto LA102_;
			T104_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T104_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_35);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T105_ = (NIM_BOOL)0;
			T105_ = valueToBool__niminiZtype95converters_u18((*T104_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			style_1.bold = T105_;
		}
LA102_: ;
		{
			NIM_BOOL T108_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T111_;
			NIM_BOOL T112_;
			T108_ = (NIM_BOOL)0;
			T108_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_37);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T108_) goto LA109_;
			T111_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T111_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_38);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T112_ = (NIM_BOOL)0;
			T112_ = valueToBool__niminiZtype95converters_u18((*T111_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			style_1.italic = T112_;
		}
LA109_: ;
		{
			NIM_BOOL T115_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T118_;
			NIM_BOOL T119_;
			T115_ = (NIM_BOOL)0;
			T115_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_40);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T115_) goto LA116_;
			T118_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T118_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_41);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T119_ = (NIM_BOOL)0;
			T119_ = valueToBool__niminiZtype95converters_u18((*T118_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			style_1.underline = T119_;
		}
LA116_: ;
		{
			NIM_BOOL T122_;
			tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** T125_;
			NIM_BOOL T126_;
			T122_ = (NIM_BOOL)0;
			T122_ = hasKey__niminiZruntime_u1333((*v_p0).map, TM__IFF4kERC3UXmKH9aTAraJ8Q_43);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T122_) goto LA123_;
			T125_ = (tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A**)0;
			T125_ = X5BX5D___niminiZruntime_u1596((&(*v_p0).map), TM__IFF4kERC3UXmKH9aTAraJ8Q_44);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T126_ = (NIM_BOOL)0;
			T126_ = valueToBool__niminiZtype95converters_u18((*T125_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			style_1.dim = T126_;
		}
LA123_: ;
		result = style_1;
		goto BeforeRet_;
	}
LA3_: ;
	result.fg.r = ((NU8)255);
	result.fg.g = ((NU8)255);
	result.fg.b = ((NU8)255);
	result.bg.r = ((NU8)0);
	result.bg.g = ((NU8)0);
	result.bg.b = ((NU8)0);
	result.bold = NIM_FALSE;
	result.italic = NIM_FALSE;
	result.underline = NIM_FALSE;
	result.dim = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, seqIntToValue__niminiZtype95converters_u2399)(tySequence__qwqHTkRvwhrRyENtudHQ7g s_p0) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	arr_1.len = 0; arr_1.p = NIM_NIL;
	arr_1.len = 0; arr_1.p = (tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content*) newSeqPayload(0, sizeof(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*), NIM_ALIGNOF(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*));
	{
		NI* item_1;
		NI i_1;
		NI L_1;
		NI T3_;
		item_1 = (NI*)0;
		i_1 = ((NI)0);
		T3_ = s_p0.len;
		L_1 = T3_;
		{
			while (1) {
				tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T6_;
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto LA1_;
				}
				item_1 = (&s_p0.p->data[i_1]);
				T6_ = NIM_NIL;
				T6_ = valInt__niminiZruntime_u1086((*item_1));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T6_); goto LA1_;}
				add__niminiZruntime_u3494((&arr_1), T6_);
				i_1 += ((NI)1);
				{
					NI T9_;
					T9_ = s_p0.len;
					if (!!((T9_ == L_1))) goto LA10_;
					failedAssertImpl__stdZassertions_u234(TM__IFF4kERC3UXmKH9aTAraJ8Q_45);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA10_: ;
			} LA5: ;
		}
	}
	result = valArray__niminiZruntime_u1255(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___niminiZruntime_u477(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___niminiZruntime_u477(arr_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, tupleXYToValue__niminiZtype95converters_u2679)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ t_p0) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	tyObject_Table__Kkv168EwyeC2mcswHBvZ1A m_1;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T2_;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&m_1), sizeof(tyObject_Table__Kkv168EwyeC2mcswHBvZ1A));
	m_1 = initTable__niminiZruntime_u1225(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = NIM_NIL;
	T2_ = valInt__niminiZruntime_u1086(t_p0.Field0);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T2_); goto LA1_;}
	X5BX5Deq___niminiZruntime_u1726((&m_1), TM__IFF4kERC3UXmKH9aTAraJ8Q_47, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = NIM_NIL;
	T3_ = valInt__niminiZruntime_u1086(t_p0.Field1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T3_); goto LA1_;}
	X5BX5Deq___niminiZruntime_u1726((&m_1), TM__IFF4kERC3UXmKH9aTAraJ8Q_49, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = valMap__niminiZruntime_u1210(m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___niminiZruntime_u1010((&m_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___niminiZruntime_u1010((&m_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, seqTupleXYToValue__niminiZtype95converters_u2986)(tySequence__8Np6tlClE5az1CyqZdN19bQ s_p0) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	arr_1.len = 0; arr_1.p = NIM_NIL;
	arr_1.len = 0; arr_1.p = (tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content*) newSeqPayload(0, sizeof(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*), NIM_ALIGNOF(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*));
	{
		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ* item_1;
		NI i_1;
		NI L_1;
		NI T3_;
		item_1 = (tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ*)0;
		i_1 = ((NI)0);
		T3_ = s_p0.len;
		L_1 = T3_;
		{
			while (1) {
				tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* T6_;
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto LA1_;
				}
				item_1 = (&s_p0.p->data[i_1]);
				T6_ = NIM_NIL;
				T6_ = tupleXYToValue__niminiZtype95converters_u2679((*item_1));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___niminiZruntime_u92(T6_); goto LA1_;}
				add__niminiZruntime_u3494((&arr_1), T6_);
				i_1 += ((NI)1);
				{
					NI T9_;
					T9_ = s_p0.len;
					if (!!((T9_ == L_1))) goto LA10_;
					failedAssertImpl__stdZassertions_u234(TM__IFF4kERC3UXmKH9aTAraJ8Q_50);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA10_: ;
			} LA5: ;
		}
	}
	result = valArray__niminiZruntime_u1255(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___niminiZruntime_u477(arr_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___niminiZruntime_u477(arr_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___niminiZtype95converters_u3042)(tySequence__8Np6tlClE5az1CyqZdN19bQ* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
