/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -I/workspaces/storie-vendor/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@sbackends@spython_backend.nim.c.o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@sbackends@spython_backend.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__4Aje6Q7a019cMMvArOJ2Tzg tySequence__4Aje6Q7a019cMMvArOJ2Tzg;
typedef struct tySequence__4Aje6Q7a019cMMvArOJ2Tzg_Content tySequence__4Aje6Q7a019cMMvArOJ2Tzg_Content;
typedef struct tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ;
typedef struct tySequence__jwzrUFjG9akTIJTBBFvvqxw tySequence__jwzrUFjG9akTIJTBBFvvqxw;
typedef struct tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__4Aje6Q7a019cMMvArOJ2Tzg {
  NI len; tySequence__4Aje6Q7a019cMMvArOJ2Tzg_Content* p;
};
struct tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ {
	NimStringV2 name;
	NimStringV2 paramType;
	NIM_BOOL isVar;
};
struct tySequence__jwzrUFjG9akTIJTBBFvvqxw {
  NI len; tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content* p;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__4Aje6Q7a019cMMvArOJ2Tzg_Content { NI cap; tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ data[SEQ_DECL_SIZE]; };
struct tySequence__jwzrUFjG9akTIJTBBFvvqxw_Content { NI cap; tyTuple__XOVT24GHXwqiEj5GCsEGCA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateInt__niminiZbackendsZpython95backend_u62)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateFloat__niminiZbackendsZpython95backend_u66)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NF value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4717)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateString__niminiZbackendsZpython95backend_u73)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBool__niminiZbackendsZpython95backend_u78)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NIM_BOOL value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIdent__niminiZbackendsZpython95backend_u82)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2642)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBinOp__niminiZbackendsZpython95backend_u86)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 left_p1, NimStringV2 op_p2, NimStringV2 right_p3);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateUnaryOp__niminiZbackendsZpython95backend_u93)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 op_p1, NimStringV2 operand_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateCall__niminiZbackendsZpython95backend_u98)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 funcName_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ args_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateArray__niminiZbackendsZpython95backend_u103)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ elements_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIndex__niminiZbackendsZpython95backend_u107)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 target_p1, NimStringV2 index_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateVarDecl__niminiZbackendsZpython95backend_u112)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateLetDecl__niminiZbackendsZpython95backend_u118)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateAssignment__niminiZbackendsZpython95backend_u124)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 target_p1, NimStringV2 value_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIfStmt__niminiZbackendsZpython95backend_u130)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElifStmt__niminiZbackendsZpython95backend_u135)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElseStmt__niminiZbackendsZpython95backend_u140)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 indent_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateForLoop__niminiZbackendsZpython95backend_u144)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 varName_p1, NimStringV2 iterable_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateWhileLoop__niminiZbackendsZpython95backend_u150)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBreak__niminiZbackendsZpython95backend_u155)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 label_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateContinue__niminiZbackendsZpython95backend_u160)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 label_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProcDecl__niminiZbackendsZpython95backend_u165)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, tySequence__4Aje6Q7a019cMMvArOJ2Tzg params_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2645)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3717)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateReturn__niminiZbackendsZpython95backend_u189)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 value_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateImport__niminiZbackendsZpython95backend_u194)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 module_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateComment__niminiZbackendsZpython95backend_u198)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 text_p1, NimStringV2 indent_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateEnumType__niminiZbackendsZpython95backend_u203)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, tySequence__jwzrUFjG9akTIJTBBFvvqxw values_p2, NimStringV2 indent_p3);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramHeader__niminiZbackendsZpython95backend_u255)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramFooter__niminiZbackendsZpython95backend_u258)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_2 = { 1 | NIM_STRLIT_FLAG, "\\" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_3 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_4 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_5 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_6 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_7 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_8 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_9 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_10 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_11 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_10};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_12 = { 2 | NIM_STRLIT_FLAG, "\\n" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_13 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_14 = { 1 | NIM_STRLIT_FLAG, "\015" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_15 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_14};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_16 = { 2 | NIM_STRLIT_FLAG, "\\r" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_17 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_16};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_18 = { 1 | NIM_STRLIT_FLAG, "\011" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_19 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_18};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_20 = { 2 | NIM_STRLIT_FLAG, "\\t" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_21 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_20};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_22 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_6};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_24 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_25 = { 4 | NIM_STRLIT_FLAG, "True" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_26 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_25};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_27 = { 5 | NIM_STRLIT_FLAG, "False" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_28 = {5, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_27};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_29 = { 3 | NIM_STRLIT_FLAG, "and" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_30 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_29};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_31 = { 2 | NIM_STRLIT_FLAG, "or" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_32 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_31};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_33 = { 1 | NIM_STRLIT_FLAG, "%" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_34 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_33};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_35 = { 1 | NIM_STRLIT_FLAG, "&" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_36 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_35};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_37 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_29};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_38 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_31};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_39 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_33};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_40 = { 1 | NIM_STRLIT_FLAG, "+" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_41 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_40};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_42 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_43 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_42};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_44 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_45 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_44};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_46 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_44};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_47 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_48 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_49 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_50 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_49};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_51 = { 3 | NIM_STRLIT_FLAG, "not" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_52 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_51};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_53 = { 1 | NIM_STRLIT_FLAG, "$" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_54 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_53};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_55 = { 2 | NIM_STRLIT_FLAG, "-(" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_56 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_55};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_57 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_58 = { 5 | NIM_STRLIT_FLAG, "not (" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_59 = {5, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_58};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_60 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_61 = { 4 | NIM_STRLIT_FLAG, "str(" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_62 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_61};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_63 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_64 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_42};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_65 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_66 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_42};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_67 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_68 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_67};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_69 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_47};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_70 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_71 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_70};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_72 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_67};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_73 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_74 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_73};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_75 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_70};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_76 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_73};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_77 = { 3 | NIM_STRLIT_FLAG, " = " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_78 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_77};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_79 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_77};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_80 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_77};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_81 = { 3 | NIM_STRLIT_FLAG, "if " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_82 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_81};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_83 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_84 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_83};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_85 = { 5 | NIM_STRLIT_FLAG, "elif " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_86 = {5, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_85};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_87 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_83};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_88 = { 5 | NIM_STRLIT_FLAG, "else:" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_89 = {5, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_88};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_90 = { 4 | NIM_STRLIT_FLAG, "for " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_91 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_90};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_92 = { 4 | NIM_STRLIT_FLAG, " in " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_93 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_92};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_94 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_83};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_95 = { 6 | NIM_STRLIT_FLAG, "while " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_96 = {6, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_95};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_97 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_83};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_98 = { 16 | NIM_STRLIT_FLAG, "break  # label \'" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_99 = {16, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_98};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_100 = { 19 | NIM_STRLIT_FLAG, "\' ignored in Python" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_101 = {19, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_100};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_102 = { 5 | NIM_STRLIT_FLAG, "break" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_103 = {5, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_102};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_104 = { 19 | NIM_STRLIT_FLAG, "continue  # label \'" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_105 = {19, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_104};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_106 = {19, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_100};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_107 = { 8 | NIM_STRLIT_FLAG, "continue" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_108 = {8, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_107};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_109 = { 13 | NIM_STRLIT_FLAG, "  # var param" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_110 = {13, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_109};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_111 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_112 = {90, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_111};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_113 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_67};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_114 = { 4 | NIM_STRLIT_FLAG, "def " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_115 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_114};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_116 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_42};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_117 = { 2 | NIM_STRLIT_FLAG, "):" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_118 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_117};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_119 = { 7 | NIM_STRLIT_FLAG, "return " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_120 = {7, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_119};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_121 = { 7 | NIM_STRLIT_FLAG, "import " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_122 = {7, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_121};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_123 = { 2 | NIM_STRLIT_FLAG, "# " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_124 = {2, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_123};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_125 = { 6 | NIM_STRLIT_FLAG, "class " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_126 = {6, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_125};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_127 = { 7 | NIM_STRLIT_FLAG, "(Enum):" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_128 = {7, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_127};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_129 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_10};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_130 = { 4 | NIM_STRLIT_FLAG, "    " };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_131 = {4, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_130};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_132 = {3, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_77};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_133 = {90, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_111};
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_134 = {1, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_10};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_135 = { 8 | NIM_STRLIT_FLAG, "    pass" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_136 = {8, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_135};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_137 = { 22 | NIM_STRLIT_FLAG, "#!/usr/bin/env python3" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_138 = {22, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_137};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__o8iAsxsEBBat1Zp0sJwleQ_139 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__o8iAsxsEBBat1Zp0sJwleQ_140 = {0, (NimStrPayload*)&TM__o8iAsxsEBBat1Zp0sJwleQ_139};
extern NIM_BOOL nimInErrorMode__system_u4234;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateInt__niminiZbackendsZpython95backend_u62)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NI value_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = dollar___systemZdollars_u14(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateFloat__niminiZbackendsZpython95backend_u66)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NF value_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = dollar___system_u4717(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__o8iAsxsEBBat1Zp0sJwleQ_23;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)2147483647)){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__o8iAsxsEBBat1Zp0sJwleQ_23)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__o8iAsxsEBBat1Zp0sJwleQ_23);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateString__niminiZbackendsZpython95backend_u73)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 value_p1) {
	NimStringV2 result;
	NimStringV2 escaped_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	escaped_1.len = 0; escaped_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD_ = nsuReplaceStr(value_p1, TM__o8iAsxsEBBat1Zp0sJwleQ_3, TM__o8iAsxsEBBat1Zp0sJwleQ_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__2 = nsuReplaceStr(colontmpD_, TM__o8iAsxsEBBat1Zp0sJwleQ_7, TM__o8iAsxsEBBat1Zp0sJwleQ_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__3 = nsuReplaceStr(colontmpD__2, TM__o8iAsxsEBBat1Zp0sJwleQ_11, TM__o8iAsxsEBBat1Zp0sJwleQ_13);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__4 = nsuReplaceStr(colontmpD__3, TM__o8iAsxsEBBat1Zp0sJwleQ_15, TM__o8iAsxsEBBat1Zp0sJwleQ_17);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	escaped_1 = nsuReplaceStr(colontmpD__4, TM__o8iAsxsEBBat1Zp0sJwleQ_19, TM__o8iAsxsEBBat1Zp0sJwleQ_21);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(escaped_1.len + 2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_22);
appendString((&T1_), escaped_1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_24);
	result = T1_;
	if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__4.p);
}
	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	if (escaped_1.p && !(escaped_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(escaped_1.p);
}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBool__niminiZbackendsZpython95backend_u78)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NIM_BOOL value_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!value_p1) goto LA4_;
		result = TM__o8iAsxsEBBat1Zp0sJwleQ_26;
	}
	goto LA2_;
LA4_: ;
	{
		result = TM__o8iAsxsEBBat1Zp0sJwleQ_28;
	}
LA2_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIdent__niminiZbackendsZpython95backend_u82)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	eqcopy___system_u2642((&result), name_p1);
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBinOp__niminiZbackendsZpython95backend_u86)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 left_p1, NimStringV2 op_p2, NimStringV2 right_p3) {
	NimStringV2 result;
	NimStringV2 pythonOp_1;
	NimStringV2 T1_;
	NimStringV2 T13_;
	pythonOp_1.len = 0; pythonOp_1.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	if (eqStrings(op_p2, TM__o8iAsxsEBBat1Zp0sJwleQ_30)) goto LA2_;
	if (eqStrings(op_p2, TM__o8iAsxsEBBat1Zp0sJwleQ_32)) goto LA3_;
	if (eqStrings(op_p2, TM__o8iAsxsEBBat1Zp0sJwleQ_34)) goto LA4_;
	if (eqStrings(op_p2, TM__o8iAsxsEBBat1Zp0sJwleQ_36)) goto LA5_;
	goto LA6_;
	LA2_: ;
	{
		pythonOp_1 = TM__o8iAsxsEBBat1Zp0sJwleQ_37;
	}
	goto LA7_;
	LA3_: ;
	{
		pythonOp_1 = TM__o8iAsxsEBBat1Zp0sJwleQ_38;
	}
	goto LA7_;
	LA4_: ;
	{
		pythonOp_1 = TM__o8iAsxsEBBat1Zp0sJwleQ_39;
	}
	goto LA7_;
	LA5_: ;
	{
		pythonOp_1 = TM__o8iAsxsEBBat1Zp0sJwleQ_41;
	}
	goto LA7_;
	LA6_: ;
	{
		pythonOp_1 = op_p2;
	}
LA7_: ;
	T13_.len = 0; T13_.p = NIM_NIL;
	T13_ = rawNewString(left_p1.len + pythonOp_1.len + right_p3.len + 4);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_43);
appendString((&T13_), left_p1);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_45);
appendString((&T13_), pythonOp_1);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_46);
appendString((&T13_), right_p3);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_48);
	result = T13_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateUnaryOp__niminiZbackendsZpython95backend_u93)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 op_p1, NimStringV2 operand_p2) {
	NimStringV2 result;
	if (eqStrings(op_p1, TM__o8iAsxsEBBat1Zp0sJwleQ_50)) goto LA1_;
	if (eqStrings(op_p1, TM__o8iAsxsEBBat1Zp0sJwleQ_52)) goto LA2_;
	if (eqStrings(op_p1, TM__o8iAsxsEBBat1Zp0sJwleQ_54)) goto LA3_;
	goto LA4_;
	LA1_: ;
	{
		NimStringV2 T7_;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(operand_p2.len + 3);
appendString((&T7_), TM__o8iAsxsEBBat1Zp0sJwleQ_56);
appendString((&T7_), operand_p2);
appendString((&T7_), TM__o8iAsxsEBBat1Zp0sJwleQ_57);
		result = T7_;
	}
	goto LA5_;
	LA2_: ;
	{
		NimStringV2 T9_;
		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = rawNewString(operand_p2.len + 6);
appendString((&T9_), TM__o8iAsxsEBBat1Zp0sJwleQ_59);
appendString((&T9_), operand_p2);
appendString((&T9_), TM__o8iAsxsEBBat1Zp0sJwleQ_60);
		result = T9_;
	}
	goto LA5_;
	LA3_: ;
	{
		NimStringV2 T11_;
		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = rawNewString(operand_p2.len + 5);
appendString((&T11_), TM__o8iAsxsEBBat1Zp0sJwleQ_62);
appendString((&T11_), operand_p2);
appendString((&T11_), TM__o8iAsxsEBBat1Zp0sJwleQ_63);
		result = T11_;
	}
	goto LA5_;
	LA4_: ;
	{
		NimStringV2 T13_;
		T13_.len = 0; T13_.p = NIM_NIL;
		T13_ = rawNewString(op_p1.len + operand_p2.len + 2);
appendString((&T13_), op_p1);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_64);
appendString((&T13_), operand_p2);
appendString((&T13_), TM__o8iAsxsEBBat1Zp0sJwleQ_65);
		result = T13_;
	}
LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateCall__niminiZbackendsZpython95backend_u98)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 funcName_p1, tySequence__sM4lkSb7zS6F7OVMvW9cffQ args_p2) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuJoinSep(((args_p2).p) ? (args_p2.p->data) : NIM_NIL, args_p2.len, TM__o8iAsxsEBBat1Zp0sJwleQ_68);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(funcName_p1.len + colontmpD_.len + 2);
appendString((&T1_), funcName_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_66);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_69);
	result = T1_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateArray__niminiZbackendsZpython95backend_u103)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ elements_p1) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nsuJoinSep(((elements_p1).p) ? (elements_p1.p->data) : NIM_NIL, elements_p1.len, TM__o8iAsxsEBBat1Zp0sJwleQ_72);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = rawNewString(colontmpD_.len + 2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_71);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_74);
	result = T1_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIndex__niminiZbackendsZpython95backend_u107)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 target_p1, NimStringV2 index_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(target_p1.len + index_p2.len + 2);
appendString((&T1_), target_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_75);
appendString((&T1_), index_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_76);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateVarDecl__niminiZbackendsZpython95backend_u112)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + name_p1.len + value_p2.len + 3);
appendString((&T1_), indent_p3);
appendString((&T1_), name_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_78);
appendString((&T1_), value_p2);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateLetDecl__niminiZbackendsZpython95backend_u118)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + name_p1.len + value_p2.len + 3);
appendString((&T1_), indent_p3);
appendString((&T1_), name_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_79);
appendString((&T1_), value_p2);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateAssignment__niminiZbackendsZpython95backend_u124)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 target_p1, NimStringV2 value_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + target_p1.len + value_p2.len + 3);
appendString((&T1_), indent_p3);
appendString((&T1_), target_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_80);
appendString((&T1_), value_p2);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateIfStmt__niminiZbackendsZpython95backend_u130)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 4);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_82);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_84);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElifStmt__niminiZbackendsZpython95backend_u135)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 6);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_86);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_87);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateElseStmt__niminiZbackendsZpython95backend_u140)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 indent_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p1.len + 5);
appendString((&T1_), indent_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_89);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateForLoop__niminiZbackendsZpython95backend_u144)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 varName_p1, NimStringV2 iterable_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + varName_p1.len + iterable_p2.len + 9);
appendString((&T1_), indent_p3);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_91);
appendString((&T1_), varName_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_93);
appendString((&T1_), iterable_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_94);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateWhileLoop__niminiZbackendsZpython95backend_u150)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 condition_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + condition_p1.len + 7);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_96);
appendString((&T1_), condition_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_97);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateBreak__niminiZbackendsZpython95backend_u155)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 label_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	{
		NimStringV2 T5_;
		if (!(((NI)0) < label_p1.len)) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = rawNewString(indent_p2.len + label_p1.len + 35);
appendString((&T5_), indent_p2);
appendString((&T5_), TM__o8iAsxsEBBat1Zp0sJwleQ_99);
appendString((&T5_), label_p1);
appendString((&T5_), TM__o8iAsxsEBBat1Zp0sJwleQ_101);
		result = T5_;
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 T7_;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(indent_p2.len + 5);
appendString((&T7_), indent_p2);
appendString((&T7_), TM__o8iAsxsEBBat1Zp0sJwleQ_103);
		result = T7_;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateContinue__niminiZbackendsZpython95backend_u160)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 label_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	{
		NimStringV2 T5_;
		if (!(((NI)0) < label_p1.len)) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = rawNewString(indent_p2.len + label_p1.len + 38);
appendString((&T5_), indent_p2);
appendString((&T5_), TM__o8iAsxsEBBat1Zp0sJwleQ_105);
appendString((&T5_), label_p1);
appendString((&T5_), TM__o8iAsxsEBBat1Zp0sJwleQ_106);
		result = T5_;
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 T7_;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(indent_p2.len + 8);
appendString((&T7_), indent_p2);
appendString((&T7_), TM__o8iAsxsEBBat1Zp0sJwleQ_108);
		result = T7_;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProcDecl__niminiZbackendsZpython95backend_u165)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, tySequence__4Aje6Q7a019cMMvArOJ2Tzg params_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ paramStrs_1;
	NimStringV2 paramList_1;
	NimStringV2 T16_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	paramStrs_1.len = 0; paramStrs_1.p = NIM_NIL;
	paramList_1.len = 0; paramList_1.p = NIM_NIL;
	paramStrs_1.len = 0; paramStrs_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ* param_1;
		NI i_1;
		NI L_1;
		NI T2_;
		param_1 = (tyObject_ProcParam__VeOCXcXge6uepWdd9c7359cQ*)0;
		i_1 = ((NI)0);
		T2_ = params_p2.len;
		L_1 = T2_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				if (i_1 < 0 || i_1 >= params_p2.len){ raiseIndexError2(i_1,params_p2.len-1); goto BeforeRet_;
				}
				param_1 = (&params_p2.p->data[i_1]);
				{
					NimStringV2 T9_;
					if (!(*param_1).isVar) goto LA7_;
					T9_.len = 0; T9_.p = NIM_NIL;
					T9_ = rawNewString((*param_1).name.len + 13);
appendString((&T9_), (*param_1).name);
appendString((&T9_), TM__o8iAsxsEBBat1Zp0sJwleQ_110);
					add__stdZenumutils_u70((&paramStrs_1), T9_);
				}
				goto LA5_;
LA7_: ;
				{
					NimStringV2 colontmpD_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD_ = eqdup___system_u2645((*param_1).name);
					add__stdZenumutils_u70((&paramStrs_1), colontmpD_);
				}
LA5_: ;
				i_1 += ((NI)1);
				{
					NI T13_;
					T13_ = params_p2.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u234(TM__o8iAsxsEBBat1Zp0sJwleQ_112);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA14_: ;
			} LA4: ;
		}
	}
	paramList_1 = nsuJoinSep(((paramStrs_1).p) ? (paramStrs_1.p->data) : NIM_NIL, paramStrs_1.len, TM__o8iAsxsEBBat1Zp0sJwleQ_113);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T16_.len = 0; T16_.p = NIM_NIL;
	T16_ = rawNewString(indent_p3.len + name_p1.len + paramList_1.len + 7);
appendString((&T16_), indent_p3);
appendString((&T16_), TM__o8iAsxsEBBat1Zp0sJwleQ_115);
appendString((&T16_), name_p1);
appendString((&T16_), TM__o8iAsxsEBBat1Zp0sJwleQ_116);
appendString((&T16_), paramList_1);
appendString((&T16_), TM__o8iAsxsEBBat1Zp0sJwleQ_118);
	result = T16_;
	if (paramList_1.p && !(paramList_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(paramList_1.p);
}
	eqdestroy___system_u3717(paramStrs_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateReturn__niminiZbackendsZpython95backend_u189)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 value_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + value_p1.len + 7);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_120);
appendString((&T1_), value_p1);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateImport__niminiZbackendsZpython95backend_u194)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 module_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(module_p1.len + 7);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_122);
appendString((&T1_), module_p1);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateComment__niminiZbackendsZpython95backend_u198)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 text_p1, NimStringV2 indent_p2) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p2.len + text_p1.len + 2);
appendString((&T1_), indent_p2);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_124);
appendString((&T1_), text_p1);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateEnumType__niminiZbackendsZpython95backend_u203)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0, NimStringV2 name_p1, tySequence__jwzrUFjG9akTIJTBBFvvqxw values_p2, NimStringV2 indent_p3) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(indent_p3.len + name_p1.len + 13);
appendString((&T1_), indent_p3);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_126);
appendString((&T1_), name_p1);
appendString((&T1_), TM__o8iAsxsEBBat1Zp0sJwleQ_128);
	result = T1_;
	{
		NI T4_;
		T4_ = values_p2.len;
		if (!(((NI)0) < T4_)) goto LA5_;
		{
			tyTuple__XOVT24GHXwqiEj5GCsEGCA* enumVal_1;
			NI i_1;
			NI L_1;
			NI T8_;
			enumVal_1 = (tyTuple__XOVT24GHXwqiEj5GCsEGCA*)0;
			i_1 = ((NI)0);
			T8_ = values_p2.len;
			L_1 = T8_;
			{
				while (1) {
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T11_;
					if (!(i_1 < L_1)) goto LA10;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					if (i_1 < 0 || i_1 >= values_p2.len){ raiseIndexError2(i_1,values_p2.len-1); goto BeforeRet_;
					}
					enumVal_1 = (&values_p2.p->data[i_1]);
					T11_.len = 0; T11_.p = NIM_NIL;
					colontmpD_ = dollar___systemZdollars_u14((*enumVal_1).Field1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T11_ = rawNewString(indent_p3.len + (*enumVal_1).Field0.len + colontmpD_.len + 8);
appendString((&T11_), TM__o8iAsxsEBBat1Zp0sJwleQ_129);
appendString((&T11_), indent_p3);
appendString((&T11_), TM__o8iAsxsEBBat1Zp0sJwleQ_131);
appendString((&T11_), (*enumVal_1).Field0);
appendString((&T11_), TM__o8iAsxsEBBat1Zp0sJwleQ_132);
appendString((&T11_), colontmpD_);
					colontmpD__2 = T11_;
					prepareAdd((&result), colontmpD__2.len + 0);
appendString((&result), colontmpD__2);
					i_1 += ((NI)1);
					{
						NI T14_;
						T14_ = values_p2.len;
						if (!!((T14_ == L_1))) goto LA15_;
						failedAssertImpl__stdZassertions_u234(TM__o8iAsxsEBBat1Zp0sJwleQ_133);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA15_: ;
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
				} LA10: ;
			}
		}
	}
	goto LA2_;
LA5_: ;
	{
		NimStringV2 colontmpD__3;
		NimStringV2 T18_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		T18_.len = 0; T18_.p = NIM_NIL;
		T18_ = rawNewString(indent_p3.len + 9);
appendString((&T18_), TM__o8iAsxsEBBat1Zp0sJwleQ_134);
appendString((&T18_), indent_p3);
appendString((&T18_), TM__o8iAsxsEBBat1Zp0sJwleQ_136);
		colontmpD__3 = T18_;
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramHeader__niminiZbackendsZpython95backend_u255)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0) {
	NimStringV2 result;
	result = TM__o8iAsxsEBBat1Zp0sJwleQ_138;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, generateProgramFooter__niminiZbackendsZpython95backend_u258)(tyObject_PythonBackendcolonObjectType___G9cKPSxmgv6mbxGi9aM4OWPQ* backend_p0) {
	NimStringV2 result;
	result = TM__o8iAsxsEBBat1Zp0sJwleQ_140;
	return result;
}
