/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -I/workspaces/storie-vendor/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@sstdlib@stypeconv.nim.c.o /workspaces/telestorie/nimcache_wasm_sdl3/@p..@sstdlib@stypeconv.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A;
typedef struct tyObject_Env__YOkjv76lcCADUm0ClKJM5g tyObject_Env__YOkjv76lcCADUm0ClKJM5g;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA tySequence__Gf9avO3sd1YsdKIYcdAbNvA;
typedef struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg;
typedef struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A tyObject_Table__Kkv168EwyeC2mcswHBvZ1A;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ tySequence__2nVARL7psn6awrm07aftcQ;
typedef struct tySequence__2nVARL7psn6awrm07aftcQ_Content tySequence__2nVARL7psn6awrm07aftcQ_Content;
typedef struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA;
typedef struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA tyTuple__9bJQUgvR2blr9cUNMhbZPKyA;
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA {
  NI len; tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ;
struct tySequence__2nVARL7psn6awrm07aftcQ {
  NI len; tySequence__2nVARL7psn6awrm07aftcQ_Content* p;
};
struct tyObject_Table__Kkv168EwyeC2mcswHBvZ1A {
	tySequence__2nVARL7psn6awrm07aftcQ data;
	NI counter;
};
struct tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA {
	NU64 a0;
	NU64 a1;
};
struct tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A {
	tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ kind;
	NI i;
	NF f;
	NIM_BOOL b;
	NimStringV2 s;
	tyObject_FunctionValcolonObjectType___pGR2JmOxTVrNPc3jK4h0Xg* fnVal;
	tyObject_Table__Kkv168EwyeC2mcswHBvZ1A map;
	tySequence__Gf9avO3sd1YsdKIYcdAbNvA arr;
	void* ptrVal;
	tyObject_Rand__xd6HIyS1W9aI4gBq8W9ct0qA randState;
};
struct tySequence__Gf9avO3sd1YsdKIYcdAbNvA_Content { NI cap; tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* data[SEQ_DECL_SIZE]; };
struct tyTuple__9bJQUgvR2blr9cUNMhbZPKyA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* Field2;
};
struct tySequence__2nVARL7psn6awrm07aftcQ_Content { NI cap; tyTuple__9bJQUgvR2blr9cUNMhbZPKyA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u6388)(NimStringV2 errormsg_p0, NI errorcode_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___niminiZruntime_u95)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A** dest_p0, tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valInt__niminiZruntime_u1086)(NI i_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, toInt__niminiZruntime_u3282)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valFloat__niminiZruntime_u1089)(NF f_p0);
N_LIB_PRIVATE N_NIMCALL(NF, toFloat__niminiZruntime_u3276)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valBool__niminiZruntime_u1092)(NIM_BOOL b_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, toBool__niminiZruntime_u3226)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, valString__niminiZruntime_u1095)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___niminiZruntime_u59)(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* v_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__nqyEs29as0LNVIOOH8LK9avA_2 = { 23 | NIM_STRLIT_FLAG, "int requires 1 argument" };
static const NimStringV2 TM__nqyEs29as0LNVIOOH8LK9avA_3 = {23, (NimStrPayload*)&TM__nqyEs29as0LNVIOOH8LK9avA_2};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__nqyEs29as0LNVIOOH8LK9avA_4 = { 25 | NIM_STRLIT_FLAG, "float requires 1 argument" };
static const NimStringV2 TM__nqyEs29as0LNVIOOH8LK9avA_5 = {25, (NimStrPayload*)&TM__nqyEs29as0LNVIOOH8LK9avA_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__nqyEs29as0LNVIOOH8LK9avA_6 = { 24 | NIM_STRLIT_FLAG, "bool requires 1 argument" };
static const NimStringV2 TM__nqyEs29as0LNVIOOH8LK9avA_7 = {24, (NimStrPayload*)&TM__nqyEs29as0LNVIOOH8LK9avA_6};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__nqyEs29as0LNVIOOH8LK9avA_8 = { 23 | NIM_STRLIT_FLAG, "str requires 1 argument" };
static const NimStringV2 TM__nqyEs29as0LNVIOOH8LK9avA_9 = {23, (NimStrPayload*)&TM__nqyEs29as0LNVIOOH8LK9avA_8};
extern NIM_BOOL nimInErrorMode__system_u4234;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4234);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, nimini_toInt__niminiZstdlibZtypeconv_u2)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		NI T3_;
		T3_ = args_p1.len;
		if (!(T3_ < ((NI)1))) goto LA4_;
		quit__system_u6388(TM__nqyEs29as0LNVIOOH8LK9avA_3, ((NI)1));
	}
LA4_: ;
	if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
	}
	switch ((*args_p1.p->data[((NI)0)]).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		eqcopy___niminiZruntime_u95(&result, args_p1.p->data[((NI)0)], NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)2):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		if ((((NI) (((NI64) ((*args_p1.p->data[((NI)0)]).f))))) < ((NI)(-2147483647 -1)) || (((NI) (((NI64) ((*args_p1.p->data[((NI)0)]).f))))) > ((NI)2147483647)){ raiseRangeErrorI(((NI) (((NI64) ((*args_p1.p->data[((NI)0)]).f)))), ((NI)(-2147483647 -1)), ((NI)2147483647)); goto BeforeRet_;
		}
		result = valInt__niminiZruntime_u1086((((NI) (((NI64) ((*args_p1.p->data[((NI)0)]).f))))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)4):
	{
		NI T9_;
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		T9_ = (NI)0;
		T9_ = toInt__niminiZruntime_u3282(args_p1.p->data[((NI)0)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = valInt__niminiZruntime_u1086(T9_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = valInt__niminiZruntime_u1086(((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, nimini_toFloat__niminiZstdlibZtypeconv_u9)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		NI T3_;
		T3_ = args_p1.len;
		if (!(T3_ < ((NI)1))) goto LA4_;
		quit__system_u6388(TM__nqyEs29as0LNVIOOH8LK9avA_5, ((NI)1));
	}
LA4_: ;
	if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
	}
	switch ((*args_p1.p->data[((NI)0)]).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		result = valFloat__niminiZruntime_u1089(((NF) ((*args_p1.p->data[((NI)0)]).i)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)2):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		eqcopy___niminiZruntime_u95(&result, args_p1.p->data[((NI)0)], NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)4):
	{
		NF T9_;
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		T9_ = (NF)0;
		T9_ = toFloat__niminiZruntime_u3276(args_p1.p->data[((NI)0)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = valFloat__niminiZruntime_u1089(T9_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = valFloat__niminiZruntime_u1089(0.0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, nimini_toBool__niminiZstdlibZtypeconv_u16)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		NI T3_;
		T3_ = args_p1.len;
		if (!(T3_ < ((NI)1))) goto LA4_;
		quit__system_u6388(TM__nqyEs29as0LNVIOOH8LK9avA_7, ((NI)1));
	}
LA4_: ;
	if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
	}
	switch ((*args_p1.p->data[((NI)0)]).kind) {
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)3):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		eqcopy___niminiZruntime_u95(&result, args_p1.p->data[((NI)0)], NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)1):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		result = valBool__niminiZruntime_u1092(!(((*args_p1.p->data[((NI)0)]).i == ((NI)0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)2):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		result = valBool__niminiZruntime_u1092(!(((*args_p1.p->data[((NI)0)]).f == 0.0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_ValueKind__QxtKmTl5uLHSaIOWTFlTlQ)4):
	{
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		result = valBool__niminiZruntime_u1092((((NI)0) < (*args_p1.p->data[((NI)0)]).s.len));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	default:
	{
		NIM_BOOL T11_;
		if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto BeforeRet_;
		}
		T11_ = (NIM_BOOL)0;
		T11_ = toBool__niminiZruntime_u3226(args_p1.p->data[((NI)0)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = valBool__niminiZruntime_u1092(T11_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A*, nimini_toString__niminiZstdlibZtypeconv_u23)(tyObject_Env__YOkjv76lcCADUm0ClKJM5g* env_p0, tySequence__Gf9avO3sd1YsdKIYcdAbNvA args_p1) {
	tyObject_ValuecolonObjectType___HXMY0yUY2exDyJ1egQNy5A* result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	{
		NI T4_;
		T4_ = args_p1.len;
		if (!(T4_ < ((NI)1))) goto LA5_;
		quit__system_u6388(TM__nqyEs29as0LNVIOOH8LK9avA_9, ((NI)1));
	}
LA5_: ;
	if (((NI)0) < 0 || ((NI)0) >= args_p1.len){ raiseIndexError2(((NI)0),args_p1.len-1); goto LA1_;
	}
	colontmpD_ = dollar___niminiZruntime_u59(args_p1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = valString__niminiZruntime_u1095(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
