/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3 -fno-strict-aliasing -sUSE_SDL=3 -I/workspaces/storie-vendor/vendor/SDL_ttf-src/include -Os   -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie -o /workspaces/telestorie/nimcache_wasm_sdl3/@pstd@sprivate@sosappdirs.nim.c.o /workspaces/telestorie/nimcache_wasm_sdl3/@pstd@sprivate@sosappdirs.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosappdirs_u83)(NimStringV2* dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)4))) goto LA2;
			if (dest_p0[(colontmp_)- 0].p && !(dest_p0[(colontmp_)- 0].p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0[(colontmp_)- 0].p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
