/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib -Os -fno-ident  -fPIC  -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie/lib -o /workspaces/telestorie/nimcache_audio_plugin/@maudio_plugin_impl.nim.c.o /workspaces/telestorie/nimcache_audio_plugin/@maudio_plugin_impl.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "miniaudio.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw;
typedef struct tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tySequence__qE1lkEbYXEtaF1pKH4BcRQ tySequence__qE1lkEbYXEtaF1pKH4BcRQ;
typedef struct tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content;
typedef struct tyObject_Table__XL9chObRXDAwcyK5wjcAFrw tyObject_Table__XL9chObRXDAwcyK5wjcAFrw;
typedef struct tySequence__dlbJs2dLdQqBXCQrVZBGvw tySequence__dlbJs2dLdQqBXCQrVZBGvw;
typedef struct tySequence__dlbJs2dLdQqBXCQrVZBGvw_Content tySequence__dlbJs2dLdQqBXCQrVZBGvw_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ;
typedef struct tyTuple__wFiEoMzi4jqMEpWD8mWDEw tyTuple__wFiEoMzi4jqMEpWD8mWDEw;
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ data;
	NI sampleRate;
	NI channels;
};
struct tySequence__qE1lkEbYXEtaF1pKH4BcRQ {
  NI len; tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content* p;
};
struct tySequence__dlbJs2dLdQqBXCQrVZBGvw {
  NI len; tySequence__dlbJs2dLdQqBXCQrVZBGvw_Content* p;
};
struct tyObject_Table__XL9chObRXDAwcyK5wjcAFrw {
	tySequence__dlbJs2dLdQqBXCQrVZBGvw data;
	NI counter;
};
struct tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw {
	ma_context context;
	ma_device device;
	ma_device_config deviceConfig;
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg currentSample;
	NI currentPosition;
	tySequence__qE1lkEbYXEtaF1pKH4BcRQ playbackQueue;
	tyObject_Table__XL9chObRXDAwcyK5wjcAFrw sounds;
	NI sampleRate;
	NI channels;
	NIM_BOOL initialized;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ {
	NI rc;
	NI rootIdx;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NI32 tyEnum_ma_device_type__eC2tfmbtxg5QmDMZQgqBkw;
typedef N_CDECL_PTR(void, tyProc__LWi3Vsh7YYQlHmF9b8enxGQ) (ma_device* pDevice_p0, void* pOutput_p1, void* pInput_p2, NU32 frameCount_p3);
typedef NI32 tyEnum_ma_format__4gBo1y9cEtmM9ahU59aSExT1g;
typedef NI32 tyEnum_ma_performance_profile__JGKYbCcpAx69aNV7fUbvOZQ;
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE]; };
struct tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content { NI cap; tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg data[SEQ_DECL_SIZE]; };
struct tyTuple__wFiEoMzi4jqMEpWD8mWDEw {
	NI Field0;
	NimStringV2 Field1;
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg Field2;
};
struct tySequence__dlbJs2dLdQqBXCQrVZBGvw_Content { NI cap; tyTuple__wFiEoMzi4jqMEpWD8mWDEw data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(void*, audio_plugin_init)(int sampleRate_p0, int channels_p1);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___audio95plugin95impl_u596)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw** dest_p0, tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* src_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u553)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u470)(tySequence__dlbJs2dLdQqBXCQrVZBGvw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u209)(tySequence__qE1lkEbYXEtaF1pKH4BcRQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95gen_u242)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__XL9chObRXDAwcyK5wjcAFrw, initTable__audio95plugin95impl_u311)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_NIMCALL(void, ma_device_config_set_callback)(ma_device_config* pConfig_p0, tyProc__LWi3Vsh7YYQlHmF9b8enxGQ callback_p1, void* pUserData_p2);
N_LIB_PRIVATE N_CDECL(void, audioDataCallback_plugin__audio95plugin95impl_u25)(ma_device* pDevice_p0, void* pOutput_p1, void* pInput_p2, NU32 frameCount_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___audio95gen_u415)(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* dest_p0, tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* src_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, delete__audio95plugin95impl_u46)(tySequence__qE1lkEbYXEtaF1pKH4BcRQ* x_p0, NI i_p1);
N_NIMCALL(void, ma_device_config_set_playback_format)(ma_device_config* pConfig_p0, tyEnum_ma_format__4gBo1y9cEtmM9ahU59aSExT1g format_p1, NU32 channels_p2, NU32 sampleRate_p3);
N_NIMCALL(void, ma_device_config_set_performance_profile)(ma_device_config* pConfig_p0, tyEnum_ma_performance_profile__JGKYbCcpAx69aNV7fUbvOZQ profile_p1);
N_NIMCALL(void, ma_device_config_set_no_pre_silenced_output_buffer)(ma_device_config* pConfig_p0, NU32 value_p1);
N_NIMCALL(void, ma_device_config_set_no_clip)(ma_device_config* pConfig_p0, NU32 value_p1);
N_NIMCALL(void, ma_device_config_set_period_size)(ma_device_config* pConfig_p0, NU32 periodSizeInFrames_p1);
N_LIB_EXPORT N_CDECL(void, audio_plugin_cleanup)(void* ctx_p0);
N_LIB_EXPORT N_CDECL(int, audio_plugin_play_sample)(void* ctx_p0, NF32* dataPtr_p1, int dataLen_p2, int channels_p3, int sampleRate_p4, float volume_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95gen_u412)(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ, newSeq__audio95gen_u157)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___audio95gen_u251)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest_p0, tySequence__4Xyxy0Om14N6K1l5e9bUPSQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___audio95gen_u421)(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* dest_p0, tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___audio95gen_u409)(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__audio95plugin95impl_u776)(tySequence__qE1lkEbYXEtaF1pKH4BcRQ* x_p0, tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* y_p1);
N_LIB_EXPORT N_CDECL(void, audio_plugin_stop_all)(void* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___audio95plugin95impl_u218)(tySequence__qE1lkEbYXEtaF1pKH4BcRQ* dest_p0, tySequence__qE1lkEbYXEtaF1pKH4BcRQ src_p1);
N_LIB_EXPORT N_CDECL(int, audio_plugin_register_sound)(void* ctx_p0, NCSTRING namePtr_p1, NF32* dataPtr_p2, int dataLen_p3, int channels_p4, int sampleRate_p5);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___audio95plugin95impl_u879)(tyObject_Table__XL9chObRXDAwcyK5wjcAFrw* t_p0, NimStringV2 key_p1, tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg* val_p2);
N_LIB_EXPORT N_CDECL(NCSTRING, audio_plugin_get_version)(void);
N_LIB_EXPORT N_CDECL(int, audio_plugin_is_initialized)(void* ctx_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u587)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_3 = { 34 | NIM_STRLIT_FLAG, "[Audio Plugin] Already initialized" };
static const struct {
  NI cap; NIM_CHAR data[51+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_4 = { 51 | NIM_STRLIT_FLAG, "[Audio Plugin] Failed to initialize audio context: " };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_5 = {51, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_4};
static const struct {
  NI cap; NIM_CHAR data[50+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_15 = { 50 | NIM_STRLIT_FLAG, "[Audio Plugin] Failed to initialize audio device: " };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_16 = {50, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_15};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_17 = { 45 | NIM_STRLIT_FLAG, "[Audio Plugin] Failed to start audio device: " };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_18 = {45, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_17};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_19 = { 28 | NIM_STRLIT_FLAG, "[Audio Plugin] Initialized (" };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_20 = {28, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_19};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_21 = { 5 | NIM_STRLIT_FLAG, " Hz, " };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_22 = {5, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_21};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_23 = { 10 | NIM_STRLIT_FLAG, " channels)" };
static const NimStringV2 TM__YVJx3uIBl5j6Ek0bbYma1g_24 = {10, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_23};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__YVJx3uIBl5j6Ek0bbYma1g_26 = { 25 | NIM_STRLIT_FLAG, "[Audio Plugin] Cleaned up" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__YVJx3uIBl5j6Ek0bbYma1g_2 = {{34, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__YVJx3uIBl5j6Ek0bbYma1g_25 = {{25, (NimStrPayload*)&TM__YVJx3uIBl5j6Ek0bbYma1g_26}}
;
N_LIB_PRIVATE tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* globalContext__audio95plugin95impl_u24;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4363;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__hLWKr9clDoQwq3AJwLFw0xQ*) (T5_));
		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u553)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* dest_p0) {
	eqdestroy___audio95plugin95impl_u470((*dest_p0).sounds.data);
	eqdestroy___audio95plugin95impl_u209((*dest_p0).playbackQueue);
	eqdestroy___audio95gen_u242((*dest_p0).currentSample.data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___audio95plugin95impl_u596)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw** dest_p0, tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* src_p1) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___audio95plugin95impl_u553((&(*(*dest_p0))));
		nimRawDispose((*dest_p0), ((NI)NIM_ALIGNOF(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw)));
	}
LA4_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4363);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, audioDataCallback_plugin__audio95plugin95impl_u25)(ma_device* pDevice_p0, void* pOutput_p1, void* pInput_p2, NU32 frameCount_p3) {
	NF32* output_1;
	NI totalSamples_1;
	NI TM__YVJx3uIBl5j6Ek0bbYma1g_6;
	NI outputIndex_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (globalContext__audio95plugin95impl_u24 == 0);
		if (T3_) goto LA4_;
		T3_ = !((*globalContext__audio95plugin95impl_u24).initialized);
LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	output_1 = ((NF32*) (pOutput_p1));
	if (nimMulInt(((NI) (frameCount_p3)), (*globalContext__audio95plugin95impl_u24).channels, &TM__YVJx3uIBl5j6Ek0bbYma1g_6)) { raiseOverflow(); goto BeforeRet_;
	};
	totalSamples_1 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_6);
	outputIndex_1 = ((NI)0);
	{
		while (1) {
			NI remaining_1;
			NI T26_;
			NI TM__YVJx3uIBl5j6Ek0bbYma1g_8;
			NI toCopy_1;
			NI TM__YVJx3uIBl5j6Ek0bbYma1g_9;
			NI TM__YVJx3uIBl5j6Ek0bbYma1g_13;
			NI TM__YVJx3uIBl5j6Ek0bbYma1g_14;
			if (!(outputIndex_1 < totalSamples_1)) goto LA8;
			{
				NIM_BOOL T11_;
				NI T12_;
				NI T14_;
				T11_ = (NIM_BOOL)0;
				T12_ = (*globalContext__audio95plugin95impl_u24).currentSample.data.len;
				T11_ = (T12_ == ((NI)0));
				if (T11_) goto LA13_;
				T14_ = (*globalContext__audio95plugin95impl_u24).currentSample.data.len;
				T11_ = (T14_ <= (*globalContext__audio95plugin95impl_u24).currentPosition);
LA13_: ;
				if (!T11_) goto LA15_;
				{
					NI T19_;
					T19_ = (*globalContext__audio95plugin95impl_u24).playbackQueue.len;
					if (!(((NI)0) < T19_)) goto LA20_;
					if (((NI)0) < 0 || ((NI)0) >= (*globalContext__audio95plugin95impl_u24).playbackQueue.len){ raiseIndexError2(((NI)0),(*globalContext__audio95plugin95impl_u24).playbackQueue.len-1); goto BeforeRet_;
					}
					eqcopy___audio95gen_u415((&(*globalContext__audio95plugin95impl_u24).currentSample), (&(*globalContext__audio95plugin95impl_u24).playbackQueue.p->data[((NI)0)]));
					delete__audio95plugin95impl_u46((&(*globalContext__audio95plugin95impl_u24).playbackQueue), ((NI)0));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					(*globalContext__audio95plugin95impl_u24).currentPosition = ((NI)0);
				}
				goto LA17_;
LA20_: ;
				{
					{
						NI i_1;
						NI i_2;
						i_1 = (NI)0;
						i_2 = outputIndex_1;
						{
							while (1) {
								NI TM__YVJx3uIBl5j6Ek0bbYma1g_7;
								if (!(i_2 < totalSamples_1)) goto LA25;
								i_1 = i_2;
								output_1[i_1] = 0.0f;
								if (nimAddInt(i_2, ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_7)) { raiseOverflow(); goto BeforeRet_;
								};
								i_2 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_7);
							} LA25: ;
						}
					}
					goto BeforeRet_;
				}
LA17_: ;
			}
LA15_: ;
			T26_ = (*globalContext__audio95plugin95impl_u24).currentSample.data.len;
			if (nimSubInt(T26_, (*globalContext__audio95plugin95impl_u24).currentPosition, &TM__YVJx3uIBl5j6Ek0bbYma1g_8)) { raiseOverflow(); goto BeforeRet_;
			};
			remaining_1 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_8);
			if (nimSubInt(totalSamples_1, outputIndex_1, &TM__YVJx3uIBl5j6Ek0bbYma1g_9)) { raiseOverflow(); goto BeforeRet_;
			};
			toCopy_1 = ((remaining_1 <= (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_9)) ? remaining_1 : (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_9));
			{
				NI i_3;
				NI i_4;
				i_3 = (NI)0;
				i_4 = ((NI)0);
				{
					while (1) {
						NI TM__YVJx3uIBl5j6Ek0bbYma1g_10;
						NI TM__YVJx3uIBl5j6Ek0bbYma1g_11;
						NI TM__YVJx3uIBl5j6Ek0bbYma1g_12;
						if (!(i_4 < toCopy_1)) goto LA29;
						i_3 = i_4;
						if (nimAddInt(outputIndex_1, i_3, &TM__YVJx3uIBl5j6Ek0bbYma1g_10)) { raiseOverflow(); goto BeforeRet_;
						};
						if (nimAddInt((*globalContext__audio95plugin95impl_u24).currentPosition, i_3, &TM__YVJx3uIBl5j6Ek0bbYma1g_11)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_11) < 0 || (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_11) >= (*globalContext__audio95plugin95impl_u24).currentSample.data.len){ raiseIndexError2((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_11),(*globalContext__audio95plugin95impl_u24).currentSample.data.len-1); goto BeforeRet_;
						}
						output_1[(NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_10)] = (*globalContext__audio95plugin95impl_u24).currentSample.data.p->data[(NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_11)];
						if (nimAddInt(i_4, ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_12)) { raiseOverflow(); goto BeforeRet_;
						};
						i_4 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_12);
					} LA29: ;
				}
			}
			if (nimAddInt((*globalContext__audio95plugin95impl_u24).currentPosition, toCopy_1, &TM__YVJx3uIBl5j6Ek0bbYma1g_13)) { raiseOverflow(); goto BeforeRet_;
			};
			(*globalContext__audio95plugin95impl_u24).currentPosition = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_13);
			if (nimAddInt(outputIndex_1, toCopy_1, &TM__YVJx3uIBl5j6Ek0bbYma1g_14)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndex_1 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_14);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(void*, audio_plugin_init)(int sampleRate_p0, int channels_p1) {
	void* result;
	int colontmpD_;
	int colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* T8_;
	int initResult_1;
	ma_context* T17_;
	ma_device_config* T18_;
	tyArray__haiLFy0nBviVTKFGuwztzQ T35_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = !((globalContext__audio95plugin95impl_u24 == 0));
		if (!(T4_)) goto LA5_;
		T4_ = (*globalContext__audio95plugin95impl_u24).initialized;
LA5_: ;
		if (!T4_) goto LA6_;
		echoBinSafe(TM__YVJx3uIBl5j6Ek0bbYma1g_2, 1);
		result = ((void*) (globalContext__audio95plugin95impl_u24));
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		goto BeforeRet_;
	}
LA6_: ;
	T8_ = NIM_NIL;
	T8_ = (tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw*) nimNewObj(sizeof(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw), NIM_ALIGNOF(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw));
	colontmpD_ = sampleRate_p0;
	(*T8_).sampleRate = ((NI) (colontmpD_));
	colontmpD__2 = channels_p1;
	(*T8_).channels = ((NI) (colontmpD__2));
	nimZeroMem((void*)(&(*T8_).currentSample), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	(*T8_).currentPosition = ((NI)0);
	(*T8_).playbackQueue.len = 0; (*T8_).playbackQueue.p = (tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content*) newSeqPayload(0, sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg), NIM_ALIGNOF(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	(*T8_).sounds = initTable__audio95plugin95impl_u311(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*T8_).initialized = NIM_FALSE;
	eqsink___audio95plugin95impl_u596(&globalContext__audio95plugin95impl_u24, T8_);
	initResult_1 = ma_context_init(NIM_NIL, ((NU32)0), NIM_NIL, (&(*globalContext__audio95plugin95impl_u24).context));
	{
		NimStringV2 colontmpD__5;
		tyArray__Re75IspeoxXy2oCZHwcRrA T14_;
		if (!!((initResult_1 == ((NI32)0)))) goto LA11_;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		T14_[0] = TM__YVJx3uIBl5j6Ek0bbYma1g_5;
		colontmpD__5 = dollar___systemZdollars_u29(initResult_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		T14_[1] = colontmpD__5;
		echoBinSafe(T14_, 2);
		result = NIM_NIL;
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		goto BeforeRet_;
		{
			LA13_:;
		}
		{
			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA11_: ;
	(*globalContext__audio95plugin95impl_u24).deviceConfig = ma_device_config_init(((tyEnum_ma_device_type__eC2tfmbtxg5QmDMZQgqBkw)1));
	ma_device_config_set_callback((&(*globalContext__audio95plugin95impl_u24).deviceConfig), audioDataCallback_plugin__audio95plugin95impl_u25, ((void*) (globalContext__audio95plugin95impl_u24)));
	ma_device_config_set_playback_format((&(*globalContext__audio95plugin95impl_u24).deviceConfig), ((tyEnum_ma_format__4gBo1y9cEtmM9ahU59aSExT1g)5), ((NU32) (channels_p1)), ((NU32) (sampleRate_p0)));
	ma_device_config_set_performance_profile((&(*globalContext__audio95plugin95impl_u24).deviceConfig), ((tyEnum_ma_performance_profile__JGKYbCcpAx69aNV7fUbvOZQ)0));
	ma_device_config_set_no_pre_silenced_output_buffer((&(*globalContext__audio95plugin95impl_u24).deviceConfig), ((NU32)1));
	ma_device_config_set_no_clip((&(*globalContext__audio95plugin95impl_u24).deviceConfig), ((NU32)1));
	ma_device_config_set_period_size((&(*globalContext__audio95plugin95impl_u24).deviceConfig), ((NU32)512));
	T17_ = (ma_context*)0;
	T17_ = (&(*globalContext__audio95plugin95impl_u24).context);
	T18_ = (ma_device_config*)0;
	T18_ = (&(*globalContext__audio95plugin95impl_u24).deviceConfig);
	initResult_1 = ma_device_init(T17_, T18_, (&(*globalContext__audio95plugin95impl_u24).device));
	{
		NimStringV2 colontmpD__6;
		tyArray__Re75IspeoxXy2oCZHwcRrA T24_;
		if (!!((initResult_1 == ((NI32)0)))) goto LA21_;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		T24_[0] = TM__YVJx3uIBl5j6Ek0bbYma1g_16;
		colontmpD__6 = dollar___systemZdollars_u29(initResult_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
		T24_[1] = colontmpD__6;
		echoBinSafe(T24_, 2);
		ma_context_uninit((&(*globalContext__audio95plugin95impl_u24).context));
		result = NIM_NIL;
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		goto BeforeRet_;
		{
			LA23_:;
		}
		{
			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA21_: ;
	initResult_1 = ma_device_start((&(*globalContext__audio95plugin95impl_u24).device));
	{
		NimStringV2 colontmpD__7;
		tyArray__Re75IspeoxXy2oCZHwcRrA T32_;
		if (!!((initResult_1 == ((NI32)0)))) goto LA29_;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		T32_[0] = TM__YVJx3uIBl5j6Ek0bbYma1g_18;
		colontmpD__7 = dollar___systemZdollars_u29(initResult_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
		T32_[1] = colontmpD__7;
		echoBinSafe(T32_, 2);
		ma_device_uninit((&(*globalContext__audio95plugin95impl_u24).device));
		ma_context_uninit((&(*globalContext__audio95plugin95impl_u24).context));
		result = NIM_NIL;
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		goto BeforeRet_;
		{
			LA31_:;
		}
		{
			if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA29_: ;
	(*globalContext__audio95plugin95impl_u24).initialized = NIM_TRUE;
	T35_[0] = TM__YVJx3uIBl5j6Ek0bbYma1g_20;
	colontmpD__3 = dollar___systemZdollars_u29(sampleRate_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T35_[1] = colontmpD__3;
	T35_[2] = TM__YVJx3uIBl5j6Ek0bbYma1g_22;
	colontmpD__4 = dollar___systemZdollars_u29(channels_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T35_[3] = colontmpD__4;
	T35_[4] = TM__YVJx3uIBl5j6Ek0bbYma1g_24;
	echoBinSafe(T35_, 5);
	result = ((void*) (globalContext__audio95plugin95impl_u24));
	if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, audio_plugin_cleanup)(void* ctx_p0) {
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = (globalContext__audio95plugin95impl_u24 == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	{
		int T11_;
		if (!(*globalContext__audio95plugin95impl_u24).initialized) goto LA9_;
		T11_ = (int)0;
		T11_ = ma_device_stop((&(*globalContext__audio95plugin95impl_u24).device));
		(void)(T11_);
		ma_device_uninit((&(*globalContext__audio95plugin95impl_u24).device));
		ma_context_uninit((&(*globalContext__audio95plugin95impl_u24).context));
		(*globalContext__audio95plugin95impl_u24).initialized = NIM_FALSE;
		echoBinSafe(TM__YVJx3uIBl5j6Ek0bbYma1g_25, 1);
	}
LA9_: ;
	eqsink___audio95plugin95impl_u596(&globalContext__audio95plugin95impl_u24, ((tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw*) NIM_NIL));
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(int, audio_plugin_play_sample)(void* ctx_p0, NF32* dataPtr_p1, int dataLen_p2, int channels_p3, int sampleRate_p4, float volume_p5) {
	int result;
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg sample_1;
	int colontmpD_;
	int colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimZeroMem((void*)(&sample_1), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (ctx_p0 == 0);
		if (T5_) goto LA6_;
		T5_ = (globalContext__audio95plugin95impl_u24 == 0);
LA6_: ;
		T4_ = T5_;
		if (T4_) goto LA7_;
		T4_ = !((*globalContext__audio95plugin95impl_u24).initialized);
LA7_: ;
		if (!T4_) goto LA8_;
		result = ((int)-1);
		eqdestroy___audio95gen_u412((&sample_1));
		goto BeforeRet_;
	}
LA8_: ;
	if ((dataLen_p2) < ((NI)0) || (dataLen_p2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(dataLen_p2, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	sample_1.data = newSeq__audio95gen_u157(((NI) (dataLen_p2)));
	colontmpD_ = sampleRate_p4;
	sample_1.sampleRate = ((NI) (colontmpD_));
	colontmpD__2 = channels_p3;
	sample_1.channels = ((NI) (colontmpD__2));
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (dataLen_p2));
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__YVJx3uIBl5j6Ek0bbYma1g_27;
				if (!(i_2 < colontmp_)) goto LA12;
				i_1 = i_2;
				if (i_1 < 0 || i_1 >= sample_1.data.len){ raiseIndexError2(i_1,sample_1.data.len-1); goto LA1_;
				}
				sample_1.data.p->data[i_1] = ((NF32)(dataPtr_p1[i_1]) * (NF32)(((NF32) (volume_p5))));
				if (nimAddInt(i_2, ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_27)) { raiseOverflow(); goto LA1_;
				};
				i_2 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_27);
			} LA12: ;
		}
	}
	{
		NIM_BOOL T15_;
		tySequence__4Xyxy0Om14N6K1l5e9bUPSQ stereoData_1;
		NI TM__YVJx3uIBl5j6Ek0bbYma1g_28;
		T15_ = (NIM_BOOL)0;
		T15_ = (channels_p3 == ((NI32)1));
		if (!(T15_)) goto LA16_;
		T15_ = ((*globalContext__audio95plugin95impl_u24).channels == ((NI)2));
LA16_: ;
		if (!T15_) goto LA17_;
		stereoData_1.len = 0; stereoData_1.p = NIM_NIL;
		if (nimMulInt(((NI) (dataLen_p2)), ((NI)2), &TM__YVJx3uIBl5j6Ek0bbYma1g_28)) { raiseOverflow(); goto LA1_;
		};
		if (((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_28)) < ((NI)0) || ((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_28)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_28), ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
		}
		stereoData_1 = newSeq__audio95gen_u157(((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_28)));
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = ((NI) (dataLen_p2));
			i_4 = ((NI)0);
			{
				while (1) {
					NI TM__YVJx3uIBl5j6Ek0bbYma1g_29;
					NI TM__YVJx3uIBl5j6Ek0bbYma1g_30;
					NI TM__YVJx3uIBl5j6Ek0bbYma1g_31;
					NI TM__YVJx3uIBl5j6Ek0bbYma1g_32;
					if (!(i_4 < colontmp__2)) goto LA21;
					i_3 = i_4;
					if (nimMulInt(i_3, ((NI)2), &TM__YVJx3uIBl5j6Ek0bbYma1g_29)) { raiseOverflow(); goto LA1_;
					};
					if ((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_29) < 0 || (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_29) >= stereoData_1.len){ raiseIndexError2((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_29),stereoData_1.len-1); goto LA1_;
					}
					if (i_3 < 0 || i_3 >= sample_1.data.len){ raiseIndexError2(i_3,sample_1.data.len-1); goto LA1_;
					}
					stereoData_1.p->data[(NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_29)] = sample_1.data.p->data[i_3];
					if (nimMulInt(i_3, ((NI)2), &TM__YVJx3uIBl5j6Ek0bbYma1g_30)) { raiseOverflow(); goto LA1_;
					};
					if (nimAddInt((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_30), ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_31)) { raiseOverflow(); goto LA1_;
					};
					if ((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_31) < 0 || (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_31) >= stereoData_1.len){ raiseIndexError2((NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_31),stereoData_1.len-1); goto LA1_;
					}
					if (i_3 < 0 || i_3 >= sample_1.data.len){ raiseIndexError2(i_3,sample_1.data.len-1); goto LA1_;
					}
					stereoData_1.p->data[(NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_31)] = sample_1.data.p->data[i_3];
					if (nimAddInt(i_4, ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_32)) { raiseOverflow(); goto LA1_;
					};
					i_4 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_32);
				} LA21: ;
			}
		}
		eqsink___audio95gen_u251((&sample_1.data), stereoData_1);
		sample_1.channels = ((NI)2);
	}
LA17_: ;
	{
		NIM_BOOL T24_;
		NI T25_;
		NI T27_;
		T24_ = (NIM_BOOL)0;
		T25_ = (*globalContext__audio95plugin95impl_u24).currentSample.data.len;
		T24_ = (T25_ == ((NI)0));
		if (T24_) goto LA26_;
		T27_ = (*globalContext__audio95plugin95impl_u24).currentSample.data.len;
		T24_ = (T27_ <= (*globalContext__audio95plugin95impl_u24).currentPosition);
LA26_: ;
		if (!T24_) goto LA28_;
		eqsink___audio95gen_u421((&(*globalContext__audio95plugin95impl_u24).currentSample), (&sample_1));
		eqwasMoved___audio95gen_u409((&sample_1));
		(*globalContext__audio95plugin95impl_u24).currentPosition = ((NI)0);
	}
	goto LA22_;
LA28_: ;
	{
		tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg blitTmp_1;
		nimZeroMem((void*)(&blitTmp_1), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
		blitTmp_1 = sample_1;
		eqwasMoved___audio95gen_u409((&sample_1));
		add__audio95plugin95impl_u776((&(*globalContext__audio95plugin95impl_u24).playbackQueue), (&blitTmp_1));
	}
LA22_: ;
	result = ((int)0);
	eqdestroy___audio95gen_u412((&sample_1));
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___audio95gen_u412((&sample_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, audio_plugin_stop_all)(void* ctx_p0) {
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg T7_;
	tySequence__qE1lkEbYXEtaF1pKH4BcRQ T8_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = (globalContext__audio95plugin95impl_u24 == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimZeroMem((void*)(&T7_), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	eqsink___audio95gen_u421((&(*globalContext__audio95plugin95impl_u24).currentSample), (&T7_));
	(*globalContext__audio95plugin95impl_u24).currentPosition = ((NI)0);
	T8_.len = 0; T8_.p = NIM_NIL;
	T8_.len = 0; T8_.p = (tySequence__qE1lkEbYXEtaF1pKH4BcRQ_Content*) newSeqPayload(0, sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg), NIM_ALIGNOF(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	eqsink___audio95plugin95impl_u218((&(*globalContext__audio95plugin95impl_u24).playbackQueue), T8_);
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(int, audio_plugin_register_sound)(void* ctx_p0, NCSTRING namePtr_p1, NF32* dataPtr_p2, int dataLen_p3, int channels_p4, int sampleRate_p5) {
	int result;
	NimStringV2 name_1;
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg sample_1;
	int colontmpD_;
	int colontmpD__2;
	tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg blitTmp_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (int)0;
	name_1.len = 0; name_1.p = NIM_NIL;
	nimZeroMem((void*)(&sample_1), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = (ctx_p0 == 0);
		if (T4_) goto LA5_;
		T4_ = (globalContext__audio95plugin95impl_u24 == 0);
LA5_: ;
		if (!T4_) goto LA6_;
		result = ((int)-1);
		eqdestroy___audio95gen_u412((&sample_1));
		if (name_1.p && !(name_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(name_1.p);
}
		goto BeforeRet_;
	}
LA6_: ;
	name_1 = cstrToNimstr(namePtr_p1);
	if ((dataLen_p3) < ((NI)0) || (dataLen_p3) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(dataLen_p3, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	sample_1.data = newSeq__audio95gen_u157(((NI) (dataLen_p3)));
	colontmpD_ = sampleRate_p5;
	sample_1.sampleRate = ((NI) (colontmpD_));
	colontmpD__2 = channels_p4;
	sample_1.channels = ((NI) (colontmpD__2));
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (dataLen_p3));
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__YVJx3uIBl5j6Ek0bbYma1g_33;
				if (!(i_2 < colontmp_)) goto LA10;
				i_1 = i_2;
				if (i_1 < 0 || i_1 >= sample_1.data.len){ raiseIndexError2(i_1,sample_1.data.len-1); goto LA1_;
				}
				sample_1.data.p->data[i_1] = dataPtr_p2[i_1];
				if (nimAddInt(i_2, ((NI)1), &TM__YVJx3uIBl5j6Ek0bbYma1g_33)) { raiseOverflow(); goto LA1_;
				};
				i_2 = (NI)(TM__YVJx3uIBl5j6Ek0bbYma1g_33);
			} LA10: ;
		}
	}
	nimZeroMem((void*)(&blitTmp_1), sizeof(tyObject_AudioSample__XvL5YQst1IUp9aRFuVzA6hg));
	blitTmp_1 = sample_1;
	eqwasMoved___audio95gen_u409((&sample_1));
	X5BX5Deq___audio95plugin95impl_u879((&(*globalContext__audio95plugin95impl_u24).sounds), name_1, (&blitTmp_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = ((int)0);
	eqdestroy___audio95gen_u412((&sample_1));
	if (name_1.p && !(name_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(name_1.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___audio95gen_u412((&sample_1));
		if (name_1.p && !(name_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(name_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NCSTRING, audio_plugin_get_version)(void) {
	NCSTRING result;
{	result = "audio_plugin v1.0.0 (miniaudio)";
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(int, audio_plugin_is_initialized)(void* ctx_p0) {
	int result;
	int colontmpD_;
	int colontmpD__2;
{	colontmpD_ = (int)0;
	colontmpD__2 = (int)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ctx_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = (globalContext__audio95plugin95impl_u24 == 0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = ((int)0);
		goto BeforeRet_;
	}
LA5_: ;
	{
		if (!(*globalContext__audio95plugin95impl_u24).initialized) goto LA9_;
		colontmpD_ = ((int)1);
		result = colontmpD_;
	}
	goto LA7_;
LA9_: ;
	{
		colontmpD__2 = ((int)0);
		result = colontmpD__2;
	}
LA7_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___audio95plugin95impl_u587)(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___audio95plugin95impl_u553((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)NIM_ALIGNOF(tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw)));
	}
LA4_: ;
}
N_LIB_EXPORT N_CDECL(void, NimDestroyGlobals)(void) {
	eqdestroy___audio95plugin95impl_u587(globalContext__audio95plugin95impl_u24);
}

N_LIB_PRIVATE void PreMainInner(void) {
	atprandomdotnim_Init000();
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	globalContext__audio95plugin95impl_u24 = ((tyObject_PluginAudioContextcolonObjectType___o8yZaWtAzaBlSykKuE69bQw*) NIM_NIL);
	nimTestErrorFlag();
}
}

