/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -I/workspaces/telestorie/lib -Os -fno-ident  -fPIC  -I/home/codespace/.choosenim/toolchains/nim-2.2.6/lib -I/workspaces/telestorie/lib -o /workspaces/telestorie/nimcache_audio_plugin/@ptimes.nim.c.o /workspaces/telestorie/nimcache_audio_plugin/@ptimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* utcInstance__pureZtimes_u2031;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___A8L9bxBrm10ubIAzlwnw7zw* localInstance__pureZtimes_u2032;
